// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/models/components"
	"github.com/kenrogers/openrouter-cli/internal/sdk/optionalnullable"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type CreateAuthKeysCodeGlobals struct {
	// The app identifier should be your app's URL and is used as the primary identifier for rankings.
	// This is used to track API usage per application.
	//
	HTTPReferer *string `header:"style=simple,explode=false,name=HTTP-Referer"`
	// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
	//
	AppTitle *string `header:"style=simple,explode=false,name=X-OpenRouter-Title"`
	// Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
	//
	AppCategories *string `header:"style=simple,explode=false,name=X-OpenRouter-Categories"`
}

func (c *CreateAuthKeysCodeGlobals) GetHTTPReferer() *string {
	if c == nil {
		return nil
	}
	return c.HTTPReferer
}

func (c *CreateAuthKeysCodeGlobals) GetAppTitle() *string {
	if c == nil {
		return nil
	}
	return c.AppTitle
}

func (c *CreateAuthKeysCodeGlobals) GetAppCategories() *string {
	if c == nil {
		return nil
	}
	return c.AppCategories
}

// CreateAuthKeysCodeCodeChallengeMethod - The method used to generate the code challenge
type CreateAuthKeysCodeCodeChallengeMethod string

const (
	CreateAuthKeysCodeCodeChallengeMethodS256  CreateAuthKeysCodeCodeChallengeMethod = "S256"
	CreateAuthKeysCodeCodeChallengeMethodPlain CreateAuthKeysCodeCodeChallengeMethod = "plain"
)

func (e CreateAuthKeysCodeCodeChallengeMethod) ToPointer() *CreateAuthKeysCodeCodeChallengeMethod {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CreateAuthKeysCodeCodeChallengeMethod) IsExact() bool {
	if e != nil {
		switch *e {
		case "S256", "plain":
			return true
		}
	}
	return false
}

// UsageLimitType - Optional credit limit reset interval. When set, the credit limit resets on this interval.
type UsageLimitType string

const (
	UsageLimitTypeDaily   UsageLimitType = "daily"
	UsageLimitTypeWeekly  UsageLimitType = "weekly"
	UsageLimitTypeMonthly UsageLimitType = "monthly"
)

func (e UsageLimitType) ToPointer() *UsageLimitType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *UsageLimitType) IsExact() bool {
	if e != nil {
		switch *e {
		case "daily", "weekly", "monthly":
			return true
		}
	}
	return false
}

type CreateAuthKeysCodeRequestBody struct {
	// The callback URL to redirect to after authorization. Note, only https URLs on ports 443 and 3000 are allowed.
	CallbackURL string `json:"callback_url"`
	// PKCE code challenge for enhanced security
	CodeChallenge *string `json:"code_challenge,omitzero"`
	// The method used to generate the code challenge
	CodeChallengeMethod *CreateAuthKeysCodeCodeChallengeMethod `json:"code_challenge_method,omitzero"`
	// Optional expiration time for the API key to be created
	ExpiresAt optionalnullable.OptionalNullable[time.Time] `json:"expires_at,omitzero"`
	// Optional custom label for the API key. Defaults to the app name if not provided.
	KeyLabel *string `json:"key_label,omitzero"`
	// Credit limit for the API key to be created
	Limit *float64 `json:"limit,omitzero"`
	// Optional credit limit reset interval. When set, the credit limit resets on this interval.
	UsageLimitType *UsageLimitType `json:"usage_limit_type,omitzero"`
}

func (c CreateAuthKeysCodeRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateAuthKeysCodeRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateAuthKeysCodeRequestBody) GetCallbackURL() string {
	if c == nil {
		return ""
	}
	return c.CallbackURL
}

func (c *CreateAuthKeysCodeRequestBody) GetCodeChallenge() *string {
	if c == nil {
		return nil
	}
	return c.CodeChallenge
}

func (c *CreateAuthKeysCodeRequestBody) GetCodeChallengeMethod() *CreateAuthKeysCodeCodeChallengeMethod {
	if c == nil {
		return nil
	}
	return c.CodeChallengeMethod
}

func (c *CreateAuthKeysCodeRequestBody) GetExpiresAt() optionalnullable.OptionalNullable[time.Time] {
	if c == nil {
		return nil
	}
	return c.ExpiresAt
}

func (c *CreateAuthKeysCodeRequestBody) GetKeyLabel() *string {
	if c == nil {
		return nil
	}
	return c.KeyLabel
}

func (c *CreateAuthKeysCodeRequestBody) GetLimit() *float64 {
	if c == nil {
		return nil
	}
	return c.Limit
}

func (c *CreateAuthKeysCodeRequestBody) GetUsageLimitType() *UsageLimitType {
	if c == nil {
		return nil
	}
	return c.UsageLimitType
}

type CreateAuthKeysCodeRequest struct {
	// The app identifier should be your app's URL and is used as the primary identifier for rankings.
	// This is used to track API usage per application.
	//
	HTTPReferer *string `header:"style=simple,explode=false,name=HTTP-Referer"`
	// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
	//
	AppTitle *string `header:"style=simple,explode=false,name=X-OpenRouter-Title"`
	// Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
	//
	AppCategories *string                       `header:"style=simple,explode=false,name=X-OpenRouter-Categories"`
	Body          CreateAuthKeysCodeRequestBody `request:"mediaType=application/json"`
}

func (c *CreateAuthKeysCodeRequest) GetHTTPReferer() *string {
	if c == nil {
		return nil
	}
	return c.HTTPReferer
}

func (c *CreateAuthKeysCodeRequest) GetAppTitle() *string {
	if c == nil {
		return nil
	}
	return c.AppTitle
}

func (c *CreateAuthKeysCodeRequest) GetAppCategories() *string {
	if c == nil {
		return nil
	}
	return c.AppCategories
}

func (c *CreateAuthKeysCodeRequest) GetBody() CreateAuthKeysCodeRequestBody {
	if c == nil {
		return CreateAuthKeysCodeRequestBody{}
	}
	return c.Body
}

// Data - Auth code data
type Data struct {
	// The application ID associated with this auth code
	AppID int64 `json:"app_id"`
	// ISO 8601 timestamp of when the auth code was created
	CreatedAt string `json:"created_at"`
	// The authorization code ID to use in the exchange request
	ID string `json:"id"`
}

func (d *Data) GetAppID() int64 {
	if d == nil {
		return 0
	}
	return d.AppID
}

func (d *Data) GetCreatedAt() string {
	if d == nil {
		return ""
	}
	return d.CreatedAt
}

func (d *Data) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

// CreateAuthKeysCodeResponseBody - Successfully created authorization code
type CreateAuthKeysCodeResponseBody struct {
	// Auth code data
	Data Data `json:"data"`
}

func (c *CreateAuthKeysCodeResponseBody) GetData() Data {
	if c == nil {
		return Data{}
	}
	return c.Data
}

type CreateAuthKeysCodeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successfully created authorization code
	Object *CreateAuthKeysCodeResponseBody
}

func (c CreateAuthKeysCodeResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateAuthKeysCodeResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateAuthKeysCodeResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateAuthKeysCodeResponse) GetObject() *CreateAuthKeysCodeResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
