// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/models/components"
	"github.com/kenrogers/openrouter-cli/internal/sdk/optionalnullable"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type CreateRerankGlobals struct {
	// The app identifier should be your app's URL and is used as the primary identifier for rankings.
	// This is used to track API usage per application.
	//
	HTTPReferer *string `header:"style=simple,explode=false,name=HTTP-Referer"`
	// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
	//
	AppTitle *string `header:"style=simple,explode=false,name=X-OpenRouter-Title"`
	// Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
	//
	AppCategories *string `header:"style=simple,explode=false,name=X-OpenRouter-Categories"`
}

func (c *CreateRerankGlobals) GetHTTPReferer() *string {
	if c == nil {
		return nil
	}
	return c.HTTPReferer
}

func (c *CreateRerankGlobals) GetAppTitle() *string {
	if c == nil {
		return nil
	}
	return c.AppTitle
}

func (c *CreateRerankGlobals) GetAppCategories() *string {
	if c == nil {
		return nil
	}
	return c.AppCategories
}

// CreateRerankRequestBody - Rerank request input
type CreateRerankRequestBody struct {
	// The list of documents to rerank
	Documents []string `json:"documents"`
	// The rerank model to use
	Model    string                                                            `json:"model"`
	Provider optionalnullable.OptionalNullable[components.ProviderPreferences] `json:"provider,omitzero"`
	// The search query to rerank documents against
	Query string `json:"query"`
	// Number of most relevant documents to return
	TopN *int64 `json:"top_n,omitzero"`
}

func (c CreateRerankRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateRerankRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateRerankRequestBody) GetDocuments() []string {
	if c == nil {
		return []string{}
	}
	return c.Documents
}

func (c *CreateRerankRequestBody) GetModel() string {
	if c == nil {
		return ""
	}
	return c.Model
}

func (c *CreateRerankRequestBody) GetProvider() optionalnullable.OptionalNullable[components.ProviderPreferences] {
	if c == nil {
		return nil
	}
	return c.Provider
}

func (c *CreateRerankRequestBody) GetQuery() string {
	if c == nil {
		return ""
	}
	return c.Query
}

func (c *CreateRerankRequestBody) GetTopN() *int64 {
	if c == nil {
		return nil
	}
	return c.TopN
}

type CreateRerankRequest struct {
	// The app identifier should be your app's URL and is used as the primary identifier for rankings.
	// This is used to track API usage per application.
	//
	HTTPReferer *string `header:"style=simple,explode=false,name=HTTP-Referer"`
	// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
	//
	AppTitle *string `header:"style=simple,explode=false,name=X-OpenRouter-Title"`
	// Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
	//
	AppCategories *string                 `header:"style=simple,explode=false,name=X-OpenRouter-Categories"`
	Body          CreateRerankRequestBody `request:"mediaType=application/json"`
}

func (c *CreateRerankRequest) GetHTTPReferer() *string {
	if c == nil {
		return nil
	}
	return c.HTTPReferer
}

func (c *CreateRerankRequest) GetAppTitle() *string {
	if c == nil {
		return nil
	}
	return c.AppTitle
}

func (c *CreateRerankRequest) GetAppCategories() *string {
	if c == nil {
		return nil
	}
	return c.AppCategories
}

func (c *CreateRerankRequest) GetBody() CreateRerankRequestBody {
	if c == nil {
		return CreateRerankRequestBody{}
	}
	return c.Body
}

// Document - The document object containing the original text
type Document struct {
	// The document text
	Text string `json:"text"`
}

func (d *Document) GetText() string {
	if d == nil {
		return ""
	}
	return d.Text
}

// Results - A single rerank result
type Results struct {
	// The document object containing the original text
	Document Document `json:"document"`
	// Index of the document in the original input list
	Index int64 `json:"index"`
	// Relevance score of the document to the query
	RelevanceScore float64 `json:"relevance_score"`
}

func (r *Results) GetDocument() Document {
	if r == nil {
		return Document{}
	}
	return r.Document
}

func (r *Results) GetIndex() int64 {
	if r == nil {
		return 0
	}
	return r.Index
}

func (r *Results) GetRelevanceScore() float64 {
	if r == nil {
		return 0.0
	}
	return r.RelevanceScore
}

// CreateRerankUsage - Usage statistics
type CreateRerankUsage struct {
	// Cost of the request in credits
	Cost *float64 `json:"cost,omitzero"`
	// Number of search units consumed (Cohere billing)
	SearchUnits *int64 `json:"search_units,omitzero"`
	// Total number of tokens used
	TotalTokens *int64 `json:"total_tokens,omitzero"`
}

func (c *CreateRerankUsage) GetCost() *float64 {
	if c == nil {
		return nil
	}
	return c.Cost
}

func (c *CreateRerankUsage) GetSearchUnits() *int64 {
	if c == nil {
		return nil
	}
	return c.SearchUnits
}

func (c *CreateRerankUsage) GetTotalTokens() *int64 {
	if c == nil {
		return nil
	}
	return c.TotalTokens
}

// CreateRerankResponseBody - Rerank response containing ranked results
type CreateRerankResponseBody struct {
	// Unique identifier for the rerank response (ORID format)
	ID *string `json:"id,omitzero"`
	// The model used for reranking
	Model string `json:"model"`
	// The provider that served the rerank request
	Provider *string `json:"provider,omitzero"`
	// List of rerank results sorted by relevance
	Results []Results `json:"results"`
	// Usage statistics
	Usage *CreateRerankUsage `json:"usage,omitzero"`
}

func (c CreateRerankResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateRerankResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateRerankResponseBody) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CreateRerankResponseBody) GetModel() string {
	if c == nil {
		return ""
	}
	return c.Model
}

func (c *CreateRerankResponseBody) GetProvider() *string {
	if c == nil {
		return nil
	}
	return c.Provider
}

func (c *CreateRerankResponseBody) GetResults() []Results {
	if c == nil {
		return []Results{}
	}
	return c.Results
}

func (c *CreateRerankResponseBody) GetUsage() *CreateRerankUsage {
	if c == nil {
		return nil
	}
	return c.Usage
}

type CreateRerankResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Rerank response
	Object *CreateRerankResponseBody
	// Rerank response
	Res *string
}

func (c CreateRerankResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateRerankResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateRerankResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateRerankResponse) GetObject() *CreateRerankResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}

func (c *CreateRerankResponse) GetRes() *string {
	if c == nil {
		return nil
	}
	return c.Res
}
