// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/models/components"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type CreatePresetsChatCompletionsGlobals struct {
	// The app identifier should be your app's URL and is used as the primary identifier for rankings.
	// This is used to track API usage per application.
	//
	HTTPReferer *string `header:"style=simple,explode=false,name=HTTP-Referer"`
	// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
	//
	AppTitle *string `header:"style=simple,explode=false,name=X-OpenRouter-Title"`
	// Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
	//
	AppCategories *string `header:"style=simple,explode=false,name=X-OpenRouter-Categories"`
}

func (c *CreatePresetsChatCompletionsGlobals) GetHTTPReferer() *string {
	if c == nil {
		return nil
	}
	return c.HTTPReferer
}

func (c *CreatePresetsChatCompletionsGlobals) GetAppTitle() *string {
	if c == nil {
		return nil
	}
	return c.AppTitle
}

func (c *CreatePresetsChatCompletionsGlobals) GetAppCategories() *string {
	if c == nil {
		return nil
	}
	return c.AppCategories
}

type CreatePresetsChatCompletionsRequest struct {
	// The app identifier should be your app's URL and is used as the primary identifier for rankings.
	// This is used to track API usage per application.
	//
	HTTPReferer *string `header:"style=simple,explode=false,name=HTTP-Referer"`
	// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
	//
	AppTitle *string `header:"style=simple,explode=false,name=X-OpenRouter-Title"`
	// Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
	//
	AppCategories *string `header:"style=simple,explode=false,name=X-OpenRouter-Categories"`
	// URL-safe slug identifying the preset. Created if it does not exist.
	Slug string                 `pathParam:"style=simple,explode=false,name=slug"`
	Body components.ChatRequest `request:"mediaType=application/json"`
}

func (c *CreatePresetsChatCompletionsRequest) GetHTTPReferer() *string {
	if c == nil {
		return nil
	}
	return c.HTTPReferer
}

func (c *CreatePresetsChatCompletionsRequest) GetAppTitle() *string {
	if c == nil {
		return nil
	}
	return c.AppTitle
}

func (c *CreatePresetsChatCompletionsRequest) GetAppCategories() *string {
	if c == nil {
		return nil
	}
	return c.AppCategories
}

func (c *CreatePresetsChatCompletionsRequest) GetSlug() string {
	if c == nil {
		return ""
	}
	return c.Slug
}

func (c *CreatePresetsChatCompletionsRequest) GetBody() components.ChatRequest {
	if c == nil {
		return components.ChatRequest{}
	}
	return c.Body
}

type CreatePresetsChatCompletionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Preset created or updated successfully.
	CreatePresetFromInferenceResponse *components.CreatePresetFromInferenceResponse
}

func (c CreatePresetsChatCompletionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreatePresetsChatCompletionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreatePresetsChatCompletionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreatePresetsChatCompletionsResponse) GetCreatePresetFromInferenceResponse() *components.CreatePresetFromInferenceResponse {
	if c == nil {
		return nil
	}
	return c.CreatePresetFromInferenceResponse
}
