// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/models/components"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type DeleteGuardrailGlobals struct {
	// The app identifier should be your app's URL and is used as the primary identifier for rankings.
	// This is used to track API usage per application.
	//
	HTTPReferer *string `header:"style=simple,explode=false,name=HTTP-Referer"`
	// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
	//
	AppTitle *string `header:"style=simple,explode=false,name=X-OpenRouter-Title"`
	// Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
	//
	AppCategories *string `header:"style=simple,explode=false,name=X-OpenRouter-Categories"`
}

func (d *DeleteGuardrailGlobals) GetHTTPReferer() *string {
	if d == nil {
		return nil
	}
	return d.HTTPReferer
}

func (d *DeleteGuardrailGlobals) GetAppTitle() *string {
	if d == nil {
		return nil
	}
	return d.AppTitle
}

func (d *DeleteGuardrailGlobals) GetAppCategories() *string {
	if d == nil {
		return nil
	}
	return d.AppCategories
}

type DeleteGuardrailRequest struct {
	// The app identifier should be your app's URL and is used as the primary identifier for rankings.
	// This is used to track API usage per application.
	//
	HTTPReferer *string `header:"style=simple,explode=false,name=HTTP-Referer"`
	// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
	//
	AppTitle *string `header:"style=simple,explode=false,name=X-OpenRouter-Title"`
	// Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
	//
	AppCategories *string `header:"style=simple,explode=false,name=X-OpenRouter-Categories"`
	// The unique identifier of the guardrail to delete
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteGuardrailRequest) GetHTTPReferer() *string {
	if d == nil {
		return nil
	}
	return d.HTTPReferer
}

func (d *DeleteGuardrailRequest) GetAppTitle() *string {
	if d == nil {
		return nil
	}
	return d.AppTitle
}

func (d *DeleteGuardrailRequest) GetAppCategories() *string {
	if d == nil {
		return nil
	}
	return d.AppCategories
}

func (d *DeleteGuardrailRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteGuardrailResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Guardrail deleted successfully
	DeleteGuardrailResponse *components.DeleteGuardrailResponse
}

func (d DeleteGuardrailResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteGuardrailResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteGuardrailResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteGuardrailResponse) GetDeleteGuardrailResponse() *components.DeleteGuardrailResponse {
	if d == nil {
		return nil
	}
	return d.DeleteGuardrailResponse
}
