// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/models/components"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type ListGenerationContentGlobals struct {
	// The app identifier should be your app's URL and is used as the primary identifier for rankings.
	// This is used to track API usage per application.
	//
	HTTPReferer *string `header:"style=simple,explode=false,name=HTTP-Referer"`
	// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
	//
	AppTitle *string `header:"style=simple,explode=false,name=X-OpenRouter-Title"`
	// Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
	//
	AppCategories *string `header:"style=simple,explode=false,name=X-OpenRouter-Categories"`
}

func (l *ListGenerationContentGlobals) GetHTTPReferer() *string {
	if l == nil {
		return nil
	}
	return l.HTTPReferer
}

func (l *ListGenerationContentGlobals) GetAppTitle() *string {
	if l == nil {
		return nil
	}
	return l.AppTitle
}

func (l *ListGenerationContentGlobals) GetAppCategories() *string {
	if l == nil {
		return nil
	}
	return l.AppCategories
}

type ListGenerationContentRequest struct {
	// The app identifier should be your app's URL and is used as the primary identifier for rankings.
	// This is used to track API usage per application.
	//
	HTTPReferer *string `header:"style=simple,explode=false,name=HTTP-Referer"`
	// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
	//
	AppTitle *string `header:"style=simple,explode=false,name=X-OpenRouter-Title"`
	// Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
	//
	AppCategories *string `header:"style=simple,explode=false,name=X-OpenRouter-Categories"`
	// The generation ID
	ID string `queryParam:"style=form,explode=true,name=id"`
}

func (l *ListGenerationContentRequest) GetHTTPReferer() *string {
	if l == nil {
		return nil
	}
	return l.HTTPReferer
}

func (l *ListGenerationContentRequest) GetAppTitle() *string {
	if l == nil {
		return nil
	}
	return l.AppTitle
}

func (l *ListGenerationContentRequest) GetAppCategories() *string {
	if l == nil {
		return nil
	}
	return l.AppCategories
}

func (l *ListGenerationContentRequest) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

type ListGenerationContentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns the stored prompt and completion content
	GenerationContentResponse *components.GenerationContentResponse
}

func (l ListGenerationContentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListGenerationContentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListGenerationContentResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListGenerationContentResponse) GetGenerationContentResponse() *components.GenerationContentResponse {
	if l == nil {
		return nil
	}
	return l.GenerationContentResponse
}
