// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/models/components"
	"github.com/kenrogers/openrouter-cli/internal/sdk/optionalnullable"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type ListGuardrailsGlobals struct {
	// The app identifier should be your app's URL and is used as the primary identifier for rankings.
	// This is used to track API usage per application.
	//
	HTTPReferer *string `header:"style=simple,explode=false,name=HTTP-Referer"`
	// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
	//
	AppTitle *string `header:"style=simple,explode=false,name=X-OpenRouter-Title"`
	// Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
	//
	AppCategories *string `header:"style=simple,explode=false,name=X-OpenRouter-Categories"`
}

func (l *ListGuardrailsGlobals) GetHTTPReferer() *string {
	if l == nil {
		return nil
	}
	return l.HTTPReferer
}

func (l *ListGuardrailsGlobals) GetAppTitle() *string {
	if l == nil {
		return nil
	}
	return l.AppTitle
}

func (l *ListGuardrailsGlobals) GetAppCategories() *string {
	if l == nil {
		return nil
	}
	return l.AppCategories
}

type ListGuardrailsRequest struct {
	// The app identifier should be your app's URL and is used as the primary identifier for rankings.
	// This is used to track API usage per application.
	//
	HTTPReferer *string `header:"style=simple,explode=false,name=HTTP-Referer"`
	// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
	//
	AppTitle *string `header:"style=simple,explode=false,name=X-OpenRouter-Title"`
	// Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
	//
	AppCategories *string `header:"style=simple,explode=false,name=X-OpenRouter-Categories"`
	// Number of records to skip for pagination
	Offset optionalnullable.OptionalNullable[int64] `queryParam:"style=form,explode=true,name=offset"`
	// Maximum number of records to return (max 100)
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Filter guardrails by workspace ID. By default, guardrails in the default workspace are returned.
	WorkspaceID *string `queryParam:"style=form,explode=true,name=workspace_id"`
}

func (l *ListGuardrailsRequest) GetHTTPReferer() *string {
	if l == nil {
		return nil
	}
	return l.HTTPReferer
}

func (l *ListGuardrailsRequest) GetAppTitle() *string {
	if l == nil {
		return nil
	}
	return l.AppTitle
}

func (l *ListGuardrailsRequest) GetAppCategories() *string {
	if l == nil {
		return nil
	}
	return l.AppCategories
}

func (l *ListGuardrailsRequest) GetOffset() optionalnullable.OptionalNullable[int64] {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListGuardrailsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListGuardrailsRequest) GetWorkspaceID() *string {
	if l == nil {
		return nil
	}
	return l.WorkspaceID
}

type ListGuardrailsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of guardrails
	ListGuardrailsResponse *components.ListGuardrailsResponse

	Next func() (*ListGuardrailsResponse, error)
}

func (l ListGuardrailsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListGuardrailsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListGuardrailsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListGuardrailsResponse) GetListGuardrailsResponse() *components.ListGuardrailsResponse {
	if l == nil {
		return nil
	}
	return l.ListGuardrailsResponse
}
