// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/models/components"
	"github.com/kenrogers/openrouter-cli/internal/sdk/optionalnullable"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type ListBYOKKeysGlobals struct {
	// The app identifier should be your app's URL and is used as the primary identifier for rankings.
	// This is used to track API usage per application.
	//
	HTTPReferer *string `header:"style=simple,explode=false,name=HTTP-Referer"`
	// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
	//
	AppTitle *string `header:"style=simple,explode=false,name=X-OpenRouter-Title"`
	// Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
	//
	AppCategories *string `header:"style=simple,explode=false,name=X-OpenRouter-Categories"`
}

func (l *ListBYOKKeysGlobals) GetHTTPReferer() *string {
	if l == nil {
		return nil
	}
	return l.HTTPReferer
}

func (l *ListBYOKKeysGlobals) GetAppTitle() *string {
	if l == nil {
		return nil
	}
	return l.AppTitle
}

func (l *ListBYOKKeysGlobals) GetAppCategories() *string {
	if l == nil {
		return nil
	}
	return l.AppCategories
}

// Provider - Optional provider slug to filter by (e.g. `openai`, `anthropic`, `amazon-bedrock`).
type Provider string

const (
	ProviderAi21            Provider = "ai21"
	ProviderAionLabs        Provider = "aion-labs"
	ProviderAkashml         Provider = "akashml"
	ProviderAlibaba         Provider = "alibaba"
	ProviderAmazonBedrock   Provider = "amazon-bedrock"
	ProviderAmazonNova      Provider = "amazon-nova"
	ProviderAmbient         Provider = "ambient"
	ProviderAnthropic       Provider = "anthropic"
	ProviderArceeAi         Provider = "arcee-ai"
	ProviderAtlasCloud      Provider = "atlas-cloud"
	ProviderAvian           Provider = "avian"
	ProviderAzure           Provider = "azure"
	ProviderBaidu           Provider = "baidu"
	ProviderBaseten         Provider = "baseten"
	ProviderBlackForestLabs Provider = "black-forest-labs"
	ProviderByteplus        Provider = "byteplus"
	ProviderCerebras        Provider = "cerebras"
	ProviderChutes          Provider = "chutes"
	ProviderCirrascale      Provider = "cirrascale"
	ProviderClarifai        Provider = "clarifai"
	ProviderCloudflare      Provider = "cloudflare"
	ProviderCohere          Provider = "cohere"
	ProviderCrusoe          Provider = "crusoe"
	ProviderDeepinfra       Provider = "deepinfra"
	ProviderDeepseek        Provider = "deepseek"
	ProviderDekallm         Provider = "dekallm"
	ProviderFeatherless     Provider = "featherless"
	ProviderFireworks       Provider = "fireworks"
	ProviderFriendli        Provider = "friendli"
	ProviderGmicloud        Provider = "gmicloud"
	ProviderGoogleAiStudio  Provider = "google-ai-studio"
	ProviderGoogleVertex    Provider = "google-vertex"
	ProviderGroq            Provider = "groq"
	ProviderHyperbolic      Provider = "hyperbolic"
	ProviderInception       Provider = "inception"
	ProviderInceptron       Provider = "inceptron"
	ProviderInferenceNet    Provider = "inference-net"
	ProviderInfermatic      Provider = "infermatic"
	ProviderInflection      Provider = "inflection"
	ProviderIoNet           Provider = "io-net"
	ProviderIonstream       Provider = "ionstream"
	ProviderLiquid          Provider = "liquid"
	ProviderMancer          Provider = "mancer"
	ProviderMara            Provider = "mara"
	ProviderMinimax         Provider = "minimax"
	ProviderMistral         Provider = "mistral"
	ProviderModelrun        Provider = "modelrun"
	ProviderModular         Provider = "modular"
	ProviderMoonshotai      Provider = "moonshotai"
	ProviderMorph           Provider = "morph"
	ProviderNcompass        Provider = "ncompass"
	ProviderNebius          Provider = "nebius"
	ProviderNexAgi          Provider = "nex-agi"
	ProviderNextbit         Provider = "nextbit"
	ProviderNovita          Provider = "novita"
	ProviderNvidia          Provider = "nvidia"
	ProviderOpenInference   Provider = "open-inference"
	ProviderOpenai          Provider = "openai"
	ProviderParasail        Provider = "parasail"
	ProviderPerceptron      Provider = "perceptron"
	ProviderPerplexity      Provider = "perplexity"
	ProviderPhala           Provider = "phala"
	ProviderPoolside        Provider = "poolside"
	ProviderRecraft         Provider = "recraft"
	ProviderReka            Provider = "reka"
	ProviderRelace          Provider = "relace"
	ProviderSambanova       Provider = "sambanova"
	ProviderSeed            Provider = "seed"
	ProviderSiliconflow     Provider = "siliconflow"
	ProviderSourceful       Provider = "sourceful"
	ProviderStepfun         Provider = "stepfun"
	ProviderStreamlake      Provider = "streamlake"
	ProviderSwitchpoint     Provider = "switchpoint"
	ProviderTogether        Provider = "together"
	ProviderUpstage         Provider = "upstage"
	ProviderVenice          Provider = "venice"
	ProviderWandb           Provider = "wandb"
	ProviderXai             Provider = "xai"
	ProviderXiaomi          Provider = "xiaomi"
	ProviderZAi             Provider = "z-ai"
)

func (e Provider) ToPointer() *Provider {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Provider) IsExact() bool {
	if e != nil {
		switch *e {
		case "ai21", "aion-labs", "akashml", "alibaba", "amazon-bedrock", "amazon-nova", "ambient", "anthropic", "arcee-ai", "atlas-cloud", "avian", "azure", "baidu", "baseten", "black-forest-labs", "byteplus", "cerebras", "chutes", "cirrascale", "clarifai", "cloudflare", "cohere", "crusoe", "deepinfra", "deepseek", "dekallm", "featherless", "fireworks", "friendli", "gmicloud", "google-ai-studio", "google-vertex", "groq", "hyperbolic", "inception", "inceptron", "inference-net", "infermatic", "inflection", "io-net", "ionstream", "liquid", "mancer", "mara", "minimax", "mistral", "modelrun", "modular", "moonshotai", "morph", "ncompass", "nebius", "nex-agi", "nextbit", "novita", "nvidia", "open-inference", "openai", "parasail", "perceptron", "perplexity", "phala", "poolside", "recraft", "reka", "relace", "sambanova", "seed", "siliconflow", "sourceful", "stepfun", "streamlake", "switchpoint", "together", "upstage", "venice", "wandb", "xai", "xiaomi", "z-ai":
			return true
		}
	}
	return false
}

type ListBYOKKeysRequest struct {
	// The app identifier should be your app's URL and is used as the primary identifier for rankings.
	// This is used to track API usage per application.
	//
	HTTPReferer *string `header:"style=simple,explode=false,name=HTTP-Referer"`
	// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
	//
	AppTitle *string `header:"style=simple,explode=false,name=X-OpenRouter-Title"`
	// Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
	//
	AppCategories *string `header:"style=simple,explode=false,name=X-OpenRouter-Categories"`
	// Number of records to skip for pagination
	Offset optionalnullable.OptionalNullable[int64] `queryParam:"style=form,explode=true,name=offset"`
	// Maximum number of records to return (max 100)
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Optional workspace ID to filter by. Defaults to the authenticated entity's default workspace.
	WorkspaceID *string `queryParam:"style=form,explode=true,name=workspace_id"`
	// Optional provider slug to filter by (e.g. `openai`, `anthropic`, `amazon-bedrock`).
	Provider *Provider `queryParam:"style=form,explode=true,name=provider"`
}

func (l *ListBYOKKeysRequest) GetHTTPReferer() *string {
	if l == nil {
		return nil
	}
	return l.HTTPReferer
}

func (l *ListBYOKKeysRequest) GetAppTitle() *string {
	if l == nil {
		return nil
	}
	return l.AppTitle
}

func (l *ListBYOKKeysRequest) GetAppCategories() *string {
	if l == nil {
		return nil
	}
	return l.AppCategories
}

func (l *ListBYOKKeysRequest) GetOffset() optionalnullable.OptionalNullable[int64] {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListBYOKKeysRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListBYOKKeysRequest) GetWorkspaceID() *string {
	if l == nil {
		return nil
	}
	return l.WorkspaceID
}

func (l *ListBYOKKeysRequest) GetProvider() *Provider {
	if l == nil {
		return nil
	}
	return l.Provider
}

type ListBYOKKeysResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of BYOK credentials
	ListBYOKKeysResponse *components.ListBYOKKeysResponse

	Next func() (*ListBYOKKeysResponse, error)
}

func (l ListBYOKKeysResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListBYOKKeysResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListBYOKKeysResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListBYOKKeysResponse) GetListBYOKKeysResponse() *components.ListBYOKKeysResponse {
	if l == nil {
		return nil
	}
	return l.ListBYOKKeysResponse
}
