// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/models/components"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type UpdateGuardrailGlobals struct {
	// The app identifier should be your app's URL and is used as the primary identifier for rankings.
	// This is used to track API usage per application.
	//
	HTTPReferer *string `header:"style=simple,explode=false,name=HTTP-Referer"`
	// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
	//
	AppTitle *string `header:"style=simple,explode=false,name=X-OpenRouter-Title"`
	// Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
	//
	AppCategories *string `header:"style=simple,explode=false,name=X-OpenRouter-Categories"`
}

func (u *UpdateGuardrailGlobals) GetHTTPReferer() *string {
	if u == nil {
		return nil
	}
	return u.HTTPReferer
}

func (u *UpdateGuardrailGlobals) GetAppTitle() *string {
	if u == nil {
		return nil
	}
	return u.AppTitle
}

func (u *UpdateGuardrailGlobals) GetAppCategories() *string {
	if u == nil {
		return nil
	}
	return u.AppCategories
}

type UpdateGuardrailRequest struct {
	// The app identifier should be your app's URL and is used as the primary identifier for rankings.
	// This is used to track API usage per application.
	//
	HTTPReferer *string `header:"style=simple,explode=false,name=HTTP-Referer"`
	// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
	//
	AppTitle *string `header:"style=simple,explode=false,name=X-OpenRouter-Title"`
	// Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
	//
	AppCategories *string `header:"style=simple,explode=false,name=X-OpenRouter-Categories"`
	// The unique identifier of the guardrail to update
	ID   string                            `pathParam:"style=simple,explode=false,name=id"`
	Body components.UpdateGuardrailRequest `request:"mediaType=application/json"`
}

func (u *UpdateGuardrailRequest) GetHTTPReferer() *string {
	if u == nil {
		return nil
	}
	return u.HTTPReferer
}

func (u *UpdateGuardrailRequest) GetAppTitle() *string {
	if u == nil {
		return nil
	}
	return u.AppTitle
}

func (u *UpdateGuardrailRequest) GetAppCategories() *string {
	if u == nil {
		return nil
	}
	return u.AppCategories
}

func (u *UpdateGuardrailRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateGuardrailRequest) GetBody() components.UpdateGuardrailRequest {
	if u == nil {
		return components.UpdateGuardrailRequest{}
	}
	return u.Body
}

type UpdateGuardrailResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Guardrail updated successfully
	UpdateGuardrailResponse *components.UpdateGuardrailResponse
}

func (u UpdateGuardrailResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateGuardrailResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateGuardrailResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateGuardrailResponse) GetUpdateGuardrailResponse() *components.UpdateGuardrailResponse {
	if u == nil {
		return nil
	}
	return u.UpdateGuardrailResponse
}
