// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/models/components"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type UpdateObservabilityDestinationGlobals struct {
	// The app identifier should be your app's URL and is used as the primary identifier for rankings.
	// This is used to track API usage per application.
	//
	HTTPReferer *string `header:"style=simple,explode=false,name=HTTP-Referer"`
	// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
	//
	AppTitle *string `header:"style=simple,explode=false,name=X-OpenRouter-Title"`
	// Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
	//
	AppCategories *string `header:"style=simple,explode=false,name=X-OpenRouter-Categories"`
}

func (u *UpdateObservabilityDestinationGlobals) GetHTTPReferer() *string {
	if u == nil {
		return nil
	}
	return u.HTTPReferer
}

func (u *UpdateObservabilityDestinationGlobals) GetAppTitle() *string {
	if u == nil {
		return nil
	}
	return u.AppTitle
}

func (u *UpdateObservabilityDestinationGlobals) GetAppCategories() *string {
	if u == nil {
		return nil
	}
	return u.AppCategories
}

type UpdateObservabilityDestinationRequest struct {
	// The app identifier should be your app's URL and is used as the primary identifier for rankings.
	// This is used to track API usage per application.
	//
	HTTPReferer *string `header:"style=simple,explode=false,name=HTTP-Referer"`
	// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
	//
	AppTitle *string `header:"style=simple,explode=false,name=X-OpenRouter-Title"`
	// Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
	//
	AppCategories *string `header:"style=simple,explode=false,name=X-OpenRouter-Categories"`
	// The destination ID (UUID).
	ID   string                                           `pathParam:"style=simple,explode=false,name=id"`
	Body components.UpdateObservabilityDestinationRequest `request:"mediaType=application/json"`
}

func (u *UpdateObservabilityDestinationRequest) GetHTTPReferer() *string {
	if u == nil {
		return nil
	}
	return u.HTTPReferer
}

func (u *UpdateObservabilityDestinationRequest) GetAppTitle() *string {
	if u == nil {
		return nil
	}
	return u.AppTitle
}

func (u *UpdateObservabilityDestinationRequest) GetAppCategories() *string {
	if u == nil {
		return nil
	}
	return u.AppCategories
}

func (u *UpdateObservabilityDestinationRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateObservabilityDestinationRequest) GetBody() components.UpdateObservabilityDestinationRequest {
	if u == nil {
		return components.UpdateObservabilityDestinationRequest{}
	}
	return u.Body
}

type UpdateObservabilityDestinationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Destination updated successfully
	UpdateObservabilityDestinationResponse *components.UpdateObservabilityDestinationResponse
}

func (u UpdateObservabilityDestinationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateObservabilityDestinationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateObservabilityDestinationResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateObservabilityDestinationResponse) GetUpdateObservabilityDestinationResponse() *components.UpdateObservabilityDestinationResponse {
	if u == nil {
		return nil
	}
	return u.UpdateObservabilityDestinationResponse
}
