// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdk

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/config"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/hooks"
)

type Beta struct {
	// beta.responses endpoints
	Responses *Responses

	rootSDK          *OpenRouter
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newBeta(rootSDK *OpenRouter, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *Beta {
	return &Beta{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
		Responses:        newResponses(rootSDK, sdkConfig, hooks),
	}
}
