// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package chat

import (
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/client"
	"github.com/kenrogers/openrouter-cli/internal/flagutil"
	"github.com/kenrogers/openrouter-cli/internal/interactive"
	"github.com/kenrogers/openrouter-cli/internal/output"
	"github.com/kenrogers/openrouter-cli/internal/sdk"
	"github.com/kenrogers/openrouter-cli/internal/sdk/models/operations"
	"github.com/kenrogers/openrouter-cli/internal/usage"
	"github.com/spf13/cobra"
)

var sendCmdMeta = []flagutil.FlagMeta{
	{FlagName: "x-open-router-experimental-metadata", Shorthand: "x", FieldPath: "XOpenRouterExperimentalMetadata", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"disabled", "enabled"}, Description: "Opt-in to surface routing metadata on the response under `openrouter_metadata`. Defaults to `disabled`. (options: disabled, enabled)"},
	{FlagName: "cache-control", Shorthand: "c", FieldPath: "Body.CacheControl", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"cache_control,omitempty"`, Description: "Enable automatic prompt caching. When set at the top level, the system automatically applies cache breakpoints to the last cacheable block in the request. Currently supported for Anthropic Claude models."},
	{FlagName: "debug-param", FieldPath: "Body.Debug", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"debug,omitempty"`, Description: "Debug options for inspecting request transformations (streaming only)"},
	{FlagName: "frequency-penalty", Shorthand: "f", FieldPath: "Body.FrequencyPenalty", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"frequency_penalty,omitempty"`, Description: "Frequency penalty (-2.0 to 2.0)"},
	{FlagName: "image-config", Shorthand: "i", FieldPath: "Body.ImageConfig", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"image_config,omitempty"`, Description: "Provider-specific image configuration options. Keys and values vary by model/provider. See https://openrouter.ai/docs/guides/overview/multimodal/image-generation for more details."},
	{FlagName: "logit-bias", FieldPath: "Body.LogitBias", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"logit_bias,omitempty"`, Description: "Token logit bias adjustments"},
	{FlagName: "logprobs", FieldPath: "Body.Logprobs", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"logprobs,omitempty"`, Description: "Return log probabilities"},
	{FlagName: "max-completion-tokens", FieldPath: "Body.MaxCompletionTokens", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"max_completion_tokens,omitempty"`, Description: "Maximum tokens in completion"},
	{FlagName: "max-tokens", FieldPath: "Body.MaxTokens", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"max_tokens,omitempty"`, Description: "Maximum tokens (deprecated, use max_completion_tokens). Note: some providers enforce a minimum of 16."},
	{FlagName: "messages", FieldPath: "Body.Messages", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"messages"`, Description: "List of messages for the conversation [required]"},
	{FlagName: "metadata", FieldPath: "Body.Metadata", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"metadata,omitempty"`, Description: "Key-value pairs for additional object information (max 16 pairs, 64 char keys, 512 char values)"},
	{FlagName: "modalities", FieldPath: "Body.Modalities", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Output modalities for the response. Supported values are \"text\", \"image\", and \"audio\"."},
	{FlagName: "model", FieldPath: "Body.Model", Kind: flagutil.FlagKindString, Optional: true, Description: "Model to use for completion"},
	{FlagName: "models", FieldPath: "Body.Models", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Models to use for completion"},
	{FlagName: "parallel-tool-calls", FieldPath: "Body.ParallelToolCalls", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"parallel_tool_calls,omitempty"`, Description: "Whether to enable parallel function calling during tool use. When true, the model may generate multiple tool calls in a single response."},
	{FlagName: "plugins", FieldPath: "Body.Plugins", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"plugins,omitempty"`, Description: "Plugins you want to enable for this request, including their settings."},
	{FlagName: "presence-penalty", FieldPath: "Body.PresencePenalty", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"presence_penalty,omitempty"`, Description: "Presence penalty (-2.0 to 2.0)"},
	{FlagName: "provider", FieldPath: "Body.Provider", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"provider,omitempty"`, Description: "When multiple model providers are available, optionally indicate your routing preference."},
	{FlagName: "reasoning", FieldPath: "Body.Reasoning", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"reasoning,omitempty"`, Description: "Configuration options for reasoning models"},
	{FlagName: "response-format", FieldPath: "Body.ResponseFormat", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: true, DiscriminatorKey: "Type", Optional: true, TypeDescription: "JSON value (variants: grammar: { grammar: string, type: string }, json_object: { type: string }, json_schema: { json_schema: object, type: string }, python: { type: string }, text: { type: string })", Variants: []flagutil.UnionVariantMeta{
		{DiscriminatorValue: "grammar", FlagName: "response-format.grammar", FieldName: "ChatFormatGrammarConfig", CanExpand: true, Description: "ChatFormatGrammarConfig variant as JSON", Fields: []flagutil.FlagMeta{
			{FlagName: "response-format.grammar.grammar", FieldPath: "Grammar", Kind: flagutil.FlagKindString, Required: true, Description: "Custom grammar for text generation [required]"},
		}},
		{DiscriminatorValue: "json_object", FlagName: "response-format.json-object", FieldName: "FormatJSONObjectConfig", CanExpand: true, Description: "FormatJsonObjectConfig variant as JSON"},
		{DiscriminatorValue: "json_schema", FlagName: "response-format.json-schema", FieldName: "ChatFormatJSONSchemaConfig", CanExpand: false, Description: "ChatFormatJsonSchemaConfig variant as JSON"},
		{DiscriminatorValue: "python", FlagName: "response-format.python", FieldName: "ChatFormatPythonConfig", CanExpand: true, Description: "ChatFormatPythonConfig variant as JSON"},
		{DiscriminatorValue: "text", FlagName: "response-format.text", FieldName: "ChatFormatTextConfig", CanExpand: true, Description: "ChatFormatTextConfig variant as JSON"},
	}}},
	{FlagName: "seed", FieldPath: "Body.Seed", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"seed,omitempty"`, Description: "Random seed for deterministic outputs"},
	{FlagName: "service-tier", FieldPath: "Body.ServiceTier", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"service_tier,omitempty"`, Description: "The service tier to use for processing this request. (options: auto, default, flex, priority, scale)"},
	{FlagName: "session-id", FieldPath: "Body.SessionID", Kind: flagutil.FlagKindString, Optional: true, Description: "A unique identifier for grouping related requests (e.g., a conversation or agent workflow) for observability. If provided in both the request body and the x-session-id header, the body value takes precedence. Maximum of 256 characters."},
	{FlagName: "stop", FieldPath: "Body.Stop", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: string | array of string | any)"}},
	{FlagName: "stop-server-tools-when", FieldPath: "Body.StopServerToolsWhen", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"stop_server_tools_when,omitempty"`, Description: "Stop conditions for the server-tool agent loop. Any condition firing halts the loop (OR logic). When set, this overrides `max_tool_calls`."},
	{FlagName: "stream", FieldPath: "Body.Stream", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, Description: "Enable streaming response"},
	{FlagName: "stream-options", FieldPath: "Body.StreamOptions", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"stream_options,omitempty"`, Description: "Streaming configuration options"},
	{FlagName: "temperature", FieldPath: "Body.Temperature", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"temperature,omitempty"`, Description: "Sampling temperature (0-2)"},
	{FlagName: "tool-choice", FieldPath: "Body.ToolChoice", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: ChatToolChoice_1 | ChatToolChoice_2 | ChatToolChoice_3 | { function: object, type: string } | { type: string })"}},
	{FlagName: "tools", FieldPath: "Body.Tools", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"tools,omitempty"`, Description: "Available tools for function calling"},
	{FlagName: "top-logprobs", FieldPath: "Body.TopLogprobs", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"top_logprobs,omitempty"`, Description: "Number of top log probabilities to return (0-20)"},
	{FlagName: "top-p", FieldPath: "Body.TopP", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"top_p,omitempty"`, Description: "Nucleus sampling parameter (0-1)"},
	{FlagName: "trace", FieldPath: "Body.Trace", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"trace,omitempty"`, Description: "Metadata for observability and tracing. Known keys (trace_id, trace_name, span_name, generation_name, parent_span_id) have special handling. Additional keys are passed through as custom metadata to configured broadcast destinations."},
	{FlagName: "user", Shorthand: "u", FieldPath: "Body.User", Kind: flagutil.FlagKindString, Optional: true, Description: "Unique user identifier"},
}

// initSendCmd initializes the send command.
func initSendCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "send",
		Short:   "Create a chat completion",
		Long:    "Sends a request for a model response for the given chat conversation. Supports both streaming and non-streaming modes.",
		Example: "  openrouter chat send --messages '[{\"content\":\"You are a helpful assistant.\",\"role\":\"system\"},{\"content\":\"What is the capital of France?\",\"role\":\"user\"}]'",
		RunE:    runSendCmd,
	}
	flagutil.RegisterFlags(cmd, sendCmdMeta)
	if err := flagutil.ValidateMeta[operations.SendChatCompletionRequestRequest](sendCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for send: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runSendCmd executes the send command.
func runSendCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, sendCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, sendCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.SendChatCompletionRequestRequest](cmd, sendCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerName(cmd, sdk.ServerList); err != nil {
		return err
	}
	// Streaming response — iterate events and output incrementally.
	// Skip streaming iteration in dry-run mode (synthetic response has no stream).
	if !client.IsDryRun(cmd) {
		res, err := s.Chat.Send(cmd.Context(), *req, sdkOpts...)
		if err != nil {
			return output.Error(cmd, err)
		}
		return output.StreamResult(cmd, res, "ChatStreamingResponse")
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Chat.Send(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
