// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/kenrogers/openrouter-cli/internal/sdk/models/components"
)

// BadGatewayResponse - Bad Gateway - Provider/upstream API failure
type BadGatewayResponse struct {
	// Error data for BadGatewayResponse
	Error_             components.BadGatewayResponseErrorData `json:"error"`
	OpenrouterMetadata map[string]any                         `json:"openrouter_metadata,omitzero"`
	UserID             *string                                `json:"user_id,omitzero"`
}

var _ error = &BadGatewayResponse{}

func (e *BadGatewayResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
