// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/kenrogers/openrouter-cli/internal/sdk/models/components"
)

// ConflictResponse - Conflict - Resource conflict or concurrent modification
type ConflictResponse struct {
	// Error data for ConflictResponse
	Error_             components.ConflictResponseErrorData `json:"error"`
	OpenrouterMetadata map[string]any                       `json:"openrouter_metadata,omitzero"`
	UserID             *string                              `json:"user_id,omitzero"`
}

var _ error = &ConflictResponse{}

func (e *ConflictResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
