// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/kenrogers/openrouter-cli/internal/sdk/models/components"
)

// ForbiddenResponse - Forbidden - Authentication successful but insufficient permissions
type ForbiddenResponse struct {
	// Error data for ForbiddenResponse
	Error_             components.ForbiddenResponseErrorData `json:"error"`
	OpenrouterMetadata map[string]any                        `json:"openrouter_metadata,omitzero"`
	UserID             *string                               `json:"user_id,omitzero"`
}

var _ error = &ForbiddenResponse{}

func (e *ForbiddenResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
