// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/kenrogers/openrouter-cli/internal/sdk/models/components"
)

// NotFoundResponse - Not Found - Resource does not exist
type NotFoundResponse struct {
	// Error data for NotFoundResponse
	Error_             components.NotFoundResponseErrorData `json:"error"`
	OpenrouterMetadata map[string]any                       `json:"openrouter_metadata,omitzero"`
	UserID             *string                              `json:"user_id,omitzero"`
}

var _ error = &NotFoundResponse{}

func (e *NotFoundResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
