// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package workspaces

import (
	"github.com/kenrogers/openrouter-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitWorkspacesRoot(parent *cobra.Command) error {
	var WorkspacesCmd = &cobra.Command{
		Use:   "workspaces",
		Short: "Workspaces endpoints",
		Long:  "Workspaces endpoints",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initListCmd(WorkspacesCmd); err != nil {
		return err
	}

	if err := initCreateCmd(WorkspacesCmd); err != nil {
		return err
	}

	if err := initDeleteCmd(WorkspacesCmd); err != nil {
		return err
	}

	if err := initGetCmd(WorkspacesCmd); err != nil {
		return err
	}

	if err := initUpdateCmd(WorkspacesCmd); err != nil {
		return err
	}

	if err := initBulkAddMembersCmd(WorkspacesCmd); err != nil {
		return err
	}

	if err := initBulkRemoveMembersCmd(WorkspacesCmd); err != nil {
		return err
	}

	parent.AddCommand(WorkspacesCmd)
	return nil
}
