// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package observability

import (
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/client"
	"github.com/kenrogers/openrouter-cli/internal/flagutil"
	"github.com/kenrogers/openrouter-cli/internal/interactive"
	"github.com/kenrogers/openrouter-cli/internal/output"
	"github.com/kenrogers/openrouter-cli/internal/sdk"
	"github.com/kenrogers/openrouter-cli/internal/sdk/models/operations"
	"github.com/kenrogers/openrouter-cli/internal/usage"
	"github.com/spf13/cobra"
)

var createCmdMeta = []flagutil.FlagMeta{
	{FlagName: "api-key-hashes", Shorthand: "a", FieldPath: "Body.APIKeyHashes", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"api_key_hashes,omitempty"`, Description: "Optional allowlist of OpenRouter API key hashes whose traffic is forwarded. `null` or omitted means all keys. Must contain at least one hash if provided."},
	{FlagName: "config-param", Shorthand: "c", FieldPath: "Body.Config", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"config"`, Description: "Provider-specific configuration. The shape depends on `type` and is validated server-side. [required]"},
	{FlagName: "enabled", Shorthand: "e", FieldPath: "Body.Enabled", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, DefaultBool: true, Description: "Whether this destination should be enabled immediately."},
	{FlagName: "filter-rules", Shorthand: "f", FieldPath: "Body.FilterRules", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"filter_rules,omitempty"`, Description: "Optional structured filter rules controlling which events are forwarded."},
	{FlagName: "name", Shorthand: "n", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Required: true, Description: "Human-readable name for the destination. [required]"},
	{FlagName: "privacy-mode", Shorthand: "p", FieldPath: "Body.PrivacyMode", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, Description: "When true, request/response bodies are not forwarded — only metadata."},
	{FlagName: "sampling-rate", Shorthand: "s", FieldPath: "Body.SamplingRate", Kind: flagutil.FlagKindFloat64, Optional: true, Description: "Sampling rate between 0 and 1 (1 = 100%)."},
	{FlagName: "type", Shorthand: "t", FieldPath: "Body.Type", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"arize", "braintrust", "clickhouse", "datadog", "grafana", "langfuse", "langsmith", "newrelic", "opik", "otel-collector", "posthog", "ramp", "s3", "sentry", "snowflake", "weave", "webhook"}, Description: "The destination type. Only stable destination types are accepted. (options: arize, braintrust, clickhouse, datadog, grafana, langfuse, langsmith, newrelic, opik, otel-collector, posthog, ramp, s3, sentry, snowflake, weave, webhook) [required]"},
	{FlagName: "workspace-id", Shorthand: "w", FieldPath: "Body.WorkspaceID", Kind: flagutil.FlagKindString, Optional: true, Description: "Optional workspace ID. Defaults to the authenticated entity's default workspace."},
}

// initCreateCmd initializes the create command.
func initCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create an observability destination",
		Long:    "Create a new observability destination. A maximum of 5 destinations per type is allowed. Defaults to the authenticated entity's default workspace; use the `workspace_id` body field to scope to a different workspace. [Management key](/docs/guides/overview/auth/management-api-keys) required.",
		Example: "  openrouter observability create --config-param '{\"baseUrl\":\"https://us.cloud.langfuse.com\",\"publicKey\":\"pk-l...EfGh\",\"secretKey\":\"sk-l...AbCd\"}' --name Production Langfuse --type langfuse",
		RunE:    runCreateCmd,
	}
	flagutil.RegisterFlags(cmd, createCmdMeta)
	if err := flagutil.ValidateMeta[operations.CreateObservabilityDestinationRequest](createCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateCmd executes the create command.
func runCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.CreateObservabilityDestinationRequest](cmd, createCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerName(cmd, sdk.ServerList); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Observability.Create(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
