// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/cli/analytics"
	"github.com/kenrogers/openrouter-cli/internal/cli/apikeys"
	"github.com/kenrogers/openrouter-cli/internal/cli/beta"
	"github.com/kenrogers/openrouter-cli/internal/cli/byok"
	"github.com/kenrogers/openrouter-cli/internal/cli/chat"
	"github.com/kenrogers/openrouter-cli/internal/cli/credits"
	"github.com/kenrogers/openrouter-cli/internal/cli/embeddings"
	"github.com/kenrogers/openrouter-cli/internal/cli/endpoints"
	"github.com/kenrogers/openrouter-cli/internal/cli/generations"
	"github.com/kenrogers/openrouter-cli/internal/cli/guardrails"
	"github.com/kenrogers/openrouter-cli/internal/cli/models"
	"github.com/kenrogers/openrouter-cli/internal/cli/oauth"
	"github.com/kenrogers/openrouter-cli/internal/cli/observability"
	"github.com/kenrogers/openrouter-cli/internal/cli/organization"
	"github.com/kenrogers/openrouter-cli/internal/cli/presets"
	"github.com/kenrogers/openrouter-cli/internal/cli/providers"
	"github.com/kenrogers/openrouter-cli/internal/cli/rerank"
	"github.com/kenrogers/openrouter-cli/internal/cli/stt"
	"github.com/kenrogers/openrouter-cli/internal/cli/tts"
	"github.com/kenrogers/openrouter-cli/internal/cli/videogeneration"
	"github.com/kenrogers/openrouter-cli/internal/cli/workspaces"
	"github.com/kenrogers/openrouter-cli/internal/config"
	"github.com/kenrogers/openrouter-cli/internal/explorer"
	"github.com/kenrogers/openrouter-cli/internal/output"
	"github.com/kenrogers/openrouter-cli/internal/usage"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	"golang.org/x/term"
	"os"
	"strings"
)

var rootCmd *cobra.Command

// NewRootCommand creates and returns the root command.
// This is exported for testing purposes to allow in-process command execution.
func NewRootCommand() (*cobra.Command, error) {
	cobra.AddTemplateFunc("groupedFlagUsages", groupedFlagUsages)
	cobra.AddTemplateFunc("groupedGlobalFlagUsages", groupedGlobalFlagUsages)
	rootCmd := &cobra.Command{
		Use:           "openrouter",
		Short:         "OpenRouter API: OpenAI-compatible API with additional OpenRouter features",
		Long:          "OpenRouter API: OpenAI-compatible API with additional OpenRouter features",
		SilenceUsage:  true,
		SilenceErrors: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return nil
			}
			if err := config.Init("openrouter", "OPENROUTER"); err != nil {
				return err
			}
			output.InitAgentMode(cmd)
			return nil
		},
	}
	if err := analytics.InitAnalyticsRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init analytics: %w", err)
	}
	if err := tts.InitTTSRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init tts: %w", err)
	}
	if err := stt.InitSTTRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init stt: %w", err)
	}
	if err := oauth.InitOAuthRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init O-auth: %w", err)
	}
	if err := byok.InitBYOKRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init byok: %w", err)
	}
	if err := chat.InitChatRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init chat: %w", err)
	}
	if err := credits.InitCreditsRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init credits: %w", err)
	}
	if err := embeddings.InitEmbeddingsRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init embeddings: %w", err)
	}
	if err := endpoints.InitEndpointsRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init endpoints: %w", err)
	}
	if err := generations.InitGenerationsRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init generations: %w", err)
	}
	if err := guardrails.InitGuardrailsRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init guardrails: %w", err)
	}
	if err := apikeys.InitAPIKeysRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init API-keys: %w", err)
	}
	if err := models.InitModelsRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init models: %w", err)
	}
	if err := observability.InitObservabilityRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init observability: %w", err)
	}
	if err := organization.InitOrganizationRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init organization: %w", err)
	}
	if err := presets.InitPresetsRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init presets: %w", err)
	}
	if err := providers.InitProvidersRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init providers: %w", err)
	}
	if err := rerank.InitRerankRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init rerank: %w", err)
	}
	if err := beta.InitBetaRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init beta: %w", err)
	}
	if err := videogeneration.InitVideoGenerationRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init video-generation: %w", err)
	}
	if err := workspaces.InitWorkspacesRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init workspaces: %w", err)
	}
	if err := initConfigureCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init configure: %w", err)
	}
	if err := initWhoamiCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init whoami: %w", err)
	}
	if err := initVersionCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init version: %w", err)
	}
	if err := initAuthCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init auth: %w", err)
	}
	initOpenRouterExperienceCommands(rootCmd)
	initExploreCmd(rootCmd)

	// Global output format flag
	rootCmd.PersistentFlags().StringP("output-format", "o", "pretty", "Specify the output format. Options: pretty, json, yaml, table, toon.")
	rootCmd.PersistentFlags().Bool("json", false, "Shortcut for --output-format json")

	// Color control flag
	rootCmd.PersistentFlags().String("color", "auto", "Control colored output: auto (color when output is a TTY), always, or never. Respects NO_COLOR and FORCE_COLOR env vars.")

	// jq filtering flag
	rootCmd.PersistentFlags().StringP("jq", "q", "", "Filter and transform output using a jq expression (e.g., '.name', '.items[] | .id')")

	// Global server URL flag
	rootCmd.PersistentFlags().String("server-url", "", "Override the default server URL")

	// Server selection flag (by index or name)
	rootCmd.PersistentFlags().String("server", "", "Select a server by index (for indexed servers) or name (for named servers)")

	// Custom header flag (repeatable: --header "Key: Value" --header "Key2: Value2")
	rootCmd.PersistentFlags().StringArrayP("header", "H", nil, "Set a custom HTTP request header (format: \"Key: Value\"). Can be specified multiple times.")

	// Response headers flag
	rootCmd.PersistentFlags().Bool("include-headers", false, "Include HTTP response headers in the output")

	// Request timeout (always available)
	rootCmd.PersistentFlags().String("timeout", "", "HTTP request timeout (e.g., 30s, 5m, 100ms)")
	// Interactive mode control
	rootCmd.PersistentFlags().Bool("no-interactive", false, "Disable all interactive features (auto-prompting, explorer auto-launch, TUI forms)")

	// Diagnostics flags
	rootCmd.PersistentFlags().Bool("usage", false, "Print the CLI Usage schema in KDL format")
	rootCmd.PersistentFlags().Bool("dry-run", false, "Preview the request that would be sent without executing it (output to stderr)")
	rootCmd.PersistentFlags().BoolP("debug", "d", false, "Log request and response diagnostics to stderr")

	// Agent mode — optimized output for AI coding agent consumption.
	// Automatically enabled when running inside a known AI agent (Claude Code, Cursor, etc.).
	// Use this flag to explicitly enable or disable (--agent-mode=false) the behavior.
	rootCmd.PersistentFlags().Bool("agent-mode", false,
		"Enable structured errors and default TOON output for AI coding agents. "+
			"Automatically enabled when a known agent environment is detected (CLAUDE_CODE, CURSOR_AGENT, etc.). "+
			"Use --agent-mode=false to disable.")
	// Retry control flags
	// Defaults: exponential backoff, 500ms initial / 10s max interval, 1.5x exponent, 30s max elapsed time.
	rootCmd.PersistentFlags().Bool("no-retries", false, "Disable automatic retries (default: retries enabled with exponential backoff)")
	rootCmd.PersistentFlags().String("retry-max-elapsed-time", "", "Maximum total time for retries (e.g., 30s, 5m). Default: 30s")
	rootCmd.PersistentFlags().Bool("retry-connection-errors", false, "Retry on connection errors (EOF, reset, etc.)")
	rootCmd.PersistentFlags().String("retry-config", "", `Full retry config as JSON. Schema: {"strategy":"backoff","backoff":{"initialInterval":500,"maxInterval":10000,"exponent":1.5,"maxElapsedTime":30000},"retryConnectionErrors":false}. Times are in milliseconds.`)

	// Global security flags
	rootCmd.PersistentFlags().String("api-key", "", "API key as bearer token in Authorization header")
	_ = rootCmd.PersistentFlags().SetAnnotation("api-key", "speakeasy:group", []string{"Authentication"})
	// Global parameter flags
	rootCmd.PersistentFlags().String("http-referer", "", "The app identifier should be your app's URL and is used as the primary identifier for rankings (env: OPENROUTER_HTTP_REFERER)")
	_ = rootCmd.PersistentFlags().SetAnnotation("http-referer", "speakeasy:group", []string{"API Parameters"})
	rootCmd.PersistentFlags().String("app-title", "", "The app display name allows you to customize how your app appears in OpenRouter's dashboard (env: OPENROUTER_APP_TITLE)")
	_ = rootCmd.PersistentFlags().SetAnnotation("app-title", "speakeasy:group", []string{"API Parameters"})
	rootCmd.PersistentFlags().String("app-categories", "", "Comma-separated list of app categories (e (env: OPENROUTER_APP_CATEGORIES)")
	_ = rootCmd.PersistentFlags().SetAnnotation("app-categories", "speakeasy:group", []string{"API Parameters"})

	// Annotate persistent flags for grouped help display
	for _, ga := range []struct{ flag, group string }{
		{"output-format", "Output"},
		{"json", "Output"},
		{"color", "Output"},
		{"jq", "Output"},
		{"include-headers", "Output"},
		{"no-interactive", "Output"},
		{"server-url", "Server"},
		{"server", "Server"},
		{"header", "Network"},
		{"timeout", "Network"},
		{"usage", "Diagnostics"},
		{"dry-run", "Diagnostics"},
		{"debug", "Diagnostics"},
		{"agent-mode", "Diagnostics"},
	} {
		_ = rootCmd.PersistentFlags().SetAnnotation(ga.flag, "speakeasy:group", []string{ga.group})
	}
	for _, flag := range []string{"no-retries", "retry-max-elapsed-time", "retry-connection-errors", "retry-config"} {
		_ = rootCmd.PersistentFlags().SetAnnotation(flag, "speakeasy:group", []string{"Network"})
	}

	rootCmd.SetUsageTemplate(groupedUsageTemplate())

	return rootCmd, nil
}

func initOpenRouterExperienceCommands(parent *cobra.Command) {
	parent.AddCommand(newOpenRouterAskCommand())
	parent.AddCommand(newOpenRouterImageCommand())
	parent.AddCommand(newOpenRouterVideoCommand())
	parent.AddCommand(newOpenRouterAudioCommand())
	parent.AddCommand(newOpenRouterEmbedCommand())
	enhanceOpenRouterModelsCommand(parent)
	enhanceOpenRouterRerankCommand(parent)
}

func Execute() error {
	var err error
	rootCmd, err = NewRootCommand()
	if err != nil {
		return err
	}

	// Early agent mode detection from env vars (flag parsing hasn't happened yet).
	// This prevents the explorer TUI from launching when an AI agent is driving the CLI.
	output.InitAgentMode(rootCmd)

	// Auto-launch explorer when invoked with no subcommand from a TTY
	if shouldAutoExplore() {
		return runExplorer(rootCmd)
	}

	return rootCmd.Execute()
}

// shouldAutoExplore returns true when the CLI is invoked with no subcommand
// from an interactive terminal and agent mode is not active.
func shouldAutoExplore() bool {
	if len(os.Args) > 1 {
		return false
	}
	if !term.IsTerminal(int(os.Stdin.Fd())) || !term.IsTerminal(int(os.Stdout.Fd())) {
		return false
	}
	// Agent mode: agents run in PTY terminals but should never get a TUI.
	if output.IsAgentMode() {
		return false
	}
	return true
}

// initExploreCmd registers the "explore" subcommand.
func initExploreCmd(parent *cobra.Command) {
	parent.AddCommand(&cobra.Command{
		Use:   "explore",
		Short: "Interactively browse and run commands",
		Long:  "Launch an interactive command explorer to browse available commands, view their descriptions and flags, and execute them.",
		RunE: func(cmd *cobra.Command, args []string) error {
			// Agent mode: print help instead of launching TUI.
			if output.IsAgentMode() {
				return cmd.Root().Help()
			}
			return runExplorer(cmd.Root())
		},
	})
}

// runExplorer launches the explorer TUI and handles command execution handoff.
func runExplorer(root *cobra.Command) error {
	selectedArgs, err := explorer.Run(root, Version)
	if err != nil {
		return err
	}
	if selectedArgs == nil {
		return nil // user quit
	}
	// Build a fresh command tree and execute the selected command
	freshRoot, err := NewRootCommand()
	if err != nil {
		return err
	}
	freshRoot.SetArgs(selectedArgs)
	return freshRoot.Execute()
}

// globalFlagGroupOrder defines the display order for flag groups in help output.
// Groups without any flags are skipped automatically.
var globalFlagGroupOrder = []string{"Output", "Authentication", "API Parameters", "Server", "Network", "Diagnostics"}

// groupedFlagUsages splits local flags into sections for help display.
// For operation commands (flags with "speakeasy:required"): Required/Optional sections.
// For the root command (flags with "speakeasy:group"): category-based sections.
// Falls back to a flat "Flags:" listing otherwise.
func groupedFlagUsages(flags *pflag.FlagSet) string {
	required := pflag.NewFlagSet("required", pflag.ContinueOnError)
	optional := pflag.NewFlagSet("optional", pflag.ContinueOnError)
	hasGroupAnnotation := false

	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		if ann, ok := f.Annotations["speakeasy:required"]; ok && len(ann) > 0 && ann[0] == "true" {
			required.AddFlag(f)
		} else {
			optional.AddFlag(f)
		}
		if _, ok := f.Annotations["speakeasy:group"]; ok {
			hasGroupAnnotation = true
		}
	})

	// Operation commands: Required/Optional sections, with sub-groups when present
	if required.HasFlags() {
		var buf strings.Builder
		buf.WriteString("Required Flags:\n")
		buf.WriteString(required.FlagUsages())
		if optional.HasFlags() {
			if hasGroupAnnotation {
				buf.WriteString("\n")
				buf.WriteString(renderOperationGroups(optional))
			} else {
				buf.WriteString("\nOptional Flags:\n")
				buf.WriteString(optional.FlagUsages())
			}
		}
		return strings.TrimRight(buf.String(), "\n")
	}

	// Grouped flags (root command or operation with only optional grouped flags)
	if hasGroupAnnotation {
		// Check if any groups are in the global order (root-level groups like Output, Server)
		hasGlobalGroup := false
		flags.VisitAll(func(f *pflag.Flag) {
			if ann, ok := f.Annotations["speakeasy:group"]; ok && len(ann) > 0 {
				for _, g := range globalFlagGroupOrder {
					if ann[0] == g {
						hasGlobalGroup = true
					}
				}
			}
		})
		if hasGlobalGroup {
			return renderGroupedFlags(flags, "Flags")
		}
		// Operation-level groups (e.g., Address, Profile)
		return strings.TrimRight(renderOperationGroups(flags), "\n")
	}

	// Fallback: flat listing
	return "Flags:\n" + strings.TrimRight(flags.FlagUsages(), "\n")
}

// groupedGlobalFlagUsages splits inherited (global) flags into category sections
// based on the "speakeasy:group" annotation. Falls back to flat "Global Flags:".
func groupedGlobalFlagUsages(flags *pflag.FlagSet) string {
	hasGroupAnnotation := false
	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		if _, ok := f.Annotations["speakeasy:group"]; ok {
			hasGroupAnnotation = true
		}
	})

	if hasGroupAnnotation {
		return renderGroupedFlags(flags, "Global Flags")
	}

	return "Global Flags:\n" + strings.TrimRight(flags.FlagUsages(), "\n")
}

// renderOperationGroups renders optional operation flags grouped by their
// "speakeasy:group" annotation. Groups are shown alphabetically, with
// ungrouped flags under a generic "Optional Flags" header.
func renderOperationGroups(flags *pflag.FlagSet) string {
	groups := make(map[string]*pflag.FlagSet)
	groupOrder := []string{}
	ungrouped := pflag.NewFlagSet("ungrouped", pflag.ContinueOnError)

	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		if ann, ok := f.Annotations["speakeasy:group"]; ok && len(ann) > 0 {
			name := ann[0]
			if _, exists := groups[name]; !exists {
				groups[name] = pflag.NewFlagSet(name, pflag.ContinueOnError)
				groupOrder = append(groupOrder, name)
			}
			groups[name].AddFlag(f)
		} else {
			ungrouped.AddFlag(f)
		}
	})

	var buf strings.Builder

	// Show ungrouped optional flags first
	if ungrouped.HasFlags() {
		buf.WriteString("Optional Flags:\n")
		buf.WriteString(ungrouped.FlagUsages())
	}

	// Then show each group
	for _, name := range groupOrder {
		fs := groups[name]
		if !fs.HasFlags() {
			continue
		}
		buf.WriteString("\n" + name + " Flags:\n")
		buf.WriteString(fs.FlagUsages())
	}

	return buf.String()
}

// renderGroupedFlags groups flags by their "speakeasy:group" annotation,
// rendering each group as a separate section with a header. Flags without
// a group annotation are collected under the fallbackHeader section.
func renderGroupedFlags(flags *pflag.FlagSet, fallbackHeader string) string {
	groups := make(map[string]*pflag.FlagSet)
	for _, g := range globalFlagGroupOrder {
		groups[g] = pflag.NewFlagSet(g, pflag.ContinueOnError)
	}
	ungrouped := pflag.NewFlagSet("ungrouped", pflag.ContinueOnError)

	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		if ann, ok := f.Annotations["speakeasy:group"]; ok && len(ann) > 0 {
			if fs, exists := groups[ann[0]]; exists {
				fs.AddFlag(f)
				return
			}
		}
		ungrouped.AddFlag(f)
	})

	var buf strings.Builder
	first := true
	for _, name := range globalFlagGroupOrder {
		fs := groups[name]
		if !fs.HasFlags() {
			continue
		}
		if !first {
			buf.WriteString("\n")
		}
		buf.WriteString(name + ":\n")
		buf.WriteString(fs.FlagUsages())
		first = false
	}
	if ungrouped.HasFlags() {
		if !first {
			buf.WriteString("\n")
		}
		buf.WriteString(fallbackHeader + ":\n")
		buf.WriteString(ungrouped.FlagUsages())
	}
	return strings.TrimRight(buf.String(), "\n")
}

// groupedUsageTemplate returns Cobra's default usage template with the local
// and global Flags sections replaced to use grouped rendering.
// Built at runtime via strings.Replace to avoid template delimiter conflicts
// with the code generator's own template engine.
func groupedUsageTemplate() string {
	ob := string([]byte{'{', '{'})
	cb := string([]byte{'}', '}'})
	defaultTmpl := (&cobra.Command{}).UsageTemplate()

	// Replace local flags section
	oldLocal := "Flags:\n" + ob + ".LocalFlags.FlagUsages | trimTrailingWhitespaces" + cb
	replLocal := ob + "groupedFlagUsages .LocalFlags | trimTrailingWhitespaces" + cb
	result := strings.Replace(defaultTmpl, oldLocal, replLocal, 1)

	// Replace global flags section
	oldGlobal := "Global Flags:\n" + ob + ".InheritedFlags.FlagUsages | trimTrailingWhitespaces" + cb
	replGlobal := ob + "groupedGlobalFlagUsages .InheritedFlags | trimTrailingWhitespaces" + cb
	result = strings.Replace(result, oldGlobal, replGlobal, 1)

	return result
}
