// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/config"
	"github.com/kenrogers/openrouter-cli/internal/output"
	"github.com/kenrogers/openrouter-cli/internal/usage"
	"github.com/spf13/cobra"
)

// initWhoamiCmd initializes the whoami command.
func initWhoamiCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:   "whoami",
		Short: "Display current authentication and global parameter configuration",
		Long: `Display the currently configured settings and their sources.

Sources are shown as:
  [flag]    - Set via command line flag
  [env]     - Set via environment variable (OPENROUTER_*)
  [keyring] - Set via OS keychain (stored by configure command)
  [unset]   - Not configured

Credential values are masked for security.`,
		RunE: runWhoamiCmd,
	}
	parent.AddCommand(cmd)
	return nil
}

// runWhoamiCmd executes the whoami command.
func runWhoamiCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	apiKey, apiKeySource := config.ResolveSecurityCredential(cmd, "api-key")
	httpReferer, httpRefererSource := config.ResolveCredential(cmd, "http-referer")
	appTitle, appTitleSource := config.ResolveCredential(cmd, "app-title")
	appCategories, appCategoriesSource := config.ResolveCredential(cmd, "app-categories")

	if output.WantsRawJSON(cmd) {
		return output.Result(cmd, map[string]any{
			"config_file":        config.GetConfigPath(),
			"environment_prefix": "OPENROUTER_",
			"credentials": map[string]any{
				"api_key": map[string]string{
					"source": apiKeySource,
					"masked": maskSecret(apiKey),
				},
			},
			"global_parameters": map[string]any{
				"http_referer":   map[string]string{"source": httpRefererSource, "value": httpReferer},
				"app_title":      map[string]string{"source": appTitleSource, "value": appTitle},
				"app_categories": map[string]string{"source": appCategoriesSource, "value": appCategories},
			},
		})
	}

	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "Configuration")
	fmt.Fprintln(out, "=============")
	fmt.Fprintln(out)
	fmt.Fprintf(out, "Config file: %s\n", config.GetConfigPath())
	fmt.Fprintf(out, "Environment prefix: OPENROUTER_\n")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "Credentials:")

	// API key as bearer token in Authorization header
	{
		fmt.Fprintf(out, "  --%-25s [%-7s] %s\n", "api-key", apiKeySource, maskSecret(apiKey))
	}

	fmt.Fprintln(out)
	fmt.Fprintln(out, "Global Parameters:")

	// The app identifier should be your app's URL and is used as the primary identifier for rankings
	{
		fmt.Fprintf(out, "  --%-25s [%-7s] %s\n", "http-referer", httpRefererSource, httpReferer)
	}

	// The app display name allows you to customize how your app appears in OpenRouter's dashboard
	{
		fmt.Fprintf(out, "  --%-25s [%-7s] %s\n", "app-title", appTitleSource, appTitle)
	}

	// Comma-separated list of app categories (e
	{
		fmt.Fprintf(out, "  --%-25s [%-7s] %s\n", "app-categories", appCategoriesSource, appCategories)
	}

	return nil
}
