// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package organization

import (
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/client"
	"github.com/kenrogers/openrouter-cli/internal/flagutil"
	"github.com/kenrogers/openrouter-cli/internal/interactive"
	"github.com/kenrogers/openrouter-cli/internal/output"
	"github.com/kenrogers/openrouter-cli/internal/sdk"
	"github.com/kenrogers/openrouter-cli/internal/sdk/models/operations"
	"github.com/kenrogers/openrouter-cli/internal/usage"
	"github.com/spf13/cobra"
)

var listMembersCmdMeta = []flagutil.FlagMeta{
	{FlagName: "offset", FieldPath: "Offset", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=offset"`, Description: "Number of records to skip for pagination"},
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, Description: "Maximum number of records to return (max 100)"},
}

// initListMembersCmd initializes the list-members command.
func initListMembersCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list-members",
		Short:   "List organization members",
		Long:    "List all members of the organization associated with the authenticated management key. [Management key](/docs/guides/overview/auth/management-api-keys) required.",
		Example: "  openrouter organization list-members",
		RunE:    runListMembersCmd,
		Aliases: []string{"lm"},
	}
	flagutil.RegisterFlags(cmd, listMembersCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListOrganizationMembersRequest](listMembersCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-members: %w", err)
	}
	cmd.Flags().BoolP("all", "a", false, "Automatically paginate and fetch all results (streams NDJSON for JSON output)")
	cmd.Flags().Int("max-pages", 0, "Maximum number of pages to fetch when using --all (0 = no limit)")
	parent.AddCommand(cmd)
	return nil
}

// runListMembersCmd executes the list-members command.
func runListMembersCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listMembersCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listMembersCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListOrganizationMembersRequest](cmd, listMembersCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerName(cmd, sdk.ServerList); err != nil {
		return err
	}
	if allPages, _ := flagutil.GetBoolFlag(cmd, "all"); allPages && !client.IsDryRun(cmd) {
		maxPages, _ := flagutil.GetIntFlag(cmd, "max-pages")
		res, err := s.Organization.ListMembers(cmd.Context(), req, sdkOpts...)
		if err != nil {
			return output.Error(cmd, err)
		}
		return output.PaginatedResult(cmd, res, "Object", "Data", maxPages)
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Organization.ListMembers(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	if output.HasMorePages(res) {
		fmt.Fprintln(cmd.ErrOrStderr(), "Hint: more pages available. Use --all to fetch all results, or use --offset/--limit for manual pagination.")
	}
	return nil
}
