// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package stt

import (
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/client"
	"github.com/kenrogers/openrouter-cli/internal/flagutil"
	"github.com/kenrogers/openrouter-cli/internal/interactive"
	"github.com/kenrogers/openrouter-cli/internal/output"
	"github.com/kenrogers/openrouter-cli/internal/sdk"
	"github.com/kenrogers/openrouter-cli/internal/sdk/models/operations"
	"github.com/kenrogers/openrouter-cli/internal/usage"
	"github.com/spf13/cobra"
)

var createTranscriptionCmdMeta = []flagutil.FlagMeta{
	{FlagName: "input-audio", Shorthand: "i", FieldPath: "Body.InputAudio", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"input_audio"`, Description: "Base64-encoded audio to transcribe [required]"},
	{FlagName: "language", Shorthand: "l", FieldPath: "Body.Language", Kind: flagutil.FlagKindString, Optional: true, Description: "ISO-639-1 language code (e.g., \"en\", \"ja\"). Auto-detected if omitted."},
	{FlagName: "model", Shorthand: "m", FieldPath: "Body.Model", Kind: flagutil.FlagKindString, Required: true, Description: "STT model identifier [required]"},
	{FlagName: "provider", Shorthand: "p", FieldPath: "Body.Provider", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"provider,omitempty"`, Description: "Provider-specific passthrough configuration"},
	{FlagName: "temperature", Shorthand: "t", FieldPath: "Body.Temperature", Kind: flagutil.FlagKindFloat64, Optional: true, Description: "Sampling temperature for transcription"},
}

// initCreateTranscriptionCmd initializes the create-transcription command.
func initCreateTranscriptionCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create-transcription",
		Short:   "Create transcription",
		Long:    "Transcribes audio into text. Accepts base64-encoded audio input and returns the transcribed text.",
		Example: "  openrouter stt create-transcription --input-audio '{\"data\":\"UklGRiQA...\",\"format\":\"wav\"}' --model openai/whisper-large-v3",
		RunE:    runCreateTranscriptionCmd,
		Aliases: []string{"ct"},
	}
	flagutil.RegisterFlags(cmd, createTranscriptionCmdMeta)
	if err := flagutil.ValidateMeta[operations.CreateAudioTranscriptionsRequest](createTranscriptionCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create-transcription: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateTranscriptionCmd executes the create-transcription command.
func runCreateTranscriptionCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createTranscriptionCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createTranscriptionCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.CreateAudioTranscriptionsRequest](cmd, createTranscriptionCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerName(cmd, sdk.ServerList); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Stt.CreateTranscription(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
