// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package guardrails

import (
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/client"
	"github.com/kenrogers/openrouter-cli/internal/flagutil"
	"github.com/kenrogers/openrouter-cli/internal/interactive"
	"github.com/kenrogers/openrouter-cli/internal/output"
	"github.com/kenrogers/openrouter-cli/internal/sdk"
	"github.com/kenrogers/openrouter-cli/internal/sdk/models/operations"
	"github.com/kenrogers/openrouter-cli/internal/usage"
	"github.com/spf13/cobra"
)

var updateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The unique identifier of the guardrail to update [required]"},
	{FlagName: "allowed-models", FieldPath: "Body.AllowedModels", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"allowed_models,omitempty"`, Description: "Array of model identifiers (slug or canonical_slug accepted)"},
	{FlagName: "allowed-providers", FieldPath: "Body.AllowedProviders", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"allowed_providers,omitempty"`, Description: "New list of allowed provider IDs"},
	{FlagName: "content-filter-builtins", FieldPath: "Body.ContentFilterBuiltins", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"content_filter_builtins,omitempty"`, Description: "Builtin content filters to apply. Set to null to remove. The \"flag\" action is only supported for \"regex-prompt-injection\"; PII slugs (email, phone, ssn, credit-card, ip-address, person-name, address) accept \"block\" or \"redact\" only."},
	{FlagName: "content-filters", FieldPath: "Body.ContentFilters", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"content_filters,omitempty"`, Description: "Custom regex content filters to apply. Set to null to remove."},
	{FlagName: "description", FieldPath: "Body.Description", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"description,omitempty"`, Description: "New description for the guardrail"},
	{FlagName: "enforce-zdr", FieldPath: "Body.EnforceZdr", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"enforce_zdr,omitempty"`, Description: "Deprecated. Use enforce_zdr_anthropic, enforce_zdr_openai, enforce_zdr_google, and enforce_zdr_other instead. When provided, its value is copied into any of those per-provider fields that are not explicitly specified on the request."},
	{FlagName: "enforce-zdr-anthropic", FieldPath: "Body.EnforceZdrAnthropic", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"enforce_zdr_anthropic,omitempty"`, Description: "Whether to enforce zero data retention for Anthropic models. Falls back to enforce_zdr when not provided."},
	{FlagName: "enforce-zdr-google", FieldPath: "Body.EnforceZdrGoogle", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"enforce_zdr_google,omitempty"`, Description: "Whether to enforce zero data retention for Google models. Falls back to enforce_zdr when not provided."},
	{FlagName: "enforce-zdr-openai", FieldPath: "Body.EnforceZdrOpenai", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"enforce_zdr_openai,omitempty"`, Description: "Whether to enforce zero data retention for OpenAI models. Falls back to enforce_zdr when not provided."},
	{FlagName: "enforce-zdr-other", FieldPath: "Body.EnforceZdrOther", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"enforce_zdr_other,omitempty"`, Description: "Whether to enforce zero data retention for models that are not from Anthropic, OpenAI, or Google. Falls back to enforce_zdr when not provided."},
	{FlagName: "ignored-models", FieldPath: "Body.IgnoredModels", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"ignored_models,omitempty"`, Description: "Array of model identifiers to exclude from routing (slug or canonical_slug accepted)"},
	{FlagName: "ignored-providers", FieldPath: "Body.IgnoredProviders", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"ignored_providers,omitempty"`, Description: "List of provider IDs to exclude from routing"},
	{FlagName: "limit-usd", Shorthand: "l", FieldPath: "Body.LimitUsd", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"limit_usd,omitempty"`, Description: "New spending limit in USD"},
	{FlagName: "name", Shorthand: "n", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Optional: true, Description: "New name for the guardrail"},
	{FlagName: "reset-interval", Shorthand: "r", FieldPath: "Body.ResetInterval", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"reset_interval,omitempty"`, Description: "Interval at which the limit resets (daily, weekly, monthly) (options: daily, weekly, monthly)"},
}

// initUpdateCmd initializes the update command.
func initUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "update",
		Short:   "Update a guardrail",
		Long:    "Update an existing guardrail. [Management key](/docs/guides/overview/auth/management-api-keys) required.",
		Example: "  openrouter guardrails update --id 550e8400-e29b-41d4-a716-446655440000",
		RunE:    runUpdateCmd,
	}
	flagutil.RegisterFlags(cmd, updateCmdMeta)
	if err := flagutil.ValidateMeta[operations.UpdateGuardrailRequest](updateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runUpdateCmd executes the update command.
func runUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, updateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, updateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.UpdateGuardrailRequest](cmd, updateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerName(cmd, sdk.ServerList); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Guardrails.Update(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
