// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package endpoints

import (
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/client"
	"github.com/kenrogers/openrouter-cli/internal/flagutil"
	"github.com/kenrogers/openrouter-cli/internal/interactive"
	"github.com/kenrogers/openrouter-cli/internal/output"
	"github.com/kenrogers/openrouter-cli/internal/sdk"
	"github.com/kenrogers/openrouter-cli/internal/sdk/models/operations"
	"github.com/kenrogers/openrouter-cli/internal/usage"
	"github.com/spf13/cobra"
)

var listZdrEndpointsCmdMeta = []flagutil.FlagMeta{}

// initListZdrEndpointsCmd initializes the list-zdr-endpoints command.
func initListZdrEndpointsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list-zdr-endpoints",
		Short:   "Preview the impact of ZDR on the available endpoints",
		Long:    "Preview the impact of ZDR on the available endpoints",
		Example: "  openrouter endpoints list-zdr-endpoints",
		RunE:    runListZdrEndpointsCmd,
		Aliases: []string{"lze"},
	}
	flagutil.RegisterFlags(cmd, listZdrEndpointsCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListEndpointsZdrRequest](listZdrEndpointsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-zdr-endpoints: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListZdrEndpointsCmd executes the list-zdr-endpoints command.
func runListZdrEndpointsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listZdrEndpointsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listZdrEndpointsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListEndpointsZdrRequest](cmd, listZdrEndpointsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerName(cmd, sdk.ServerList); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Endpoints.ListZdrEndpoints(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
