// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package oauth

import (
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/client"
	"github.com/kenrogers/openrouter-cli/internal/flagutil"
	"github.com/kenrogers/openrouter-cli/internal/interactive"
	"github.com/kenrogers/openrouter-cli/internal/output"
	"github.com/kenrogers/openrouter-cli/internal/sdk"
	"github.com/kenrogers/openrouter-cli/internal/sdk/models/operations"
	"github.com/kenrogers/openrouter-cli/internal/usage"
	"github.com/spf13/cobra"
)

var createAuthCodeCmdMeta = []flagutil.FlagMeta{
	{FlagName: "callback-url", FieldPath: "Body.CallbackURL", Kind: flagutil.FlagKindString, Required: true, Description: "The callback URL to redirect to after authorization. Note, only https URLs on ports 443 and 3000 are allowed. [required]"},
	{FlagName: "code-challenge", FieldPath: "Body.CodeChallenge", Kind: flagutil.FlagKindString, Optional: true, Description: "PKCE code challenge for enhanced security"},
	{FlagName: "code-challenge-method", FieldPath: "Body.CodeChallengeMethod", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"S256", "plain"}, Description: "The method used to generate the code challenge (options: S256, plain)"},
	{FlagName: "expires-at", Shorthand: "e", FieldPath: "Body.ExpiresAt", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"expires_at,omitempty"`, Description: "Optional expiration time for the API key to be created"},
	{FlagName: "key-label", Shorthand: "k", FieldPath: "Body.KeyLabel", Kind: flagutil.FlagKindString, Optional: true, Description: "Optional custom label for the API key. Defaults to the app name if not provided."},
	{FlagName: "limit", Shorthand: "l", FieldPath: "Body.Limit", Kind: flagutil.FlagKindFloat64, Optional: true, Description: "Credit limit for the API key to be created"},
	{FlagName: "usage-limit-type", Shorthand: "u", FieldPath: "Body.UsageLimitType", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"daily", "weekly", "monthly"}, Description: "Optional credit limit reset interval. When set, the credit limit resets on this interval. (options: daily, weekly, monthly)"},
}

// initCreateAuthCodeCmd initializes the create-auth-code command.
func initCreateAuthCodeCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create-auth-code",
		Short:   "Create authorization code",
		Long:    "Create an authorization code for the PKCE flow to generate a user-controlled API key",
		Example: "  openrouter O-auth create-auth-code --callback-url https://myapp.com/auth/callback",
		RunE:    runCreateAuthCodeCmd,
		Aliases: []string{"cac"},
	}
	flagutil.RegisterFlags(cmd, createAuthCodeCmdMeta)
	if err := flagutil.ValidateMeta[operations.CreateAuthKeysCodeRequest](createAuthCodeCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create-auth-code: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateAuthCodeCmd executes the create-auth-code command.
func runCreateAuthCodeCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createAuthCodeCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createAuthCodeCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.CreateAuthKeysCodeRequest](cmd, createAuthCodeCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerName(cmd, sdk.ServerList); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.OAuth.CreateAuthCode(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
