// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package oauth

import (
	"github.com/kenrogers/openrouter-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitOAuthRoot(parent *cobra.Command) error {
	var OAuthCmd = &cobra.Command{
		Use:   "O-auth",
		Short: "OAuth authentication endpoints",
		Long:  "OAuth authentication endpoints",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"Oa"},
	}

	if err := initExchangeAuthCodeForAPIKeyCmd(OAuthCmd); err != nil {
		return err
	}

	if err := initCreateAuthCodeCmd(OAuthCmd); err != nil {
		return err
	}

	parent.AddCommand(OAuthCmd)
	return nil
}
