// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ActivityResponse struct {
	// List of activity items
	Data []ActivityItem `json:"data"`
}

func (a *ActivityResponse) GetData() []ActivityItem {
	if a == nil {
		return []ActivityItem{}
	}
	return a.Data
}
