// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ActivityItem struct {
	// BYOK inference cost in USD (external credits spent)
	ByokUsageInference float64 `json:"byok_usage_inference"`
	// Total completion tokens generated
	CompletionTokens int64 `json:"completion_tokens"`
	// Date of the activity (YYYY-MM-DD format)
	Date string `json:"date"`
	// Unique identifier for the endpoint
	EndpointID string `json:"endpoint_id"`
	// Model slug (e.g., "openai/gpt-4.1")
	Model string `json:"model"`
	// Model permaslug (e.g., "openai/gpt-4.1-2025-04-14")
	ModelPermaslug string `json:"model_permaslug"`
	// Total prompt tokens used
	PromptTokens int64 `json:"prompt_tokens"`
	// Name of the provider serving this endpoint
	ProviderName string `json:"provider_name"`
	// Total reasoning tokens used
	ReasoningTokens int64 `json:"reasoning_tokens"`
	// Number of requests made
	Requests int64 `json:"requests"`
	// Total cost in USD (OpenRouter credits spent)
	Usage float64 `json:"usage"`
}

func (a *ActivityItem) GetByokUsageInference() float64 {
	if a == nil {
		return 0.0
	}
	return a.ByokUsageInference
}

func (a *ActivityItem) GetCompletionTokens() int64 {
	if a == nil {
		return 0
	}
	return a.CompletionTokens
}

func (a *ActivityItem) GetDate() string {
	if a == nil {
		return ""
	}
	return a.Date
}

func (a *ActivityItem) GetEndpointID() string {
	if a == nil {
		return ""
	}
	return a.EndpointID
}

func (a *ActivityItem) GetModel() string {
	if a == nil {
		return ""
	}
	return a.Model
}

func (a *ActivityItem) GetModelPermaslug() string {
	if a == nil {
		return ""
	}
	return a.ModelPermaslug
}

func (a *ActivityItem) GetPromptTokens() int64 {
	if a == nil {
		return 0
	}
	return a.PromptTokens
}

func (a *ActivityItem) GetProviderName() string {
	if a == nil {
		return ""
	}
	return a.ProviderName
}

func (a *ActivityItem) GetReasoningTokens() int64 {
	if a == nil {
		return 0
	}
	return a.ReasoningTokens
}

func (a *ActivityItem) GetRequests() int64 {
	if a == nil {
		return 0
	}
	return a.Requests
}

func (a *ActivityItem) GetUsage() float64 {
	if a == nil {
		return 0.0
	}
	return a.Usage
}
