// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type ApplyPatchUpdateFileOperationType string

const (
	ApplyPatchUpdateFileOperationTypeUpdateFile ApplyPatchUpdateFileOperationType = "update_file"
)

func (e ApplyPatchUpdateFileOperationType) ToPointer() *ApplyPatchUpdateFileOperationType {
	return &e
}
func (e *ApplyPatchUpdateFileOperationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "update_file":
		*e = ApplyPatchUpdateFileOperationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ApplyPatchUpdateFileOperationType: %v", v)
	}
}

// ApplyPatchUpdateFileOperation - The `update_file` variant of an `apply_patch_call.operation`. Carries a V4A diff describing edits to an existing file.
type ApplyPatchUpdateFileOperation struct {
	Diff string                            `json:"diff"`
	Path string                            `json:"path"`
	Type ApplyPatchUpdateFileOperationType `json:"type"`
}

func (a ApplyPatchUpdateFileOperation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ApplyPatchUpdateFileOperation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ApplyPatchUpdateFileOperation) GetDiff() string {
	if a == nil {
		return ""
	}
	return a.Diff
}

func (a *ApplyPatchUpdateFileOperation) GetPath() string {
	if a == nil {
		return ""
	}
	return a.Path
}

func (a *ApplyPatchUpdateFileOperation) GetType() ApplyPatchUpdateFileOperationType {
	if a == nil {
		return ApplyPatchUpdateFileOperationType("")
	}
	return a.Type
}
