// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BulkRemoveWorkspaceMembersResponse struct {
	// Number of members removed
	RemovedCount int64 `json:"removed_count"`
}

func (b *BulkRemoveWorkspaceMembersResponse) GetRemovedCount() int64 {
	if b == nil {
		return 0
	}
	return b.RemovedCount
}
