// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BulkAssignMembersRequest struct {
	// Array of member user IDs to assign to the guardrail
	MemberUserIds []string `json:"member_user_ids"`
}

func (b *BulkAssignMembersRequest) GetMemberUserIds() []string {
	if b == nil {
		return []string{}
	}
	return b.MemberUserIds
}
