// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type ChatContentItemsType string

const (
	ChatContentItemsTypeFile       ChatContentItemsType = "file"
	ChatContentItemsTypeImageURL   ChatContentItemsType = "image_url"
	ChatContentItemsTypeInputAudio ChatContentItemsType = "input_audio"
	ChatContentItemsTypeInputVideo ChatContentItemsType = "input_video"
	ChatContentItemsTypeText       ChatContentItemsType = "text"
	ChatContentItemsTypeVideoURL   ChatContentItemsType = "video_url"
	ChatContentItemsTypeUnknown    ChatContentItemsType = "UNKNOWN"
)

// ChatContentItems - Content part for chat completion messages
type ChatContentItems struct {
	ChatContentText        *ChatContentText        `queryParam:"inline" union:"member"`
	ChatContentImage       *ChatContentImage       `queryParam:"inline" union:"member"`
	ChatContentAudio       *ChatContentAudio       `queryParam:"inline" union:"member"`
	LegacyChatContentVideo *LegacyChatContentVideo `queryParam:"inline" union:"member"`
	ChatContentVideo       *ChatContentVideo       `queryParam:"inline" union:"member"`
	ChatContentFile        *ChatContentFile        `queryParam:"inline" union:"member"`
	UnknownRaw             json.RawMessage         `json:"-" union:"unknown"`

	Type ChatContentItemsType
}

func CreateChatContentItemsFile(file ChatContentFile) ChatContentItems {
	typ := ChatContentItemsTypeFile

	typStr := ChatContentFileType(typ)
	file.Type = typStr

	return ChatContentItems{
		ChatContentFile: &file,
		Type:            typ,
	}
}

func CreateChatContentItemsImageURL(imageURL ChatContentImage) ChatContentItems {
	typ := ChatContentItemsTypeImageURL

	typStr := ChatContentImageType(typ)
	imageURL.Type = typStr

	return ChatContentItems{
		ChatContentImage: &imageURL,
		Type:             typ,
	}
}

func CreateChatContentItemsInputAudio(inputAudio ChatContentAudio) ChatContentItems {
	typ := ChatContentItemsTypeInputAudio

	typStr := ChatContentAudioType(typ)
	inputAudio.Type = typStr

	return ChatContentItems{
		ChatContentAudio: &inputAudio,
		Type:             typ,
	}
}

func CreateChatContentItemsInputVideo(inputVideo LegacyChatContentVideo) ChatContentItems {
	typ := ChatContentItemsTypeInputVideo

	typStr := LegacyChatContentVideoType(typ)
	inputVideo.Type = typStr

	return ChatContentItems{
		LegacyChatContentVideo: &inputVideo,
		Type:                   typ,
	}
}

func CreateChatContentItemsText(text ChatContentText) ChatContentItems {
	typ := ChatContentItemsTypeText

	typStr := ChatContentTextType(typ)
	text.Type = typStr

	return ChatContentItems{
		ChatContentText: &text,
		Type:            typ,
	}
}

func CreateChatContentItemsVideoURL(videoURL ChatContentVideo) ChatContentItems {
	typ := ChatContentItemsTypeVideoURL

	typStr := ChatContentVideoType(typ)
	videoURL.Type = typStr

	return ChatContentItems{
		ChatContentVideo: &videoURL,
		Type:             typ,
	}
}

func CreateChatContentItemsUnknown(raw json.RawMessage) ChatContentItems {
	return ChatContentItems{
		UnknownRaw: raw,
		Type:       ChatContentItemsTypeUnknown,
	}
}

func (u ChatContentItems) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u ChatContentItems) IsUnknown() bool {
	return u.Type == ChatContentItemsTypeUnknown
}

func (u *ChatContentItems) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ChatContentItemsTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ChatContentItemsTypeUnknown
		return nil
	}

	switch dis.Type {
	case "file":
		chatContentFile := new(ChatContentFile)
		if err := utils.UnmarshalJSON(data, &chatContentFile, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == file) type ChatContentFile within ChatContentItems: %w", string(data), err)
		}

		u.ChatContentFile = chatContentFile
		u.Type = ChatContentItemsTypeFile
		return nil
	case "image_url":
		chatContentImage := new(ChatContentImage)
		if err := utils.UnmarshalJSON(data, &chatContentImage, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == image_url) type ChatContentImage within ChatContentItems: %w", string(data), err)
		}

		u.ChatContentImage = chatContentImage
		u.Type = ChatContentItemsTypeImageURL
		return nil
	case "input_audio":
		chatContentAudio := new(ChatContentAudio)
		if err := utils.UnmarshalJSON(data, &chatContentAudio, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == input_audio) type ChatContentAudio within ChatContentItems: %w", string(data), err)
		}

		u.ChatContentAudio = chatContentAudio
		u.Type = ChatContentItemsTypeInputAudio
		return nil
	case "input_video":
		legacyChatContentVideo := new(LegacyChatContentVideo)
		if err := utils.UnmarshalJSON(data, &legacyChatContentVideo, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == input_video) type LegacyChatContentVideo within ChatContentItems: %w", string(data), err)
		}

		u.LegacyChatContentVideo = legacyChatContentVideo
		u.Type = ChatContentItemsTypeInputVideo
		return nil
	case "text":
		chatContentText := new(ChatContentText)
		if err := utils.UnmarshalJSON(data, &chatContentText, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == text) type ChatContentText within ChatContentItems: %w", string(data), err)
		}

		u.ChatContentText = chatContentText
		u.Type = ChatContentItemsTypeText
		return nil
	case "video_url":
		chatContentVideo := new(ChatContentVideo)
		if err := utils.UnmarshalJSON(data, &chatContentVideo, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == video_url) type ChatContentVideo within ChatContentItems: %w", string(data), err)
		}

		u.ChatContentVideo = chatContentVideo
		u.Type = ChatContentItemsTypeVideoURL
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ChatContentItemsTypeUnknown
		return nil
	}

}

func (u ChatContentItems) MarshalJSON() ([]byte, error) {
	if u.ChatContentText != nil {
		return utils.MarshalJSON(u.ChatContentText, "", true)
	}

	if u.ChatContentImage != nil {
		return utils.MarshalJSON(u.ChatContentImage, "", true)
	}

	if u.ChatContentAudio != nil {
		return utils.MarshalJSON(u.ChatContentAudio, "", true)
	}

	if u.LegacyChatContentVideo != nil {
		return utils.MarshalJSON(u.LegacyChatContentVideo, "", true)
	}

	if u.ChatContentVideo != nil {
		return utils.MarshalJSON(u.ChatContentVideo, "", true)
	}

	if u.ChatContentFile != nil {
		return utils.MarshalJSON(u.ChatContentFile, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type ChatContentItems: all fields are null")
}
