// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ChatReasoningSummaryVerbosityEnum string

const (
	ChatReasoningSummaryVerbosityEnumAuto     ChatReasoningSummaryVerbosityEnum = "auto"
	ChatReasoningSummaryVerbosityEnumConcise  ChatReasoningSummaryVerbosityEnum = "concise"
	ChatReasoningSummaryVerbosityEnumDetailed ChatReasoningSummaryVerbosityEnum = "detailed"
)

func (e ChatReasoningSummaryVerbosityEnum) ToPointer() *ChatReasoningSummaryVerbosityEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ChatReasoningSummaryVerbosityEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "auto", "concise", "detailed":
			return true
		}
	}
	return false
}
