// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/optionalnullable"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

// ChatTokenLogprobs - Log probabilities for the completion
type ChatTokenLogprobs struct {
	// Log probabilities for content tokens
	Content []ChatTokenLogprob `json:"content"`
	// Log probabilities for refusal tokens
	Refusal optionalnullable.OptionalNullable[[]ChatTokenLogprob] `json:"refusal,omitzero"`
}

func (c ChatTokenLogprobs) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatTokenLogprobs) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatTokenLogprobs) GetContent() []ChatTokenLogprob {
	if c == nil {
		return nil
	}
	return c.Content
}

func (c *ChatTokenLogprobs) GetRefusal() optionalnullable.OptionalNullable[[]ChatTokenLogprob] {
	if c == nil {
		return nil
	}
	return c.Refusal
}
