// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/optionalnullable"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type Object string

const (
	ObjectChatCompletion Object = "chat.completion"
)

func (e Object) ToPointer() *Object {
	return &e
}
func (e *Object) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "chat.completion":
		*e = Object(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Object: %v", v)
	}
}

// ChatResult - Chat completion response
type ChatResult struct {
	// List of completion choices
	Choices []ChatChoice `json:"choices"`
	// Unix timestamp of creation
	Created int64 `json:"created"`
	// Unique completion identifier
	ID string `json:"id"`
	// Model used for completion
	Model              string              `json:"model"`
	Object             Object              `json:"object"`
	OpenrouterMetadata *OpenRouterMetadata `json:"openrouter_metadata,omitzero"`
	// The service tier used by the upstream provider for this request
	ServiceTier optionalnullable.OptionalNullable[string] `json:"service_tier,omitzero"`
	// System fingerprint
	SystemFingerprint *string `json:"system_fingerprint"`
	// Token usage statistics
	Usage *ChatUsage `json:"usage,omitzero"`
}

func (c ChatResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatResult) GetChoices() []ChatChoice {
	if c == nil {
		return []ChatChoice{}
	}
	return c.Choices
}

func (c *ChatResult) GetCreated() int64 {
	if c == nil {
		return 0
	}
	return c.Created
}

func (c *ChatResult) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ChatResult) GetModel() string {
	if c == nil {
		return ""
	}
	return c.Model
}

func (c *ChatResult) GetObject() Object {
	if c == nil {
		return Object("")
	}
	return c.Object
}

func (c *ChatResult) GetOpenrouterMetadata() *OpenRouterMetadata {
	if c == nil {
		return nil
	}
	return c.OpenrouterMetadata
}

func (c *ChatResult) GetServiceTier() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.ServiceTier
}

func (c *ChatResult) GetSystemFingerprint() *string {
	if c == nil {
		return nil
	}
	return c.SystemFingerprint
}

func (c *ChatResult) GetUsage() *ChatUsage {
	if c == nil {
		return nil
	}
	return c.Usage
}
