// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type ChatToolChoice3 string

const (
	ChatToolChoice3Required ChatToolChoice3 = "required"
)

func (e ChatToolChoice3) ToPointer() *ChatToolChoice3 {
	return &e
}
func (e *ChatToolChoice3) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "required":
		*e = ChatToolChoice3(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChatToolChoice3: %v", v)
	}
}

type ChatToolChoice2 string

const (
	ChatToolChoice2Auto ChatToolChoice2 = "auto"
)

func (e ChatToolChoice2) ToPointer() *ChatToolChoice2 {
	return &e
}
func (e *ChatToolChoice2) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "auto":
		*e = ChatToolChoice2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChatToolChoice2: %v", v)
	}
}

type ChatToolChoice1 string

const (
	ChatToolChoice1None ChatToolChoice1 = "none"
)

func (e ChatToolChoice1) ToPointer() *ChatToolChoice1 {
	return &e
}
func (e *ChatToolChoice1) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "none":
		*e = ChatToolChoice1(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChatToolChoice1: %v", v)
	}
}

type ChatToolChoiceType string

const (
	ChatToolChoiceTypeChatToolChoice1      ChatToolChoiceType = "ChatToolChoice_1"
	ChatToolChoiceTypeChatToolChoice2      ChatToolChoiceType = "ChatToolChoice_2"
	ChatToolChoiceTypeChatToolChoice3      ChatToolChoiceType = "ChatToolChoice_3"
	ChatToolChoiceTypeChatNamedToolChoice  ChatToolChoiceType = "ChatNamedToolChoice"
	ChatToolChoiceTypeChatServerToolChoice ChatToolChoiceType = "ChatServerToolChoice"
)

// ChatToolChoice - Tool choice configuration
type ChatToolChoice struct {
	ChatToolChoice1      *ChatToolChoice1      `queryParam:"inline" union:"member"`
	ChatToolChoice2      *ChatToolChoice2      `queryParam:"inline" union:"member"`
	ChatToolChoice3      *ChatToolChoice3      `queryParam:"inline" union:"member"`
	ChatNamedToolChoice  *ChatNamedToolChoice  `queryParam:"inline" union:"member"`
	ChatServerToolChoice *ChatServerToolChoice `queryParam:"inline" union:"member"`

	Type ChatToolChoiceType
}

func CreateChatToolChoiceChatToolChoice1(chatToolChoice1 ChatToolChoice1) ChatToolChoice {
	typ := ChatToolChoiceTypeChatToolChoice1

	return ChatToolChoice{
		ChatToolChoice1: &chatToolChoice1,
		Type:            typ,
	}
}

func CreateChatToolChoiceChatToolChoice2(chatToolChoice2 ChatToolChoice2) ChatToolChoice {
	typ := ChatToolChoiceTypeChatToolChoice2

	return ChatToolChoice{
		ChatToolChoice2: &chatToolChoice2,
		Type:            typ,
	}
}

func CreateChatToolChoiceChatToolChoice3(chatToolChoice3 ChatToolChoice3) ChatToolChoice {
	typ := ChatToolChoiceTypeChatToolChoice3

	return ChatToolChoice{
		ChatToolChoice3: &chatToolChoice3,
		Type:            typ,
	}
}

func CreateChatToolChoiceChatNamedToolChoice(chatNamedToolChoice ChatNamedToolChoice) ChatToolChoice {
	typ := ChatToolChoiceTypeChatNamedToolChoice

	return ChatToolChoice{
		ChatNamedToolChoice: &chatNamedToolChoice,
		Type:                typ,
	}
}

func CreateChatToolChoiceChatServerToolChoice(chatServerToolChoice ChatServerToolChoice) ChatToolChoice {
	typ := ChatToolChoiceTypeChatServerToolChoice

	return ChatToolChoice{
		ChatServerToolChoice: &chatServerToolChoice,
		Type:                 typ,
	}
}

func (u *ChatToolChoice) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var chatToolChoice1 ChatToolChoice1 = ChatToolChoice1("")
	if err := utils.UnmarshalJSON(data, &chatToolChoice1, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ChatToolChoiceTypeChatToolChoice1,
			Value: &chatToolChoice1,
		})
	}

	var chatToolChoice2 ChatToolChoice2 = ChatToolChoice2("")
	if err := utils.UnmarshalJSON(data, &chatToolChoice2, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ChatToolChoiceTypeChatToolChoice2,
			Value: &chatToolChoice2,
		})
	}

	var chatToolChoice3 ChatToolChoice3 = ChatToolChoice3("")
	if err := utils.UnmarshalJSON(data, &chatToolChoice3, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ChatToolChoiceTypeChatToolChoice3,
			Value: &chatToolChoice3,
		})
	}

	var chatNamedToolChoice ChatNamedToolChoice = ChatNamedToolChoice{}
	if err := utils.UnmarshalJSON(data, &chatNamedToolChoice, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ChatToolChoiceTypeChatNamedToolChoice,
			Value: &chatNamedToolChoice,
		})
	}

	var chatServerToolChoice ChatServerToolChoice = ChatServerToolChoice{}
	if err := utils.UnmarshalJSON(data, &chatServerToolChoice, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ChatToolChoiceTypeChatServerToolChoice,
			Value: &chatServerToolChoice,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ChatToolChoice", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ChatToolChoice", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ChatToolChoiceType)
	switch best.Type {
	case ChatToolChoiceTypeChatToolChoice1:
		u.ChatToolChoice1 = best.Value.(*ChatToolChoice1)
		return nil
	case ChatToolChoiceTypeChatToolChoice2:
		u.ChatToolChoice2 = best.Value.(*ChatToolChoice2)
		return nil
	case ChatToolChoiceTypeChatToolChoice3:
		u.ChatToolChoice3 = best.Value.(*ChatToolChoice3)
		return nil
	case ChatToolChoiceTypeChatNamedToolChoice:
		u.ChatNamedToolChoice = best.Value.(*ChatNamedToolChoice)
		return nil
	case ChatToolChoiceTypeChatServerToolChoice:
		u.ChatServerToolChoice = best.Value.(*ChatServerToolChoice)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ChatToolChoice", string(data))
}

func (u ChatToolChoice) MarshalJSON() ([]byte, error) {
	if u.ChatToolChoice1 != nil {
		return utils.MarshalJSON(u.ChatToolChoice1, "", true)
	}

	if u.ChatToolChoice2 != nil {
		return utils.MarshalJSON(u.ChatToolChoice2, "", true)
	}

	if u.ChatToolChoice3 != nil {
		return utils.MarshalJSON(u.ChatToolChoice3, "", true)
	}

	if u.ChatNamedToolChoice != nil {
		return utils.MarshalJSON(u.ChatNamedToolChoice, "", true)
	}

	if u.ChatServerToolChoice != nil {
		return utils.MarshalJSON(u.ChatServerToolChoice, "", true)
	}

	return nil, errors.New("could not marshal union type ChatToolChoice: all fields are null")
}
