// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

// ChatServerToolChoice - OpenRouter extension: force a specific server tool by naming it directly in `tool_choice.type` instead of wrapping it in `{ type: "function", function: { name } }`.
type ChatServerToolChoice struct {
	// OpenRouter server-tool type to force (e.g. `openrouter:web_search`, `web_search`, `web_search_preview`).
	Type string `json:"type"`
}

func (c ChatServerToolChoice) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatServerToolChoice) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatServerToolChoice) GetType() string {
	if c == nil {
		return ""
	}
	return c.Type
}
