// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type ChatToolMessageContentType string

const (
	ChatToolMessageContentTypeStr                     ChatToolMessageContentType = "str"
	ChatToolMessageContentTypeArrayOfChatContentItems ChatToolMessageContentType = "arrayOfChatContentItems"
)

// ChatToolMessageContent - Tool response content
type ChatToolMessageContent struct {
	Str                     *string            `queryParam:"inline" union:"member"`
	ArrayOfChatContentItems []ChatContentItems `queryParam:"inline" union:"member"`

	Type ChatToolMessageContentType
}

func CreateChatToolMessageContentStr(str string) ChatToolMessageContent {
	typ := ChatToolMessageContentTypeStr

	return ChatToolMessageContent{
		Str:  &str,
		Type: typ,
	}
}

func CreateChatToolMessageContentArrayOfChatContentItems(arrayOfChatContentItems []ChatContentItems) ChatToolMessageContent {
	typ := ChatToolMessageContentTypeArrayOfChatContentItems

	return ChatToolMessageContent{
		ArrayOfChatContentItems: arrayOfChatContentItems,
		Type:                    typ,
	}
}

func (u *ChatToolMessageContent) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ChatToolMessageContentTypeStr,
			Value: &str,
		})
	}

	var arrayOfChatContentItems []ChatContentItems = []ChatContentItems{}
	if err := utils.UnmarshalJSON(data, &arrayOfChatContentItems, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ChatToolMessageContentTypeArrayOfChatContentItems,
			Value: arrayOfChatContentItems,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ChatToolMessageContent", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ChatToolMessageContent", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ChatToolMessageContentType)
	switch best.Type {
	case ChatToolMessageContentTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case ChatToolMessageContentTypeArrayOfChatContentItems:
		u.ArrayOfChatContentItems = best.Value.([]ChatContentItems)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ChatToolMessageContent", string(data))
}

func (u ChatToolMessageContent) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfChatContentItems != nil {
		return utils.MarshalJSON(u.ArrayOfChatContentItems, "", true)
	}

	return nil, errors.New("could not marshal union type ChatToolMessageContent: all fields are null")
}

type ChatToolMessageRole string

const (
	ChatToolMessageRoleTool ChatToolMessageRole = "tool"
)

func (e ChatToolMessageRole) ToPointer() *ChatToolMessageRole {
	return &e
}
func (e *ChatToolMessageRole) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tool":
		*e = ChatToolMessageRole(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChatToolMessageRole: %v", v)
	}
}

// ChatToolMessage - Tool response message
type ChatToolMessage struct {
	// Tool response content
	Content ChatToolMessageContent `json:"content"`
	Role    ChatToolMessageRole    `json:"role"`
	// ID of the assistant message tool call this message responds to
	ToolCallID string `json:"tool_call_id"`
}

func (c ChatToolMessage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatToolMessage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatToolMessage) GetContent() ChatToolMessageContent {
	if c == nil {
		return ChatToolMessageContent{}
	}
	return c.Content
}

func (c *ChatToolMessage) GetRole() ChatToolMessageRole {
	if c == nil {
		return ChatToolMessageRole("")
	}
	return c.Role
}

func (c *ChatToolMessage) GetToolCallID() string {
	if c == nil {
		return ""
	}
	return c.ToolCallID
}
