// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

// ChatAudioOutput - Audio output data or reference
type ChatAudioOutput struct {
	// Base64 encoded audio data
	Data *string `json:"data,omitzero"`
	// Audio expiration timestamp
	ExpiresAt *int64 `json:"expires_at,omitzero"`
	// Audio output identifier
	ID *string `json:"id,omitzero"`
	// Audio transcript
	Transcript *string `json:"transcript,omitzero"`
}

func (c ChatAudioOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatAudioOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatAudioOutput) GetData() *string {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *ChatAudioOutput) GetExpiresAt() *int64 {
	if c == nil {
		return nil
	}
	return c.ExpiresAt
}

func (c *ChatAudioOutput) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *ChatAudioOutput) GetTranscript() *string {
	if c == nil {
		return nil
	}
	return c.Transcript
}
