// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ChatStreamOptions - Streaming configuration options
type ChatStreamOptions struct {
	// Deprecated: This field has no effect. Full usage details are always included.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	IncludeUsage *bool `json:"include_usage,omitzero"`
}

func (c *ChatStreamOptions) GetIncludeUsage() *bool {
	if c == nil {
		return nil
	}
	return c.IncludeUsage
}
