// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/optionalnullable"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type Modalities string

const (
	ModalitiesText  Modalities = "text"
	ModalitiesImage Modalities = "image"
	ModalitiesAudio Modalities = "audio"
)

func (e Modalities) ToPointer() *Modalities {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Modalities) IsExact() bool {
	if e != nil {
		switch *e {
		case "text", "image", "audio":
			return true
		}
	}
	return false
}

type PluginsType string

const (
	PluginsTypeAutoRouter         PluginsType = "auto-router"
	PluginsTypeContextCompression PluginsType = "context-compression"
	PluginsTypeFileParser         PluginsType = "file-parser"
	PluginsTypeFusion             PluginsType = "fusion"
	PluginsTypeModeration         PluginsType = "moderation"
	PluginsTypeParetoRouter       PluginsType = "pareto-router"
	PluginsTypeResponseHealing    PluginsType = "response-healing"
	PluginsTypeWeb                PluginsType = "web"
	PluginsTypeWebFetch           PluginsType = "web-fetch"
)

type Plugins struct {
	AutoRouterPlugin         *AutoRouterPlugin         `queryParam:"inline" union:"member"`
	ModerationPlugin         *ModerationPlugin         `queryParam:"inline" union:"member"`
	WebSearchPlugin          *WebSearchPlugin          `queryParam:"inline" union:"member"`
	WebFetchPlugin           *WebFetchPlugin           `queryParam:"inline" union:"member"`
	FileParserPlugin         *FileParserPlugin         `queryParam:"inline" union:"member"`
	ResponseHealingPlugin    *ResponseHealingPlugin    `queryParam:"inline" union:"member"`
	ContextCompressionPlugin *ContextCompressionPlugin `queryParam:"inline" union:"member"`
	ParetoRouterPlugin       *ParetoRouterPlugin       `queryParam:"inline" union:"member"`
	FusionPlugin             *FusionPlugin             `queryParam:"inline" union:"member"`

	Type PluginsType
}

func CreatePluginsAutoRouter(autoRouter AutoRouterPlugin) Plugins {
	typ := PluginsTypeAutoRouter

	typStr := ID(typ)
	autoRouter.ID = typStr

	return Plugins{
		AutoRouterPlugin: &autoRouter,
		Type:             typ,
	}
}

func CreatePluginsContextCompression(contextCompression ContextCompressionPlugin) Plugins {
	typ := PluginsTypeContextCompression

	typStr := ContextCompressionPluginID(typ)
	contextCompression.ID = typStr

	return Plugins{
		ContextCompressionPlugin: &contextCompression,
		Type:                     typ,
	}
}

func CreatePluginsFileParser(fileParser FileParserPlugin) Plugins {
	typ := PluginsTypeFileParser

	typStr := FileParserPluginID(typ)
	fileParser.ID = typStr

	return Plugins{
		FileParserPlugin: &fileParser,
		Type:             typ,
	}
}

func CreatePluginsFusion(fusion FusionPlugin) Plugins {
	typ := PluginsTypeFusion

	typStr := FusionPluginID(typ)
	fusion.ID = typStr

	return Plugins{
		FusionPlugin: &fusion,
		Type:         typ,
	}
}

func CreatePluginsModeration(moderation ModerationPlugin) Plugins {
	typ := PluginsTypeModeration

	typStr := ModerationPluginID(typ)
	moderation.ID = typStr

	return Plugins{
		ModerationPlugin: &moderation,
		Type:             typ,
	}
}

func CreatePluginsParetoRouter(paretoRouter ParetoRouterPlugin) Plugins {
	typ := PluginsTypeParetoRouter

	typStr := ParetoRouterPluginID(typ)
	paretoRouter.ID = typStr

	return Plugins{
		ParetoRouterPlugin: &paretoRouter,
		Type:               typ,
	}
}

func CreatePluginsResponseHealing(responseHealing ResponseHealingPlugin) Plugins {
	typ := PluginsTypeResponseHealing

	typStr := ResponseHealingPluginID(typ)
	responseHealing.ID = typStr

	return Plugins{
		ResponseHealingPlugin: &responseHealing,
		Type:                  typ,
	}
}

func CreatePluginsWeb(web WebSearchPlugin) Plugins {
	typ := PluginsTypeWeb

	typStr := WebSearchPluginID(typ)
	web.ID = typStr

	return Plugins{
		WebSearchPlugin: &web,
		Type:            typ,
	}
}

func CreatePluginsWebFetch(webFetch WebFetchPlugin) Plugins {
	typ := PluginsTypeWebFetch

	typStr := WebFetchPluginID(typ)
	webFetch.ID = typStr

	return Plugins{
		WebFetchPlugin: &webFetch,
		Type:           typ,
	}
}

func (u *Plugins) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		ID string `json:"id"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.ID {
	case "auto-router":
		autoRouterPlugin := new(AutoRouterPlugin)
		if err := utils.UnmarshalJSON(data, &autoRouterPlugin, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ID == auto-router) type AutoRouterPlugin within Plugins: %w", string(data), err)
		}

		u.AutoRouterPlugin = autoRouterPlugin
		u.Type = PluginsTypeAutoRouter
		return nil
	case "context-compression":
		contextCompressionPlugin := new(ContextCompressionPlugin)
		if err := utils.UnmarshalJSON(data, &contextCompressionPlugin, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ID == context-compression) type ContextCompressionPlugin within Plugins: %w", string(data), err)
		}

		u.ContextCompressionPlugin = contextCompressionPlugin
		u.Type = PluginsTypeContextCompression
		return nil
	case "file-parser":
		fileParserPlugin := new(FileParserPlugin)
		if err := utils.UnmarshalJSON(data, &fileParserPlugin, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ID == file-parser) type FileParserPlugin within Plugins: %w", string(data), err)
		}

		u.FileParserPlugin = fileParserPlugin
		u.Type = PluginsTypeFileParser
		return nil
	case "fusion":
		fusionPlugin := new(FusionPlugin)
		if err := utils.UnmarshalJSON(data, &fusionPlugin, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ID == fusion) type FusionPlugin within Plugins: %w", string(data), err)
		}

		u.FusionPlugin = fusionPlugin
		u.Type = PluginsTypeFusion
		return nil
	case "moderation":
		moderationPlugin := new(ModerationPlugin)
		if err := utils.UnmarshalJSON(data, &moderationPlugin, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ID == moderation) type ModerationPlugin within Plugins: %w", string(data), err)
		}

		u.ModerationPlugin = moderationPlugin
		u.Type = PluginsTypeModeration
		return nil
	case "pareto-router":
		paretoRouterPlugin := new(ParetoRouterPlugin)
		if err := utils.UnmarshalJSON(data, &paretoRouterPlugin, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ID == pareto-router) type ParetoRouterPlugin within Plugins: %w", string(data), err)
		}

		u.ParetoRouterPlugin = paretoRouterPlugin
		u.Type = PluginsTypeParetoRouter
		return nil
	case "response-healing":
		responseHealingPlugin := new(ResponseHealingPlugin)
		if err := utils.UnmarshalJSON(data, &responseHealingPlugin, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ID == response-healing) type ResponseHealingPlugin within Plugins: %w", string(data), err)
		}

		u.ResponseHealingPlugin = responseHealingPlugin
		u.Type = PluginsTypeResponseHealing
		return nil
	case "web":
		webSearchPlugin := new(WebSearchPlugin)
		if err := utils.UnmarshalJSON(data, &webSearchPlugin, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ID == web) type WebSearchPlugin within Plugins: %w", string(data), err)
		}

		u.WebSearchPlugin = webSearchPlugin
		u.Type = PluginsTypeWeb
		return nil
	case "web-fetch":
		webFetchPlugin := new(WebFetchPlugin)
		if err := utils.UnmarshalJSON(data, &webFetchPlugin, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ID == web-fetch) type WebFetchPlugin within Plugins: %w", string(data), err)
		}

		u.WebFetchPlugin = webFetchPlugin
		u.Type = PluginsTypeWebFetch
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Plugins", string(data))
}

func (u Plugins) MarshalJSON() ([]byte, error) {
	if u.AutoRouterPlugin != nil {
		return utils.MarshalJSON(u.AutoRouterPlugin, "", true)
	}

	if u.ModerationPlugin != nil {
		return utils.MarshalJSON(u.ModerationPlugin, "", true)
	}

	if u.WebSearchPlugin != nil {
		return utils.MarshalJSON(u.WebSearchPlugin, "", true)
	}

	if u.WebFetchPlugin != nil {
		return utils.MarshalJSON(u.WebFetchPlugin, "", true)
	}

	if u.FileParserPlugin != nil {
		return utils.MarshalJSON(u.FileParserPlugin, "", true)
	}

	if u.ResponseHealingPlugin != nil {
		return utils.MarshalJSON(u.ResponseHealingPlugin, "", true)
	}

	if u.ContextCompressionPlugin != nil {
		return utils.MarshalJSON(u.ContextCompressionPlugin, "", true)
	}

	if u.ParetoRouterPlugin != nil {
		return utils.MarshalJSON(u.ParetoRouterPlugin, "", true)
	}

	if u.FusionPlugin != nil {
		return utils.MarshalJSON(u.FusionPlugin, "", true)
	}

	return nil, errors.New("could not marshal union type Plugins: all fields are null")
}

// Effort - Constrains effort on reasoning for reasoning models
type Effort string

const (
	EffortXhigh   Effort = "xhigh"
	EffortHigh    Effort = "high"
	EffortMedium  Effort = "medium"
	EffortLow     Effort = "low"
	EffortMinimal Effort = "minimal"
	EffortNone    Effort = "none"
)

func (e Effort) ToPointer() *Effort {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Effort) IsExact() bool {
	if e != nil {
		switch *e {
		case "xhigh", "high", "medium", "low", "minimal", "none":
			return true
		}
	}
	return false
}

// Reasoning - Configuration options for reasoning models
type Reasoning struct {
	// Constrains effort on reasoning for reasoning models
	Effort  optionalnullable.OptionalNullable[Effort]                            `json:"effort,omitzero"`
	Summary optionalnullable.OptionalNullable[ChatReasoningSummaryVerbosityEnum] `json:"summary,omitzero"`
}

func (r *Reasoning) GetEffort() optionalnullable.OptionalNullable[Effort] {
	if r == nil {
		return nil
	}
	return r.Effort
}

func (r *Reasoning) GetSummary() optionalnullable.OptionalNullable[ChatReasoningSummaryVerbosityEnum] {
	if r == nil {
		return nil
	}
	return r.Summary
}

type ChatRequestResponseFormatType string

const (
	ChatRequestResponseFormatTypeGrammar    ChatRequestResponseFormatType = "grammar"
	ChatRequestResponseFormatTypeJSONObject ChatRequestResponseFormatType = "json_object"
	ChatRequestResponseFormatTypeJSONSchema ChatRequestResponseFormatType = "json_schema"
	ChatRequestResponseFormatTypePython     ChatRequestResponseFormatType = "python"
	ChatRequestResponseFormatTypeText       ChatRequestResponseFormatType = "text"
)

// ChatRequestResponseFormat - Response format configuration
type ChatRequestResponseFormat struct {
	ChatFormatTextConfig       *ChatFormatTextConfig       `queryParam:"inline" union:"member"`
	FormatJSONObjectConfig     *FormatJSONObjectConfig     `queryParam:"inline" union:"member"`
	ChatFormatJSONSchemaConfig *ChatFormatJSONSchemaConfig `queryParam:"inline" union:"member"`
	ChatFormatGrammarConfig    *ChatFormatGrammarConfig    `queryParam:"inline" union:"member"`
	ChatFormatPythonConfig     *ChatFormatPythonConfig     `queryParam:"inline" union:"member"`

	Type ChatRequestResponseFormatType
}

func CreateChatRequestResponseFormatGrammar(grammar ChatFormatGrammarConfig) ChatRequestResponseFormat {
	typ := ChatRequestResponseFormatTypeGrammar

	typStr := ChatFormatGrammarConfigType(typ)
	grammar.Type = typStr

	return ChatRequestResponseFormat{
		ChatFormatGrammarConfig: &grammar,
		Type:                    typ,
	}
}

func CreateChatRequestResponseFormatJSONObject(jsonObject FormatJSONObjectConfig) ChatRequestResponseFormat {
	typ := ChatRequestResponseFormatTypeJSONObject

	typStr := FormatJSONObjectConfigType(typ)
	jsonObject.Type = typStr

	return ChatRequestResponseFormat{
		FormatJSONObjectConfig: &jsonObject,
		Type:                   typ,
	}
}

func CreateChatRequestResponseFormatJSONSchema(jsonSchema ChatFormatJSONSchemaConfig) ChatRequestResponseFormat {
	typ := ChatRequestResponseFormatTypeJSONSchema

	typStr := ChatFormatJSONSchemaConfigType(typ)
	jsonSchema.Type = typStr

	return ChatRequestResponseFormat{
		ChatFormatJSONSchemaConfig: &jsonSchema,
		Type:                       typ,
	}
}

func CreateChatRequestResponseFormatPython(python ChatFormatPythonConfig) ChatRequestResponseFormat {
	typ := ChatRequestResponseFormatTypePython

	typStr := ChatFormatPythonConfigType(typ)
	python.Type = typStr

	return ChatRequestResponseFormat{
		ChatFormatPythonConfig: &python,
		Type:                   typ,
	}
}

func CreateChatRequestResponseFormatText(text ChatFormatTextConfig) ChatRequestResponseFormat {
	typ := ChatRequestResponseFormatTypeText

	typStr := ChatFormatTextConfigType(typ)
	text.Type = typStr

	return ChatRequestResponseFormat{
		ChatFormatTextConfig: &text,
		Type:                 typ,
	}
}

func (u *ChatRequestResponseFormat) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "grammar":
		chatFormatGrammarConfig := new(ChatFormatGrammarConfig)
		if err := utils.UnmarshalJSON(data, &chatFormatGrammarConfig, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == grammar) type ChatFormatGrammarConfig within ChatRequestResponseFormat: %w", string(data), err)
		}

		u.ChatFormatGrammarConfig = chatFormatGrammarConfig
		u.Type = ChatRequestResponseFormatTypeGrammar
		return nil
	case "json_object":
		formatJSONObjectConfig := new(FormatJSONObjectConfig)
		if err := utils.UnmarshalJSON(data, &formatJSONObjectConfig, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == json_object) type FormatJSONObjectConfig within ChatRequestResponseFormat: %w", string(data), err)
		}

		u.FormatJSONObjectConfig = formatJSONObjectConfig
		u.Type = ChatRequestResponseFormatTypeJSONObject
		return nil
	case "json_schema":
		chatFormatJSONSchemaConfig := new(ChatFormatJSONSchemaConfig)
		if err := utils.UnmarshalJSON(data, &chatFormatJSONSchemaConfig, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == json_schema) type ChatFormatJSONSchemaConfig within ChatRequestResponseFormat: %w", string(data), err)
		}

		u.ChatFormatJSONSchemaConfig = chatFormatJSONSchemaConfig
		u.Type = ChatRequestResponseFormatTypeJSONSchema
		return nil
	case "python":
		chatFormatPythonConfig := new(ChatFormatPythonConfig)
		if err := utils.UnmarshalJSON(data, &chatFormatPythonConfig, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == python) type ChatFormatPythonConfig within ChatRequestResponseFormat: %w", string(data), err)
		}

		u.ChatFormatPythonConfig = chatFormatPythonConfig
		u.Type = ChatRequestResponseFormatTypePython
		return nil
	case "text":
		chatFormatTextConfig := new(ChatFormatTextConfig)
		if err := utils.UnmarshalJSON(data, &chatFormatTextConfig, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == text) type ChatFormatTextConfig within ChatRequestResponseFormat: %w", string(data), err)
		}

		u.ChatFormatTextConfig = chatFormatTextConfig
		u.Type = ChatRequestResponseFormatTypeText
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ChatRequestResponseFormat", string(data))
}

func (u ChatRequestResponseFormat) MarshalJSON() ([]byte, error) {
	if u.ChatFormatTextConfig != nil {
		return utils.MarshalJSON(u.ChatFormatTextConfig, "", true)
	}

	if u.FormatJSONObjectConfig != nil {
		return utils.MarshalJSON(u.FormatJSONObjectConfig, "", true)
	}

	if u.ChatFormatJSONSchemaConfig != nil {
		return utils.MarshalJSON(u.ChatFormatJSONSchemaConfig, "", true)
	}

	if u.ChatFormatGrammarConfig != nil {
		return utils.MarshalJSON(u.ChatFormatGrammarConfig, "", true)
	}

	if u.ChatFormatPythonConfig != nil {
		return utils.MarshalJSON(u.ChatFormatPythonConfig, "", true)
	}

	return nil, errors.New("could not marshal union type ChatRequestResponseFormat: all fields are null")
}

// ServiceTier - The service tier to use for processing this request.
type ServiceTier string

const (
	ServiceTierAuto     ServiceTier = "auto"
	ServiceTierDefault  ServiceTier = "default"
	ServiceTierFlex     ServiceTier = "flex"
	ServiceTierPriority ServiceTier = "priority"
	ServiceTierScale    ServiceTier = "scale"
)

func (e ServiceTier) ToPointer() *ServiceTier {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ServiceTier) IsExact() bool {
	if e != nil {
		switch *e {
		case "auto", "default", "flex", "priority", "scale":
			return true
		}
	}
	return false
}

type StopType string

const (
	StopTypeStr        StopType = "str"
	StopTypeArrayOfStr StopType = "arrayOfStr"
	StopTypeAny        StopType = "any"
)

// Stop sequences (up to 4)
type Stop struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`
	Any        any      `queryParam:"inline" union:"member"`

	Type StopType
}

func CreateStopStr(str string) Stop {
	typ := StopTypeStr

	return Stop{
		Str:  &str,
		Type: typ,
	}
}

func CreateStopArrayOfStr(arrayOfStr []string) Stop {
	typ := StopTypeArrayOfStr

	return Stop{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func CreateStopAny(anyT any) Stop {
	typ := StopTypeAny

	return Stop{
		Any:  anyT,
		Type: typ,
	}
}

func (u *Stop) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StopTypeStr,
			Value: &str,
		})
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StopTypeArrayOfStr,
			Value: arrayOfStr,
		})
	}

	var anyVar any = nil
	if err := utils.UnmarshalJSON(data, &anyVar, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StopTypeAny,
			Value: anyVar,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Stop", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Stop", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(StopType)
	switch best.Type {
	case StopTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case StopTypeArrayOfStr:
		u.ArrayOfStr = best.Value.([]string)
		return nil
	case StopTypeAny:
		u.Any = best.Value.(any)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Stop", string(data))
}

func (u Stop) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	if u.Any != nil {
		return utils.MarshalJSON(u.Any, "", true)
	}

	return nil, errors.New("could not marshal union type Stop: all fields are null")
}

// ChatRequest - Chat completion request parameters
type ChatRequest struct {
	// Enable automatic prompt caching. When set at the top level, the system automatically applies cache breakpoints to the last cacheable block in the request. Currently supported for Anthropic Claude models.
	CacheControl *AnthropicCacheControlDirective `json:"cache_control,omitzero"`
	// Debug options for inspecting request transformations (streaming only)
	Debug *ChatDebugOptions `json:"debug,omitzero"`
	// Frequency penalty (-2.0 to 2.0)
	FrequencyPenalty optionalnullable.OptionalNullable[float64] `json:"frequency_penalty,omitzero"`
	// Provider-specific image configuration options. Keys and values vary by model/provider. See https://openrouter.ai/docs/guides/overview/multimodal/image-generation for more details.
	ImageConfig map[string]ImageConfig `json:"image_config,omitzero"`
	// Token logit bias adjustments
	LogitBias optionalnullable.OptionalNullable[map[string]float64] `json:"logit_bias,omitzero"`
	// Return log probabilities
	Logprobs optionalnullable.OptionalNullable[bool] `json:"logprobs,omitzero"`
	// Maximum tokens in completion
	MaxCompletionTokens optionalnullable.OptionalNullable[int64] `json:"max_completion_tokens,omitzero"`
	// Maximum tokens (deprecated, use max_completion_tokens). Note: some providers enforce a minimum of 16.
	MaxTokens optionalnullable.OptionalNullable[int64] `json:"max_tokens,omitzero"`
	// List of messages for the conversation
	Messages []ChatMessages `json:"messages"`
	// Key-value pairs for additional object information (max 16 pairs, 64 char keys, 512 char values)
	Metadata map[string]string `json:"metadata,omitzero"`
	// Output modalities for the response. Supported values are "text", "image", and "audio".
	Modalities []Modalities `json:"modalities,omitzero"`
	// Model to use for completion
	Model *string `json:"model,omitzero"`
	// Models to use for completion
	Models []string `json:"models,omitzero"`
	// Whether to enable parallel function calling during tool use. When true, the model may generate multiple tool calls in a single response.
	ParallelToolCalls optionalnullable.OptionalNullable[bool] `json:"parallel_tool_calls,omitzero"`
	// Plugins you want to enable for this request, including their settings.
	Plugins []Plugins `json:"plugins,omitzero"`
	// Presence penalty (-2.0 to 2.0)
	PresencePenalty optionalnullable.OptionalNullable[float64] `json:"presence_penalty,omitzero"`
	// When multiple model providers are available, optionally indicate your routing preference.
	Provider optionalnullable.OptionalNullable[ProviderPreferences] `json:"provider,omitzero"`
	// Configuration options for reasoning models
	Reasoning *Reasoning `json:"reasoning,omitzero"`
	// Response format configuration
	ResponseFormat *ChatRequestResponseFormat `json:"response_format,omitzero"`
	// Random seed for deterministic outputs
	Seed optionalnullable.OptionalNullable[int64] `json:"seed,omitzero"`
	// The service tier to use for processing this request.
	ServiceTier optionalnullable.OptionalNullable[ServiceTier] `json:"service_tier,omitzero"`
	// A unique identifier for grouping related requests (e.g., a conversation or agent workflow) for observability. If provided in both the request body and the x-session-id header, the body value takes precedence. Maximum of 256 characters.
	SessionID *string `json:"session_id,omitzero"`
	// Stop sequences (up to 4)
	Stop optionalnullable.OptionalNullable[Stop] `json:"stop,omitzero"`
	// Stop conditions for the server-tool agent loop. Any condition firing halts the loop (OR logic). When set, this overrides `max_tool_calls`.
	StopServerToolsWhen []StopServerToolsWhenCondition `json:"stop_server_tools_when,omitzero"`
	// Enable streaming response
	Stream *bool `default:"false" json:"stream"`
	// Streaming configuration options
	StreamOptions optionalnullable.OptionalNullable[ChatStreamOptions] `json:"stream_options,omitzero"`
	// Sampling temperature (0-2)
	Temperature optionalnullable.OptionalNullable[float64] `json:"temperature,omitzero"`
	// Tool choice configuration
	ToolChoice *ChatToolChoice `json:"tool_choice,omitzero"`
	// Available tools for function calling
	Tools []ChatFunctionTool `json:"tools,omitzero"`
	// Number of top log probabilities to return (0-20)
	TopLogprobs optionalnullable.OptionalNullable[int64] `json:"top_logprobs,omitzero"`
	// Nucleus sampling parameter (0-1)
	TopP optionalnullable.OptionalNullable[float64] `json:"top_p,omitzero"`
	// Metadata for observability and tracing. Known keys (trace_id, trace_name, span_name, generation_name, parent_span_id) have special handling. Additional keys are passed through as custom metadata to configured broadcast destinations.
	Trace *TraceConfig `json:"trace,omitzero"`
	// Unique user identifier
	User *string `json:"user,omitzero"`
}

func (c ChatRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatRequest) GetCacheControl() *AnthropicCacheControlDirective {
	if c == nil {
		return nil
	}
	return c.CacheControl
}

func (c *ChatRequest) GetDebug() *ChatDebugOptions {
	if c == nil {
		return nil
	}
	return c.Debug
}

func (c *ChatRequest) GetFrequencyPenalty() optionalnullable.OptionalNullable[float64] {
	if c == nil {
		return nil
	}
	return c.FrequencyPenalty
}

func (c *ChatRequest) GetImageConfig() map[string]ImageConfig {
	if c == nil {
		return nil
	}
	return c.ImageConfig
}

func (c *ChatRequest) GetLogitBias() optionalnullable.OptionalNullable[map[string]float64] {
	if c == nil {
		return nil
	}
	return c.LogitBias
}

func (c *ChatRequest) GetLogprobs() optionalnullable.OptionalNullable[bool] {
	if c == nil {
		return nil
	}
	return c.Logprobs
}

func (c *ChatRequest) GetMaxCompletionTokens() optionalnullable.OptionalNullable[int64] {
	if c == nil {
		return nil
	}
	return c.MaxCompletionTokens
}

func (c *ChatRequest) GetMaxTokens() optionalnullable.OptionalNullable[int64] {
	if c == nil {
		return nil
	}
	return c.MaxTokens
}

func (c *ChatRequest) GetMessages() []ChatMessages {
	if c == nil {
		return []ChatMessages{}
	}
	return c.Messages
}

func (c *ChatRequest) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *ChatRequest) GetModalities() []Modalities {
	if c == nil {
		return nil
	}
	return c.Modalities
}

func (c *ChatRequest) GetModel() *string {
	if c == nil {
		return nil
	}
	return c.Model
}

func (c *ChatRequest) GetModels() []string {
	if c == nil {
		return nil
	}
	return c.Models
}

func (c *ChatRequest) GetParallelToolCalls() optionalnullable.OptionalNullable[bool] {
	if c == nil {
		return nil
	}
	return c.ParallelToolCalls
}

func (c *ChatRequest) GetPlugins() []Plugins {
	if c == nil {
		return nil
	}
	return c.Plugins
}

func (c *ChatRequest) GetPresencePenalty() optionalnullable.OptionalNullable[float64] {
	if c == nil {
		return nil
	}
	return c.PresencePenalty
}

func (c *ChatRequest) GetProvider() optionalnullable.OptionalNullable[ProviderPreferences] {
	if c == nil {
		return nil
	}
	return c.Provider
}

func (c *ChatRequest) GetReasoning() *Reasoning {
	if c == nil {
		return nil
	}
	return c.Reasoning
}

func (c *ChatRequest) GetResponseFormat() *ChatRequestResponseFormat {
	if c == nil {
		return nil
	}
	return c.ResponseFormat
}

func (c *ChatRequest) GetResponseFormatGrammar() *ChatFormatGrammarConfig {
	if v := c.GetResponseFormat(); v != nil {
		return v.ChatFormatGrammarConfig
	}
	return nil
}

func (c *ChatRequest) GetResponseFormatJSONObject() *FormatJSONObjectConfig {
	if v := c.GetResponseFormat(); v != nil {
		return v.FormatJSONObjectConfig
	}
	return nil
}

func (c *ChatRequest) GetResponseFormatJSONSchema() *ChatFormatJSONSchemaConfig {
	if v := c.GetResponseFormat(); v != nil {
		return v.ChatFormatJSONSchemaConfig
	}
	return nil
}

func (c *ChatRequest) GetResponseFormatPython() *ChatFormatPythonConfig {
	if v := c.GetResponseFormat(); v != nil {
		return v.ChatFormatPythonConfig
	}
	return nil
}

func (c *ChatRequest) GetResponseFormatText() *ChatFormatTextConfig {
	if v := c.GetResponseFormat(); v != nil {
		return v.ChatFormatTextConfig
	}
	return nil
}

func (c *ChatRequest) GetSeed() optionalnullable.OptionalNullable[int64] {
	if c == nil {
		return nil
	}
	return c.Seed
}

func (c *ChatRequest) GetServiceTier() optionalnullable.OptionalNullable[ServiceTier] {
	if c == nil {
		return nil
	}
	return c.ServiceTier
}

func (c *ChatRequest) GetSessionID() *string {
	if c == nil {
		return nil
	}
	return c.SessionID
}

func (c *ChatRequest) GetStop() optionalnullable.OptionalNullable[Stop] {
	if c == nil {
		return nil
	}
	return c.Stop
}

func (c *ChatRequest) GetStopServerToolsWhen() []StopServerToolsWhenCondition {
	if c == nil {
		return nil
	}
	return c.StopServerToolsWhen
}

func (c *ChatRequest) GetStream() *bool {
	if c == nil {
		return nil
	}
	return c.Stream
}

func (c *ChatRequest) GetStreamOptions() optionalnullable.OptionalNullable[ChatStreamOptions] {
	if c == nil {
		return nil
	}
	return c.StreamOptions
}

func (c *ChatRequest) GetTemperature() optionalnullable.OptionalNullable[float64] {
	if c == nil {
		return nil
	}
	return c.Temperature
}

func (c *ChatRequest) GetToolChoice() *ChatToolChoice {
	if c == nil {
		return nil
	}
	return c.ToolChoice
}

func (c *ChatRequest) GetTools() []ChatFunctionTool {
	if c == nil {
		return nil
	}
	return c.Tools
}

func (c *ChatRequest) GetTopLogprobs() optionalnullable.OptionalNullable[int64] {
	if c == nil {
		return nil
	}
	return c.TopLogprobs
}

func (c *ChatRequest) GetTopP() optionalnullable.OptionalNullable[float64] {
	if c == nil {
		return nil
	}
	return c.TopP
}

func (c *ChatRequest) GetTrace() *TraceConfig {
	if c == nil {
		return nil
	}
	return c.Trace
}

func (c *ChatRequest) GetUser() *string {
	if c == nil {
		return nil
	}
	return c.User
}
