// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type ChatContentAudioInputAudio struct {
	// Base64 encoded audio data
	Data string `json:"data"`
	// Audio format (e.g., wav, mp3, flac, m4a, ogg, aiff, aac, pcm16, pcm24). Supported formats vary by provider.
	Format string `json:"format"`
}

func (c ChatContentAudioInputAudio) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatContentAudioInputAudio) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatContentAudioInputAudio) GetData() string {
	if c == nil {
		return ""
	}
	return c.Data
}

func (c *ChatContentAudioInputAudio) GetFormat() string {
	if c == nil {
		return ""
	}
	return c.Format
}

type ChatContentAudioType string

const (
	ChatContentAudioTypeInputAudio ChatContentAudioType = "input_audio"
)

func (e ChatContentAudioType) ToPointer() *ChatContentAudioType {
	return &e
}
func (e *ChatContentAudioType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "input_audio":
		*e = ChatContentAudioType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChatContentAudioType: %v", v)
	}
}

// ChatContentAudio - Audio input content part. Supported audio formats vary by provider.
type ChatContentAudio struct {
	InputAudio ChatContentAudioInputAudio `json:"input_audio"`
	Type       ChatContentAudioType       `json:"type"`
}

func (c ChatContentAudio) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatContentAudio) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatContentAudio) GetInputAudio() ChatContentAudioInputAudio {
	if c == nil {
		return ChatContentAudioInputAudio{}
	}
	return c.InputAudio
}

func (c *ChatContentAudio) GetType() ChatContentAudioType {
	if c == nil {
		return ChatContentAudioType("")
	}
	return c.Type
}
