// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type ChatContentCacheControlType string

const (
	ChatContentCacheControlTypeEphemeral ChatContentCacheControlType = "ephemeral"
)

func (e ChatContentCacheControlType) ToPointer() *ChatContentCacheControlType {
	return &e
}
func (e *ChatContentCacheControlType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ephemeral":
		*e = ChatContentCacheControlType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChatContentCacheControlType: %v", v)
	}
}

// ChatContentCacheControl - Cache control for the content part
type ChatContentCacheControl struct {
	TTL  *AnthropicCacheControlTTL   `json:"ttl,omitzero"`
	Type ChatContentCacheControlType `json:"type"`
}

func (c ChatContentCacheControl) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatContentCacheControl) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatContentCacheControl) GetTTL() *AnthropicCacheControlTTL {
	if c == nil {
		return nil
	}
	return c.TTL
}

func (c *ChatContentCacheControl) GetType() ChatContentCacheControlType {
	if c == nil {
		return ChatContentCacheControlType("")
	}
	return c.Type
}
