// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type CodexLocalShellToolType string

const (
	CodexLocalShellToolTypeLocalShell CodexLocalShellToolType = "local_shell"
)

func (e CodexLocalShellToolType) ToPointer() *CodexLocalShellToolType {
	return &e
}
func (e *CodexLocalShellToolType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "local_shell":
		*e = CodexLocalShellToolType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CodexLocalShellToolType: %v", v)
	}
}

// CodexLocalShellTool - Local shell tool configuration
type CodexLocalShellTool struct {
	Type CodexLocalShellToolType `json:"type"`
}

func (c CodexLocalShellTool) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CodexLocalShellTool) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CodexLocalShellTool) GetType() CodexLocalShellToolType {
	if c == nil {
		return CodexLocalShellToolType("")
	}
	return c.Type
}
