// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/optionalnullable"
)

// ContentFilterEntry - A custom regex content filter that scans request messages for matching patterns.
type ContentFilterEntry struct {
	// Action taken when the pattern matches
	Action ContentFilterAction `json:"action"`
	// Optional label used in redaction placeholders or error messages
	Label optionalnullable.OptionalNullable[string] `json:"label,omitzero"`
	// A regex pattern to match against request content
	Pattern string `json:"pattern"`
}

func (c *ContentFilterEntry) GetAction() ContentFilterAction {
	if c == nil {
		return ContentFilterAction("")
	}
	return c.Action
}

func (c *ContentFilterEntry) GetLabel() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Label
}

func (c *ContentFilterEntry) GetPattern() string {
	if c == nil {
		return ""
	}
	return c.Pattern
}
