// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ContentFilterBuiltinSlug - The builtin filter identifier
type ContentFilterBuiltinSlug string

const (
	ContentFilterBuiltinSlugEmail                ContentFilterBuiltinSlug = "email"
	ContentFilterBuiltinSlugPhone                ContentFilterBuiltinSlug = "phone"
	ContentFilterBuiltinSlugSsn                  ContentFilterBuiltinSlug = "ssn"
	ContentFilterBuiltinSlugCreditCard           ContentFilterBuiltinSlug = "credit-card"
	ContentFilterBuiltinSlugIPAddress            ContentFilterBuiltinSlug = "ip-address"
	ContentFilterBuiltinSlugPersonName           ContentFilterBuiltinSlug = "person-name"
	ContentFilterBuiltinSlugAddress              ContentFilterBuiltinSlug = "address"
	ContentFilterBuiltinSlugRegexPromptInjection ContentFilterBuiltinSlug = "regex-prompt-injection"
)

func (e ContentFilterBuiltinSlug) ToPointer() *ContentFilterBuiltinSlug {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ContentFilterBuiltinSlug) IsExact() bool {
	if e != nil {
		switch *e {
		case "email", "phone", "ssn", "credit-card", "ip-address", "person-name", "address", "regex-prompt-injection":
			return true
		}
	}
	return false
}
