// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type ContentPartInputFileType string

const (
	ContentPartInputFileTypeInputFile ContentPartInputFileType = "input_file"
)

func (e ContentPartInputFileType) ToPointer() *ContentPartInputFileType {
	return &e
}
func (e *ContentPartInputFileType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "input_file":
		*e = ContentPartInputFileType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ContentPartInputFileType: %v", v)
	}
}

type ContentPartInputFile struct {
	InputFile MultimodalMedia          `json:"input_file"`
	Type      ContentPartInputFileType `json:"type"`
}

func (c ContentPartInputFile) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContentPartInputFile) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContentPartInputFile) GetInputFile() MultimodalMedia {
	if c == nil {
		return MultimodalMedia{}
	}
	return c.InputFile
}

func (c *ContentPartInputFile) GetType() ContentPartInputFileType {
	if c == nil {
		return ContentPartInputFileType("")
	}
	return c.Type
}
