// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type ContextCompressionPluginID string

const (
	ContextCompressionPluginIDContextCompression ContextCompressionPluginID = "context-compression"
)

func (e ContextCompressionPluginID) ToPointer() *ContextCompressionPluginID {
	return &e
}
func (e *ContextCompressionPluginID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "context-compression":
		*e = ContextCompressionPluginID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ContextCompressionPluginID: %v", v)
	}
}

type ContextCompressionPlugin struct {
	// Set to false to disable the context-compression plugin for this request. Defaults to true.
	Enabled *bool `json:"enabled,omitzero"`
	// The compression engine to use. Defaults to "middle-out".
	Engine *ContextCompressionEngine  `json:"engine,omitzero"`
	ID     ContextCompressionPluginID `json:"id"`
}

func (c ContextCompressionPlugin) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContextCompressionPlugin) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContextCompressionPlugin) GetEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.Enabled
}

func (c *ContextCompressionPlugin) GetEngine() *ContextCompressionEngine {
	if c == nil {
		return nil
	}
	return c.Engine
}

func (c *ContextCompressionPlugin) GetID() ContextCompressionPluginID {
	if c == nil {
		return ContextCompressionPluginID("")
	}
	return c.ID
}
