// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/optionalnullable"
)

// CostDetails - Breakdown of upstream inference costs
type CostDetails struct {
	UpstreamInferenceCompletionsCost float64                                    `json:"upstream_inference_completions_cost"`
	UpstreamInferenceCost            optionalnullable.OptionalNullable[float64] `json:"upstream_inference_cost,omitzero"`
	UpstreamInferencePromptCost      float64                                    `json:"upstream_inference_prompt_cost"`
}

func (c *CostDetails) GetUpstreamInferenceCompletionsCost() float64 {
	if c == nil {
		return 0.0
	}
	return c.UpstreamInferenceCompletionsCost
}

func (c *CostDetails) GetUpstreamInferenceCost() optionalnullable.OptionalNullable[float64] {
	if c == nil {
		return nil
	}
	return c.UpstreamInferenceCost
}

func (c *CostDetails) GetUpstreamInferencePromptCost() float64 {
	if c == nil {
		return 0.0
	}
	return c.UpstreamInferencePromptCost
}
