// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/optionalnullable"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type CustomToolCallOutputItem2Detail string

const (
	CustomToolCallOutputItem2DetailAuto     CustomToolCallOutputItem2Detail = "auto"
	CustomToolCallOutputItem2DetailHigh     CustomToolCallOutputItem2Detail = "high"
	CustomToolCallOutputItem2DetailLow      CustomToolCallOutputItem2Detail = "low"
	CustomToolCallOutputItem2DetailOriginal CustomToolCallOutputItem2Detail = "original"
)

func (e CustomToolCallOutputItem2Detail) ToPointer() *CustomToolCallOutputItem2Detail {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CustomToolCallOutputItem2Detail) IsExact() bool {
	if e != nil {
		switch *e {
		case "auto", "high", "low", "original":
			return true
		}
	}
	return false
}

type CustomToolCallOutputItem2Type string

const (
	CustomToolCallOutputItem2TypeInputImage CustomToolCallOutputItem2Type = "input_image"
)

func (e CustomToolCallOutputItem2Type) ToPointer() *CustomToolCallOutputItem2Type {
	return &e
}
func (e *CustomToolCallOutputItem2Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "input_image":
		*e = CustomToolCallOutputItem2Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CustomToolCallOutputItem2Type: %v", v)
	}
}

// CustomToolCallOutputItem22 - Image input content item
type CustomToolCallOutputItem22 struct {
	Detail   CustomToolCallOutputItem2Detail           `json:"detail"`
	ImageURL optionalnullable.OptionalNullable[string] `json:"image_url,omitzero"`
	Type     CustomToolCallOutputItem2Type             `json:"type"`
}

func (c CustomToolCallOutputItem22) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomToolCallOutputItem22) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CustomToolCallOutputItem22) GetDetail() CustomToolCallOutputItem2Detail {
	if c == nil {
		return CustomToolCallOutputItem2Detail("")
	}
	return c.Detail
}

func (c *CustomToolCallOutputItem22) GetImageURL() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.ImageURL
}

func (c *CustomToolCallOutputItem22) GetType() CustomToolCallOutputItem2Type {
	if c == nil {
		return CustomToolCallOutputItem2Type("")
	}
	return c.Type
}

// #region class-body-customtoolcalloutputitem22
// #endregion class-body-customtoolcalloutputitem22

type CustomToolCallOutputItemOutput2Type string

const (
	CustomToolCallOutputItemOutput2TypeInputText  CustomToolCallOutputItemOutput2Type = "input_text"
	CustomToolCallOutputItemOutput2TypeInputImage CustomToolCallOutputItemOutput2Type = "input_image"
	CustomToolCallOutputItemOutput2TypeInputFile  CustomToolCallOutputItemOutput2Type = "input_file"
)

type CustomToolCallOutputItemOutput2 struct {
	InputText                  *InputText                  `queryParam:"inline" union:"member"`
	CustomToolCallOutputItem22 *CustomToolCallOutputItem22 `queryParam:"inline" union:"member"`
	InputFile                  *InputFile                  `queryParam:"inline" union:"member"`

	Type CustomToolCallOutputItemOutput2Type
}

func CreateCustomToolCallOutputItemOutput2InputText(inputText InputText) CustomToolCallOutputItemOutput2 {
	typ := CustomToolCallOutputItemOutput2TypeInputText

	typStr := InputTextType(typ)
	inputText.Type = typStr

	return CustomToolCallOutputItemOutput2{
		InputText: &inputText,
		Type:      typ,
	}
}

func CreateCustomToolCallOutputItemOutput2InputImage(inputImage CustomToolCallOutputItem22) CustomToolCallOutputItemOutput2 {
	typ := CustomToolCallOutputItemOutput2TypeInputImage

	typStr := CustomToolCallOutputItem2Type(typ)
	inputImage.Type = typStr

	return CustomToolCallOutputItemOutput2{
		CustomToolCallOutputItem22: &inputImage,
		Type:                       typ,
	}
}

func CreateCustomToolCallOutputItemOutput2InputFile(inputFile InputFile) CustomToolCallOutputItemOutput2 {
	typ := CustomToolCallOutputItemOutput2TypeInputFile

	typStr := InputFileType(typ)
	inputFile.Type = typStr

	return CustomToolCallOutputItemOutput2{
		InputFile: &inputFile,
		Type:      typ,
	}
}

func (u *CustomToolCallOutputItemOutput2) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "input_text":
		inputText := new(InputText)
		if err := utils.UnmarshalJSON(data, &inputText, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == input_text) type InputText within CustomToolCallOutputItemOutput2: %w", string(data), err)
		}

		u.InputText = inputText
		u.Type = CustomToolCallOutputItemOutput2TypeInputText
		return nil
	case "input_image":
		customToolCallOutputItem22 := new(CustomToolCallOutputItem22)
		if err := utils.UnmarshalJSON(data, &customToolCallOutputItem22, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == input_image) type CustomToolCallOutputItem22 within CustomToolCallOutputItemOutput2: %w", string(data), err)
		}

		u.CustomToolCallOutputItem22 = customToolCallOutputItem22
		u.Type = CustomToolCallOutputItemOutput2TypeInputImage
		return nil
	case "input_file":
		inputFile := new(InputFile)
		if err := utils.UnmarshalJSON(data, &inputFile, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == input_file) type InputFile within CustomToolCallOutputItemOutput2: %w", string(data), err)
		}

		u.InputFile = inputFile
		u.Type = CustomToolCallOutputItemOutput2TypeInputFile
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CustomToolCallOutputItemOutput2", string(data))
}

func (u CustomToolCallOutputItemOutput2) MarshalJSON() ([]byte, error) {
	if u.InputText != nil {
		return utils.MarshalJSON(u.InputText, "", true)
	}

	if u.CustomToolCallOutputItem22 != nil {
		return utils.MarshalJSON(u.CustomToolCallOutputItem22, "", true)
	}

	if u.InputFile != nil {
		return utils.MarshalJSON(u.InputFile, "", true)
	}

	return nil, errors.New("could not marshal union type CustomToolCallOutputItemOutput2: all fields are null")
}

type CustomToolCallOutputItemOutputType string

const (
	CustomToolCallOutputItemOutputTypeStr                                    CustomToolCallOutputItemOutputType = "str"
	CustomToolCallOutputItemOutputTypeArrayOfCustomToolCallOutputItemOutput2 CustomToolCallOutputItemOutputType = "arrayOfCustomToolCallOutputItemOutput2"
)

type CustomToolCallOutputItemOutput struct {
	Str                                    *string                           `queryParam:"inline" union:"member"`
	ArrayOfCustomToolCallOutputItemOutput2 []CustomToolCallOutputItemOutput2 `queryParam:"inline" union:"member"`

	Type CustomToolCallOutputItemOutputType
}

func CreateCustomToolCallOutputItemOutputStr(str string) CustomToolCallOutputItemOutput {
	typ := CustomToolCallOutputItemOutputTypeStr

	return CustomToolCallOutputItemOutput{
		Str:  &str,
		Type: typ,
	}
}

func CreateCustomToolCallOutputItemOutputArrayOfCustomToolCallOutputItemOutput2(arrayOfCustomToolCallOutputItemOutput2 []CustomToolCallOutputItemOutput2) CustomToolCallOutputItemOutput {
	typ := CustomToolCallOutputItemOutputTypeArrayOfCustomToolCallOutputItemOutput2

	return CustomToolCallOutputItemOutput{
		ArrayOfCustomToolCallOutputItemOutput2: arrayOfCustomToolCallOutputItemOutput2,
		Type:                                   typ,
	}
}

func (u *CustomToolCallOutputItemOutput) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  CustomToolCallOutputItemOutputTypeStr,
			Value: &str,
		})
	}

	var arrayOfCustomToolCallOutputItemOutput2 []CustomToolCallOutputItemOutput2 = []CustomToolCallOutputItemOutput2{}
	if err := utils.UnmarshalJSON(data, &arrayOfCustomToolCallOutputItemOutput2, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  CustomToolCallOutputItemOutputTypeArrayOfCustomToolCallOutputItemOutput2,
			Value: arrayOfCustomToolCallOutputItemOutput2,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for CustomToolCallOutputItemOutput", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for CustomToolCallOutputItemOutput", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(CustomToolCallOutputItemOutputType)
	switch best.Type {
	case CustomToolCallOutputItemOutputTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case CustomToolCallOutputItemOutputTypeArrayOfCustomToolCallOutputItemOutput2:
		u.ArrayOfCustomToolCallOutputItemOutput2 = best.Value.([]CustomToolCallOutputItemOutput2)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CustomToolCallOutputItemOutput", string(data))
}

func (u CustomToolCallOutputItemOutput) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfCustomToolCallOutputItemOutput2 != nil {
		return utils.MarshalJSON(u.ArrayOfCustomToolCallOutputItemOutput2, "", true)
	}

	return nil, errors.New("could not marshal union type CustomToolCallOutputItemOutput: all fields are null")
}

type CustomToolCallOutputItemType string

const (
	CustomToolCallOutputItemTypeCustomToolCallOutput CustomToolCallOutputItemType = "custom_tool_call_output"
)

func (e CustomToolCallOutputItemType) ToPointer() *CustomToolCallOutputItemType {
	return &e
}
func (e *CustomToolCallOutputItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "custom_tool_call_output":
		*e = CustomToolCallOutputItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CustomToolCallOutputItemType: %v", v)
	}
}

// CustomToolCallOutputItem - The output from a custom (freeform-grammar) tool call execution. Mirrors `function_call_output` but is matched to a `custom_tool_call` rather than a `function_call`.
type CustomToolCallOutputItem struct {
	CallID string                         `json:"call_id"`
	ID     *string                        `json:"id,omitzero"`
	Output CustomToolCallOutputItemOutput `json:"output"`
	Type   CustomToolCallOutputItemType   `json:"type"`
}

func (c CustomToolCallOutputItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomToolCallOutputItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CustomToolCallOutputItem) GetCallID() string {
	if c == nil {
		return ""
	}
	return c.CallID
}

func (c *CustomToolCallOutputItem) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CustomToolCallOutputItem) GetOutput() CustomToolCallOutputItemOutput {
	if c == nil {
		return CustomToolCallOutputItemOutput{}
	}
	return c.Output
}

func (c *CustomToolCallOutputItem) GetType() CustomToolCallOutputItemType {
	if c == nil {
		return CustomToolCallOutputItemType("")
	}
	return c.Type
}
