// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type DeleteWorkspaceResponse struct {
	// Confirmation that the workspace was deleted
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	deleted bool `const:"true" json:"deleted"`
}

func (d DeleteWorkspaceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteWorkspaceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteWorkspaceResponse) GetDeleted() bool {
	return true
}
