// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type EndpointsMetadata struct {
	Available []EndpointInfo `json:"available"`
	Total     int64          `json:"total"`
}

func (e EndpointsMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EndpointsMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EndpointsMetadata) GetAvailable() []EndpointInfo {
	if e == nil {
		return []EndpointInfo{}
	}
	return e.Available
}

func (e *EndpointsMetadata) GetTotal() int64 {
	if e == nil {
		return 0
	}
	return e.Total
}
