// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type EndpointInfo struct {
	Model    string `json:"model"`
	Provider string `json:"provider"`
	Selected bool   `json:"selected"`
}

func (e EndpointInfo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EndpointInfo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EndpointInfo) GetModel() string {
	if e == nil {
		return ""
	}
	return e.Model
}

func (e *EndpointInfo) GetProvider() string {
	if e == nil {
		return ""
	}
	return e.Provider
}

func (e *EndpointInfo) GetSelected() bool {
	if e == nil {
		return false
	}
	return e.Selected
}
