// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type FormatJSONObjectConfigType string

const (
	FormatJSONObjectConfigTypeJSONObject FormatJSONObjectConfigType = "json_object"
)

func (e FormatJSONObjectConfigType) ToPointer() *FormatJSONObjectConfigType {
	return &e
}
func (e *FormatJSONObjectConfigType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "json_object":
		*e = FormatJSONObjectConfigType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FormatJSONObjectConfigType: %v", v)
	}
}

// FormatJSONObjectConfig - JSON object response format
type FormatJSONObjectConfig struct {
	Type FormatJSONObjectConfigType `json:"type"`
}

func (f FormatJSONObjectConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FormatJSONObjectConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FormatJSONObjectConfig) GetType() FormatJSONObjectConfigType {
	if f == nil {
		return FormatJSONObjectConfigType("")
	}
	return f.Type
}
