// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type FunctionCallItemType string

const (
	FunctionCallItemTypeFunctionCall FunctionCallItemType = "function_call"
)

func (e FunctionCallItemType) ToPointer() *FunctionCallItemType {
	return &e
}
func (e *FunctionCallItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "function_call":
		*e = FunctionCallItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FunctionCallItemType: %v", v)
	}
}

// FunctionCallItem - A function call initiated by the model
type FunctionCallItem struct {
	Arguments string `json:"arguments"`
	CallID    string `json:"call_id"`
	ID        string `json:"id"`
	Name      string `json:"name"`
	// Namespace qualifier for tools registered as part of a namespace tool group (e.g. an MCP server)
	Namespace *string              `json:"namespace,omitzero"`
	Status    *ToolCallStatus      `json:"status,omitzero"`
	Type      FunctionCallItemType `json:"type"`
}

func (f FunctionCallItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FunctionCallItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FunctionCallItem) GetArguments() string {
	if f == nil {
		return ""
	}
	return f.Arguments
}

func (f *FunctionCallItem) GetCallID() string {
	if f == nil {
		return ""
	}
	return f.CallID
}

func (f *FunctionCallItem) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *FunctionCallItem) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}

func (f *FunctionCallItem) GetNamespace() *string {
	if f == nil {
		return nil
	}
	return f.Namespace
}

func (f *FunctionCallItem) GetStatus() *ToolCallStatus {
	if f == nil {
		return nil
	}
	return f.Status
}

func (f *FunctionCallItem) GetType() FunctionCallItemType {
	if f == nil {
		return FunctionCallItemType("")
	}
	return f.Type
}
