// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type FunctionCallArgsDeltaEventType string

const (
	FunctionCallArgsDeltaEventTypeResponseFunctionCallArgumentsDelta FunctionCallArgsDeltaEventType = "response.function_call_arguments.delta"
)

func (e FunctionCallArgsDeltaEventType) ToPointer() *FunctionCallArgsDeltaEventType {
	return &e
}
func (e *FunctionCallArgsDeltaEventType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "response.function_call_arguments.delta":
		*e = FunctionCallArgsDeltaEventType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FunctionCallArgsDeltaEventType: %v", v)
	}
}

// FunctionCallArgsDeltaEvent - Event emitted when function call arguments are being streamed
type FunctionCallArgsDeltaEvent struct {
	Delta          string                         `json:"delta"`
	ItemID         string                         `json:"item_id"`
	OutputIndex    int64                          `json:"output_index"`
	SequenceNumber int64                          `json:"sequence_number"`
	Type           FunctionCallArgsDeltaEventType `json:"type"`
}

func (f FunctionCallArgsDeltaEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FunctionCallArgsDeltaEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FunctionCallArgsDeltaEvent) GetDelta() string {
	if f == nil {
		return ""
	}
	return f.Delta
}

func (f *FunctionCallArgsDeltaEvent) GetItemID() string {
	if f == nil {
		return ""
	}
	return f.ItemID
}

func (f *FunctionCallArgsDeltaEvent) GetOutputIndex() int64 {
	if f == nil {
		return 0
	}
	return f.OutputIndex
}

func (f *FunctionCallArgsDeltaEvent) GetSequenceNumber() int64 {
	if f == nil {
		return 0
	}
	return f.SequenceNumber
}

func (f *FunctionCallArgsDeltaEvent) GetType() FunctionCallArgsDeltaEventType {
	if f == nil {
		return FunctionCallArgsDeltaEventType("")
	}
	return f.Type
}
