// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GenerationContentResponse - Stored prompt and completion content for a generation
type GenerationContentResponse struct {
	// Stored prompt and completion content
	Data GenerationContentData `json:"data"`
}

func (g *GenerationContentResponse) GetData() GenerationContentData {
	if g == nil {
		return GenerationContentData{}
	}
	return g.Data
}
