// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetWorkspaceResponse struct {
	Data Workspace `json:"data"`
}

func (g *GetWorkspaceResponse) GetData() Workspace {
	if g == nil {
		return Workspace{}
	}
	return g.Data
}
