// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type ImageGenCallCompletedEventType string

const (
	ImageGenCallCompletedEventTypeResponseImageGenerationCallCompleted ImageGenCallCompletedEventType = "response.image_generation_call.completed"
)

func (e ImageGenCallCompletedEventType) ToPointer() *ImageGenCallCompletedEventType {
	return &e
}
func (e *ImageGenCallCompletedEventType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "response.image_generation_call.completed":
		*e = ImageGenCallCompletedEventType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ImageGenCallCompletedEventType: %v", v)
	}
}

// ImageGenCallCompletedEvent - Image generation call completed
type ImageGenCallCompletedEvent struct {
	ItemID         string                         `json:"item_id"`
	OutputIndex    int64                          `json:"output_index"`
	SequenceNumber int64                          `json:"sequence_number"`
	Type           ImageGenCallCompletedEventType `json:"type"`
}

func (i ImageGenCallCompletedEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ImageGenCallCompletedEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *ImageGenCallCompletedEvent) GetItemID() string {
	if i == nil {
		return ""
	}
	return i.ItemID
}

func (i *ImageGenCallCompletedEvent) GetOutputIndex() int64 {
	if i == nil {
		return 0
	}
	return i.OutputIndex
}

func (i *ImageGenCallCompletedEvent) GetSequenceNumber() int64 {
	if i == nil {
		return 0
	}
	return i.SequenceNumber
}

func (i *ImageGenCallCompletedEvent) GetType() ImageGenCallCompletedEventType {
	if i == nil {
		return ImageGenCallCompletedEventType("")
	}
	return i.Type
}
