// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/optionalnullable"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type InputFileType string

const (
	InputFileTypeInputFile InputFileType = "input_file"
)

func (e InputFileType) ToPointer() *InputFileType {
	return &e
}
func (e *InputFileType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "input_file":
		*e = InputFileType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputFileType: %v", v)
	}
}

// InputFile - File input content item
type InputFile struct {
	FileData *string                                   `json:"file_data,omitzero"`
	FileID   optionalnullable.OptionalNullable[string] `json:"file_id,omitzero"`
	FileURL  *string                                   `json:"file_url,omitzero"`
	Filename *string                                   `json:"filename,omitzero"`
	Type     InputFileType                             `json:"type"`
}

func (i InputFile) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputFile) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InputFile) GetFileData() *string {
	if i == nil {
		return nil
	}
	return i.FileData
}

func (i *InputFile) GetFileID() optionalnullable.OptionalNullable[string] {
	if i == nil {
		return nil
	}
	return i.FileID
}

func (i *InputFile) GetFileURL() *string {
	if i == nil {
		return nil
	}
	return i.FileURL
}

func (i *InputFile) GetFilename() *string {
	if i == nil {
		return nil
	}
	return i.Filename
}

func (i *InputFile) GetType() InputFileType {
	if i == nil {
		return InputFileType("")
	}
	return i.Type
}
