// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type InputTextType string

const (
	InputTextTypeInputText InputTextType = "input_text"
)

func (e InputTextType) ToPointer() *InputTextType {
	return &e
}
func (e *InputTextType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "input_text":
		*e = InputTextType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputTextType: %v", v)
	}
}

// InputText - Text input content item
type InputText struct {
	Text string        `json:"text"`
	Type InputTextType `json:"type"`
}

func (i InputText) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputText) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InputText) GetText() string {
	if i == nil {
		return ""
	}
	return i.Text
}

func (i *InputText) GetType() InputTextType {
	if i == nil {
		return InputTextType("")
	}
	return i.Type
}
