// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type LegacyChatContentVideoType string

const (
	LegacyChatContentVideoTypeInputVideo LegacyChatContentVideoType = "input_video"
)

func (e LegacyChatContentVideoType) ToPointer() *LegacyChatContentVideoType {
	return &e
}
func (e *LegacyChatContentVideoType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "input_video":
		*e = LegacyChatContentVideoType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LegacyChatContentVideoType: %v", v)
	}
}

// LegacyChatContentVideo - Video input content part (legacy format - deprecated)
//
// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
type LegacyChatContentVideo struct {
	Type LegacyChatContentVideoType `json:"type"`
	// Video input object
	VideoURL ChatContentVideoInput `json:"video_url"`
}

func (l LegacyChatContentVideo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LegacyChatContentVideo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LegacyChatContentVideo) GetType() LegacyChatContentVideoType {
	if l == nil {
		return LegacyChatContentVideoType("")
	}
	return l.Type
}

func (l *LegacyChatContentVideo) GetVideoURL() ChatContentVideoInput {
	if l == nil {
		return ChatContentVideoInput{}
	}
	return l.VideoURL
}
