// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListWorkspacesResponse struct {
	// List of workspaces
	Data []Workspace `json:"data"`
	// Total number of workspaces
	TotalCount int64 `json:"total_count"`
}

func (l *ListWorkspacesResponse) GetData() []Workspace {
	if l == nil {
		return []Workspace{}
	}
	return l.Data
}

func (l *ListWorkspacesResponse) GetTotalCount() int64 {
	if l == nil {
		return 0
	}
	return l.TotalCount
}
