// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type McpApprovalRequestItemType string

const (
	McpApprovalRequestItemTypeMcpApprovalRequest McpApprovalRequestItemType = "mcp_approval_request"
)

func (e McpApprovalRequestItemType) ToPointer() *McpApprovalRequestItemType {
	return &e
}
func (e *McpApprovalRequestItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "mcp_approval_request":
		*e = McpApprovalRequestItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for McpApprovalRequestItemType: %v", v)
	}
}

// McpApprovalRequestItem - Request for approval to execute an MCP tool
type McpApprovalRequestItem struct {
	Arguments   string                     `json:"arguments"`
	ID          string                     `json:"id"`
	Name        string                     `json:"name"`
	ServerLabel string                     `json:"server_label"`
	Type        McpApprovalRequestItemType `json:"type"`
}

func (m McpApprovalRequestItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *McpApprovalRequestItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *McpApprovalRequestItem) GetArguments() string {
	if m == nil {
		return ""
	}
	return m.Arguments
}

func (m *McpApprovalRequestItem) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

func (m *McpApprovalRequestItem) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *McpApprovalRequestItem) GetServerLabel() string {
	if m == nil {
		return ""
	}
	return m.ServerLabel
}

func (m *McpApprovalRequestItem) GetType() McpApprovalRequestItemType {
	if m == nil {
		return McpApprovalRequestItemType("")
	}
	return m.Type
}
