// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// MetadataLevel - Opt-in level for surfacing routing metadata on the response under `openrouter_metadata`.
type MetadataLevel string

const (
	MetadataLevelDisabled MetadataLevel = "disabled"
	MetadataLevelEnabled  MetadataLevel = "enabled"
)

func (e MetadataLevel) ToPointer() *MetadataLevel {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *MetadataLevel) IsExact() bool {
	if e != nil {
		switch *e {
		case "disabled", "enabled":
			return true
		}
	}
	return false
}
