// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type Method string

const (
	MethodPost Method = "POST"
	MethodPut  Method = "PUT"
)

func (e Method) ToPointer() *Method {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Method) IsExact() bool {
	if e != nil {
		switch *e {
		case "POST", "PUT":
			return true
		}
	}
	return false
}

type ObservabilityWebhookDestinationConfig struct {
	Headers map[string]string `json:"headers,omitzero"`
	Method  *Method           `default:"POST" json:"method"`
	URL     string            `json:"url"`
}

func (o ObservabilityWebhookDestinationConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *ObservabilityWebhookDestinationConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ObservabilityWebhookDestinationConfig) GetHeaders() map[string]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *ObservabilityWebhookDestinationConfig) GetMethod() *Method {
	if o == nil {
		return nil
	}
	return o.Method
}

func (o *ObservabilityWebhookDestinationConfig) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

type ObservabilityWebhookDestinationType string

const (
	ObservabilityWebhookDestinationTypeWebhook ObservabilityWebhookDestinationType = "webhook"
)

func (e ObservabilityWebhookDestinationType) ToPointer() *ObservabilityWebhookDestinationType {
	return &e
}
func (e *ObservabilityWebhookDestinationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "webhook":
		*e = ObservabilityWebhookDestinationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ObservabilityWebhookDestinationType: %v", v)
	}
}

type ObservabilityWebhookDestination struct {
	// Optional allowlist of OpenRouter API key hashes (`api_keys.hash`) whose traffic is forwarded to this destination. `null` means all keys.
	APIKeyHashes []string                              `json:"api_key_hashes"`
	Config       ObservabilityWebhookDestinationConfig `json:"config"`
	// ISO timestamp of when the destination was created.
	CreatedAt string `json:"created_at"`
	// Whether this destination is currently enabled.
	Enabled bool `json:"enabled"`
	// Optional structured filter rules controlling which events are forwarded.
	FilterRules *ObservabilityFilterRulesConfig `json:"filter_rules"`
	// Stable public identifier for this destination.
	ID string `json:"id"`
	// Human-readable name for the destination.
	Name *string `json:"name"`
	// When true, request/response bodies are not forwarded to this destination — only metadata.
	PrivacyMode bool `json:"privacy_mode"`
	// Sampling rate for events sent to this destination, between 0 and 1 (1 = 100%).
	SamplingRate float64                             `json:"sampling_rate"`
	Type         ObservabilityWebhookDestinationType `json:"type"`
	// ISO timestamp of when the destination was last updated.
	UpdatedAt string `json:"updated_at"`
	// ID of the workspace this destination belongs to.
	WorkspaceID string `json:"workspace_id"`
}

func (o ObservabilityWebhookDestination) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *ObservabilityWebhookDestination) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ObservabilityWebhookDestination) GetAPIKeyHashes() []string {
	if o == nil {
		return nil
	}
	return o.APIKeyHashes
}

func (o *ObservabilityWebhookDestination) GetConfig() ObservabilityWebhookDestinationConfig {
	if o == nil {
		return ObservabilityWebhookDestinationConfig{}
	}
	return o.Config
}

func (o *ObservabilityWebhookDestination) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *ObservabilityWebhookDestination) GetEnabled() bool {
	if o == nil {
		return false
	}
	return o.Enabled
}

func (o *ObservabilityWebhookDestination) GetFilterRules() *ObservabilityFilterRulesConfig {
	if o == nil {
		return nil
	}
	return o.FilterRules
}

func (o *ObservabilityWebhookDestination) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ObservabilityWebhookDestination) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ObservabilityWebhookDestination) GetPrivacyMode() bool {
	if o == nil {
		return false
	}
	return o.PrivacyMode
}

func (o *ObservabilityWebhookDestination) GetSamplingRate() float64 {
	if o == nil {
		return 0.0
	}
	return o.SamplingRate
}

func (o *ObservabilityWebhookDestination) GetType() ObservabilityWebhookDestinationType {
	if o == nil {
		return ObservabilityWebhookDestinationType("")
	}
	return o.Type
}

func (o *ObservabilityWebhookDestination) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}

func (o *ObservabilityWebhookDestination) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}
