// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type Logic string

const (
	LogicAnd Logic = "and"
	LogicOr  Logic = "or"
)

func (e Logic) ToPointer() *Logic {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Logic) IsExact() bool {
	if e != nil {
		switch *e {
		case "and", "or":
			return true
		}
	}
	return false
}

type Field string

const (
	FieldModel            Field = "model"
	FieldProvider         Field = "provider"
	FieldSessionID        Field = "session_id"
	FieldUserID           Field = "user_id"
	FieldAPIKeyName       Field = "api_key_name"
	FieldFinishReason     Field = "finish_reason"
	FieldInput            Field = "input"
	FieldOutput           Field = "output"
	FieldTotalCost        Field = "total_cost"
	FieldTotalTokens      Field = "total_tokens"
	FieldPromptTokens     Field = "prompt_tokens"
	FieldCompletionTokens Field = "completion_tokens"
)

func (e Field) ToPointer() *Field {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Field) IsExact() bool {
	if e != nil {
		switch *e {
		case "model", "provider", "session_id", "user_id", "api_key_name", "finish_reason", "input", "output", "total_cost", "total_tokens", "prompt_tokens", "completion_tokens":
			return true
		}
	}
	return false
}

type Operator string

const (
	OperatorEquals      Operator = "equals"
	OperatorNotEquals   Operator = "not_equals"
	OperatorContains    Operator = "contains"
	OperatorNotContains Operator = "not_contains"
	OperatorRegex       Operator = "regex"
	OperatorStartsWith  Operator = "starts_with"
	OperatorEndsWith    Operator = "ends_with"
	OperatorGt          Operator = "gt"
	OperatorLt          Operator = "lt"
	OperatorGte         Operator = "gte"
	OperatorLte         Operator = "lte"
	OperatorExists      Operator = "exists"
	OperatorNotExists   Operator = "not_exists"
)

func (e Operator) ToPointer() *Operator {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Operator) IsExact() bool {
	if e != nil {
		switch *e {
		case "equals", "not_equals", "contains", "not_contains", "regex", "starts_with", "ends_with", "gt", "lt", "gte", "lte", "exists", "not_exists":
			return true
		}
	}
	return false
}

type ValueType string

const (
	ValueTypeStr     ValueType = "str"
	ValueTypeNumber  ValueType = "number"
	ValueTypeUnknown ValueType = "Unknown"
)

type Value struct {
	Str        *string         `queryParam:"inline" union:"member"`
	Number     *float64        `queryParam:"inline" union:"member"`
	UnknownRaw json.RawMessage `json:"-" union:"unknown"`

	Type ValueType
}

func CreateValueStr(str string) Value {
	typ := ValueTypeStr

	return Value{
		Str:  &str,
		Type: typ,
	}
}

func CreateValueNumber(number float64) Value {
	typ := ValueTypeNumber

	return Value{
		Number: &number,
		Type:   typ,
	}
}

func CreateValueUnknown(raw json.RawMessage) Value {
	return Value{
		UnknownRaw: raw,
		Type:       ValueTypeUnknown,
	}
}

func (u Value) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u Value) IsUnknown() bool {
	return u.Type == ValueTypeUnknown
}

func (u *Value) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValueTypeStr,
			Value: &str,
		})
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValueTypeNumber,
			Value: &number,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ValueTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ValueTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ValueType)
	switch best.Type {
	case ValueTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case ValueTypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = ValueTypeUnknown
	return nil
}

func (u Value) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type Value: all fields are null")
}

type Rules struct {
	Field    Field    `json:"field"`
	Operator Operator `json:"operator"`
	Value    *Value   `json:"value,omitzero"`
}

func (r Rules) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Rules) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *Rules) GetField() Field {
	if r == nil {
		return Field("")
	}
	return r.Field
}

func (r *Rules) GetOperator() Operator {
	if r == nil {
		return Operator("")
	}
	return r.Operator
}

func (r *Rules) GetValue() *Value {
	if r == nil {
		return nil
	}
	return r.Value
}

type Groups struct {
	Logic *Logic  `default:"and" json:"logic"`
	Rules []Rules `json:"rules"`
}

func (g Groups) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *Groups) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *Groups) GetLogic() *Logic {
	if g == nil {
		return nil
	}
	return g.Logic
}

func (g *Groups) GetRules() []Rules {
	if g == nil {
		return []Rules{}
	}
	return g.Rules
}

// ObservabilityFilterRulesConfig - Optional structured filter rules controlling which events are forwarded.
type ObservabilityFilterRulesConfig struct {
	Enabled *bool    `default:"true" json:"enabled"`
	Groups  []Groups `json:"groups"`
}

func (o ObservabilityFilterRulesConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *ObservabilityFilterRulesConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ObservabilityFilterRulesConfig) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *ObservabilityFilterRulesConfig) GetGroups() []Groups {
	if o == nil {
		return []Groups{}
	}
	return o.Groups
}
