// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type ObservabilityRampDestinationConfig struct {
	// Generate this in your Ramp integration settings.
	APIKey  string  `json:"apiKey"`
	BaseURL *string `default:"https://api.ramp.com/developer/v1/ai-usage/openrouter" json:"baseUrl"`
	// Custom HTTP headers to include in requests to Ramp.
	Headers map[string]string `json:"headers,omitzero"`
}

func (o ObservabilityRampDestinationConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *ObservabilityRampDestinationConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ObservabilityRampDestinationConfig) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *ObservabilityRampDestinationConfig) GetBaseURL() *string {
	if o == nil {
		return nil
	}
	return o.BaseURL
}

func (o *ObservabilityRampDestinationConfig) GetHeaders() map[string]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

type ObservabilityRampDestinationType string

const (
	ObservabilityRampDestinationTypeRamp ObservabilityRampDestinationType = "ramp"
)

func (e ObservabilityRampDestinationType) ToPointer() *ObservabilityRampDestinationType {
	return &e
}
func (e *ObservabilityRampDestinationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ramp":
		*e = ObservabilityRampDestinationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ObservabilityRampDestinationType: %v", v)
	}
}

type ObservabilityRampDestination struct {
	// Optional allowlist of OpenRouter API key hashes (`api_keys.hash`) whose traffic is forwarded to this destination. `null` means all keys.
	APIKeyHashes []string                           `json:"api_key_hashes"`
	Config       ObservabilityRampDestinationConfig `json:"config"`
	// ISO timestamp of when the destination was created.
	CreatedAt string `json:"created_at"`
	// Whether this destination is currently enabled.
	Enabled bool `json:"enabled"`
	// Optional structured filter rules controlling which events are forwarded.
	FilterRules *ObservabilityFilterRulesConfig `json:"filter_rules"`
	// Stable public identifier for this destination.
	ID string `json:"id"`
	// Human-readable name for the destination.
	Name *string `json:"name"`
	// When true, request/response bodies are not forwarded to this destination — only metadata.
	PrivacyMode bool `json:"privacy_mode"`
	// Sampling rate for events sent to this destination, between 0 and 1 (1 = 100%).
	SamplingRate float64                          `json:"sampling_rate"`
	Type         ObservabilityRampDestinationType `json:"type"`
	// ISO timestamp of when the destination was last updated.
	UpdatedAt string `json:"updated_at"`
	// ID of the workspace this destination belongs to.
	WorkspaceID string `json:"workspace_id"`
}

func (o ObservabilityRampDestination) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *ObservabilityRampDestination) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ObservabilityRampDestination) GetAPIKeyHashes() []string {
	if o == nil {
		return nil
	}
	return o.APIKeyHashes
}

func (o *ObservabilityRampDestination) GetConfig() ObservabilityRampDestinationConfig {
	if o == nil {
		return ObservabilityRampDestinationConfig{}
	}
	return o.Config
}

func (o *ObservabilityRampDestination) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *ObservabilityRampDestination) GetEnabled() bool {
	if o == nil {
		return false
	}
	return o.Enabled
}

func (o *ObservabilityRampDestination) GetFilterRules() *ObservabilityFilterRulesConfig {
	if o == nil {
		return nil
	}
	return o.FilterRules
}

func (o *ObservabilityRampDestination) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ObservabilityRampDestination) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ObservabilityRampDestination) GetPrivacyMode() bool {
	if o == nil {
		return false
	}
	return o.PrivacyMode
}

func (o *ObservabilityRampDestination) GetSamplingRate() float64 {
	if o == nil {
		return 0.0
	}
	return o.SamplingRate
}

func (o *ObservabilityRampDestination) GetType() ObservabilityRampDestinationType {
	if o == nil {
		return ObservabilityRampDestinationType("")
	}
	return o.Type
}

func (o *ObservabilityRampDestination) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}

func (o *ObservabilityRampDestination) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}
