// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type ObservabilityPosthogDestinationConfig struct {
	APIKey   string  `json:"apiKey"`
	Endpoint *string `default:"https://us.i.posthog.com" json:"endpoint"`
	// Custom HTTP headers to include in requests to this destination.
	Headers map[string]string `json:"headers,omitzero"`
}

func (o ObservabilityPosthogDestinationConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *ObservabilityPosthogDestinationConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ObservabilityPosthogDestinationConfig) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *ObservabilityPosthogDestinationConfig) GetEndpoint() *string {
	if o == nil {
		return nil
	}
	return o.Endpoint
}

func (o *ObservabilityPosthogDestinationConfig) GetHeaders() map[string]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

type ObservabilityPosthogDestinationType string

const (
	ObservabilityPosthogDestinationTypePosthog ObservabilityPosthogDestinationType = "posthog"
)

func (e ObservabilityPosthogDestinationType) ToPointer() *ObservabilityPosthogDestinationType {
	return &e
}
func (e *ObservabilityPosthogDestinationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "posthog":
		*e = ObservabilityPosthogDestinationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ObservabilityPosthogDestinationType: %v", v)
	}
}

type ObservabilityPosthogDestination struct {
	// Optional allowlist of OpenRouter API key hashes (`api_keys.hash`) whose traffic is forwarded to this destination. `null` means all keys.
	APIKeyHashes []string                              `json:"api_key_hashes"`
	Config       ObservabilityPosthogDestinationConfig `json:"config"`
	// ISO timestamp of when the destination was created.
	CreatedAt string `json:"created_at"`
	// Whether this destination is currently enabled.
	Enabled bool `json:"enabled"`
	// Optional structured filter rules controlling which events are forwarded.
	FilterRules *ObservabilityFilterRulesConfig `json:"filter_rules"`
	// Stable public identifier for this destination.
	ID string `json:"id"`
	// Human-readable name for the destination.
	Name *string `json:"name"`
	// When true, request/response bodies are not forwarded to this destination — only metadata.
	PrivacyMode bool `json:"privacy_mode"`
	// Sampling rate for events sent to this destination, between 0 and 1 (1 = 100%).
	SamplingRate float64                             `json:"sampling_rate"`
	Type         ObservabilityPosthogDestinationType `json:"type"`
	// ISO timestamp of when the destination was last updated.
	UpdatedAt string `json:"updated_at"`
	// ID of the workspace this destination belongs to.
	WorkspaceID string `json:"workspace_id"`
}

func (o ObservabilityPosthogDestination) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *ObservabilityPosthogDestination) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ObservabilityPosthogDestination) GetAPIKeyHashes() []string {
	if o == nil {
		return nil
	}
	return o.APIKeyHashes
}

func (o *ObservabilityPosthogDestination) GetConfig() ObservabilityPosthogDestinationConfig {
	if o == nil {
		return ObservabilityPosthogDestinationConfig{}
	}
	return o.Config
}

func (o *ObservabilityPosthogDestination) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *ObservabilityPosthogDestination) GetEnabled() bool {
	if o == nil {
		return false
	}
	return o.Enabled
}

func (o *ObservabilityPosthogDestination) GetFilterRules() *ObservabilityFilterRulesConfig {
	if o == nil {
		return nil
	}
	return o.FilterRules
}

func (o *ObservabilityPosthogDestination) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ObservabilityPosthogDestination) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ObservabilityPosthogDestination) GetPrivacyMode() bool {
	if o == nil {
		return false
	}
	return o.PrivacyMode
}

func (o *ObservabilityPosthogDestination) GetSamplingRate() float64 {
	if o == nil {
		return 0.0
	}
	return o.SamplingRate
}

func (o *ObservabilityPosthogDestination) GetType() ObservabilityPosthogDestinationType {
	if o == nil {
		return ObservabilityPosthogDestinationType("")
	}
	return o.Type
}

func (o *ObservabilityPosthogDestination) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}

func (o *ObservabilityPosthogDestination) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}
