// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type OpenAIResponseFunctionToolCallType string

const (
	OpenAIResponseFunctionToolCallTypeFunctionCall OpenAIResponseFunctionToolCallType = "function_call"
)

func (e OpenAIResponseFunctionToolCallType) ToPointer() *OpenAIResponseFunctionToolCallType {
	return &e
}
func (e *OpenAIResponseFunctionToolCallType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "function_call":
		*e = OpenAIResponseFunctionToolCallType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OpenAIResponseFunctionToolCallType: %v", v)
	}
}

type OpenAIResponseFunctionToolCall struct {
	Arguments string  `json:"arguments"`
	CallID    string  `json:"call_id"`
	ID        *string `json:"id,omitzero"`
	Name      string  `json:"name"`
	// Namespace qualifier for tools registered as part of a namespace tool group (e.g. an MCP server)
	Namespace *string                            `json:"namespace,omitzero"`
	Status    *ToolCallStatus                    `json:"status,omitzero"`
	Type      OpenAIResponseFunctionToolCallType `json:"type"`
}

func (o OpenAIResponseFunctionToolCall) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OpenAIResponseFunctionToolCall) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OpenAIResponseFunctionToolCall) GetArguments() string {
	if o == nil {
		return ""
	}
	return o.Arguments
}

func (o *OpenAIResponseFunctionToolCall) GetCallID() string {
	if o == nil {
		return ""
	}
	return o.CallID
}

func (o *OpenAIResponseFunctionToolCall) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *OpenAIResponseFunctionToolCall) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *OpenAIResponseFunctionToolCall) GetNamespace() *string {
	if o == nil {
		return nil
	}
	return o.Namespace
}

func (o *OpenAIResponseFunctionToolCall) GetStatus() *ToolCallStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *OpenAIResponseFunctionToolCall) GetType() OpenAIResponseFunctionToolCallType {
	if o == nil {
		return OpenAIResponseFunctionToolCallType("")
	}
	return o.Type
}
