// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type OpenAIResponseCustomToolCallType string

const (
	OpenAIResponseCustomToolCallTypeCustomToolCall OpenAIResponseCustomToolCallType = "custom_tool_call"
)

func (e OpenAIResponseCustomToolCallType) ToPointer() *OpenAIResponseCustomToolCallType {
	return &e
}
func (e *OpenAIResponseCustomToolCallType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "custom_tool_call":
		*e = OpenAIResponseCustomToolCallType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OpenAIResponseCustomToolCallType: %v", v)
	}
}

type OpenAIResponseCustomToolCall struct {
	CallID string  `json:"call_id"`
	ID     *string `json:"id,omitzero"`
	Input  string  `json:"input"`
	Name   string  `json:"name"`
	// Namespace qualifier for tools registered as part of a namespace tool group (e.g. an MCP server)
	Namespace *string                          `json:"namespace,omitzero"`
	Type      OpenAIResponseCustomToolCallType `json:"type"`
}

func (o OpenAIResponseCustomToolCall) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OpenAIResponseCustomToolCall) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OpenAIResponseCustomToolCall) GetCallID() string {
	if o == nil {
		return ""
	}
	return o.CallID
}

func (o *OpenAIResponseCustomToolCall) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *OpenAIResponseCustomToolCall) GetInput() string {
	if o == nil {
		return ""
	}
	return o.Input
}

func (o *OpenAIResponseCustomToolCall) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *OpenAIResponseCustomToolCall) GetNamespace() *string {
	if o == nil {
		return nil
	}
	return o.Namespace
}

func (o *OpenAIResponseCustomToolCall) GetType() OpenAIResponseCustomToolCallType {
	if o == nil {
		return OpenAIResponseCustomToolCallType("")
	}
	return o.Type
}
