// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type OpenAIResponseInputMessageItemContentType string

const (
	OpenAIResponseInputMessageItemContentTypeInputAudio OpenAIResponseInputMessageItemContentType = "input_audio"
	OpenAIResponseInputMessageItemContentTypeInputFile  OpenAIResponseInputMessageItemContentType = "input_file"
	OpenAIResponseInputMessageItemContentTypeInputImage OpenAIResponseInputMessageItemContentType = "input_image"
	OpenAIResponseInputMessageItemContentTypeInputText  OpenAIResponseInputMessageItemContentType = "input_text"
	OpenAIResponseInputMessageItemContentTypeUnknown    OpenAIResponseInputMessageItemContentType = "UNKNOWN"
)

type OpenAIResponseInputMessageItemContent struct {
	InputText  *InputText      `queryParam:"inline" union:"member"`
	InputImage *InputImage     `queryParam:"inline" union:"member"`
	InputFile  *InputFile      `queryParam:"inline" union:"member"`
	InputAudio *InputAudio     `queryParam:"inline" union:"member"`
	UnknownRaw json.RawMessage `json:"-" union:"unknown"`

	Type OpenAIResponseInputMessageItemContentType
}

func CreateOpenAIResponseInputMessageItemContentInputAudio(inputAudio InputAudio) OpenAIResponseInputMessageItemContent {
	typ := OpenAIResponseInputMessageItemContentTypeInputAudio

	typStr := InputAudioType(typ)
	inputAudio.Type = typStr

	return OpenAIResponseInputMessageItemContent{
		InputAudio: &inputAudio,
		Type:       typ,
	}
}

func CreateOpenAIResponseInputMessageItemContentInputFile(inputFile InputFile) OpenAIResponseInputMessageItemContent {
	typ := OpenAIResponseInputMessageItemContentTypeInputFile

	typStr := InputFileType(typ)
	inputFile.Type = typStr

	return OpenAIResponseInputMessageItemContent{
		InputFile: &inputFile,
		Type:      typ,
	}
}

func CreateOpenAIResponseInputMessageItemContentInputImage(inputImage InputImage) OpenAIResponseInputMessageItemContent {
	typ := OpenAIResponseInputMessageItemContentTypeInputImage

	typStr := InputImageType(typ)
	inputImage.Type = typStr

	return OpenAIResponseInputMessageItemContent{
		InputImage: &inputImage,
		Type:       typ,
	}
}

func CreateOpenAIResponseInputMessageItemContentInputText(inputText InputText) OpenAIResponseInputMessageItemContent {
	typ := OpenAIResponseInputMessageItemContentTypeInputText

	typStr := InputTextType(typ)
	inputText.Type = typStr

	return OpenAIResponseInputMessageItemContent{
		InputText: &inputText,
		Type:      typ,
	}
}

func CreateOpenAIResponseInputMessageItemContentUnknown(raw json.RawMessage) OpenAIResponseInputMessageItemContent {
	return OpenAIResponseInputMessageItemContent{
		UnknownRaw: raw,
		Type:       OpenAIResponseInputMessageItemContentTypeUnknown,
	}
}

func (u OpenAIResponseInputMessageItemContent) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u OpenAIResponseInputMessageItemContent) IsUnknown() bool {
	return u.Type == OpenAIResponseInputMessageItemContentTypeUnknown
}

func (u *OpenAIResponseInputMessageItemContent) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = OpenAIResponseInputMessageItemContentTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = OpenAIResponseInputMessageItemContentTypeUnknown
		return nil
	}

	switch dis.Type {
	case "input_audio":
		inputAudio := new(InputAudio)
		if err := utils.UnmarshalJSON(data, &inputAudio, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == input_audio) type InputAudio within OpenAIResponseInputMessageItemContent: %w", string(data), err)
		}

		u.InputAudio = inputAudio
		u.Type = OpenAIResponseInputMessageItemContentTypeInputAudio
		return nil
	case "input_file":
		inputFile := new(InputFile)
		if err := utils.UnmarshalJSON(data, &inputFile, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == input_file) type InputFile within OpenAIResponseInputMessageItemContent: %w", string(data), err)
		}

		u.InputFile = inputFile
		u.Type = OpenAIResponseInputMessageItemContentTypeInputFile
		return nil
	case "input_image":
		inputImage := new(InputImage)
		if err := utils.UnmarshalJSON(data, &inputImage, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == input_image) type InputImage within OpenAIResponseInputMessageItemContent: %w", string(data), err)
		}

		u.InputImage = inputImage
		u.Type = OpenAIResponseInputMessageItemContentTypeInputImage
		return nil
	case "input_text":
		inputText := new(InputText)
		if err := utils.UnmarshalJSON(data, &inputText, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == input_text) type InputText within OpenAIResponseInputMessageItemContent: %w", string(data), err)
		}

		u.InputText = inputText
		u.Type = OpenAIResponseInputMessageItemContentTypeInputText
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = OpenAIResponseInputMessageItemContentTypeUnknown
		return nil
	}

}

func (u OpenAIResponseInputMessageItemContent) MarshalJSON() ([]byte, error) {
	if u.InputText != nil {
		return utils.MarshalJSON(u.InputText, "", true)
	}

	if u.InputImage != nil {
		return utils.MarshalJSON(u.InputImage, "", true)
	}

	if u.InputFile != nil {
		return utils.MarshalJSON(u.InputFile, "", true)
	}

	if u.InputAudio != nil {
		return utils.MarshalJSON(u.InputAudio, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type OpenAIResponseInputMessageItemContent: all fields are null")
}

type OpenAIResponseInputMessageItemRole3 string

const (
	OpenAIResponseInputMessageItemRole3Developer OpenAIResponseInputMessageItemRole3 = "developer"
)

func (e OpenAIResponseInputMessageItemRole3) ToPointer() *OpenAIResponseInputMessageItemRole3 {
	return &e
}
func (e *OpenAIResponseInputMessageItemRole3) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "developer":
		*e = OpenAIResponseInputMessageItemRole3(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OpenAIResponseInputMessageItemRole3: %v", v)
	}
}

type OpenAIResponseInputMessageItemRole2 string

const (
	OpenAIResponseInputMessageItemRole2System OpenAIResponseInputMessageItemRole2 = "system"
)

func (e OpenAIResponseInputMessageItemRole2) ToPointer() *OpenAIResponseInputMessageItemRole2 {
	return &e
}
func (e *OpenAIResponseInputMessageItemRole2) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "system":
		*e = OpenAIResponseInputMessageItemRole2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OpenAIResponseInputMessageItemRole2: %v", v)
	}
}

type OpenAIResponseInputMessageItemRole1 string

const (
	OpenAIResponseInputMessageItemRole1User OpenAIResponseInputMessageItemRole1 = "user"
)

func (e OpenAIResponseInputMessageItemRole1) ToPointer() *OpenAIResponseInputMessageItemRole1 {
	return &e
}
func (e *OpenAIResponseInputMessageItemRole1) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "user":
		*e = OpenAIResponseInputMessageItemRole1(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OpenAIResponseInputMessageItemRole1: %v", v)
	}
}

type OpenAIResponseInputMessageItemRoleType string

const (
	OpenAIResponseInputMessageItemRoleTypeOpenAIResponseInputMessageItemRole1 OpenAIResponseInputMessageItemRoleType = "OpenAIResponseInputMessageItem_role_1"
	OpenAIResponseInputMessageItemRoleTypeOpenAIResponseInputMessageItemRole2 OpenAIResponseInputMessageItemRoleType = "OpenAIResponseInputMessageItem_role_2"
	OpenAIResponseInputMessageItemRoleTypeOpenAIResponseInputMessageItemRole3 OpenAIResponseInputMessageItemRoleType = "OpenAIResponseInputMessageItem_role_3"
	OpenAIResponseInputMessageItemRoleTypeUnknown                             OpenAIResponseInputMessageItemRoleType = "Unknown"
)

type OpenAIResponseInputMessageItemRole struct {
	OpenAIResponseInputMessageItemRole1 *OpenAIResponseInputMessageItemRole1 `queryParam:"inline" union:"member"`
	OpenAIResponseInputMessageItemRole2 *OpenAIResponseInputMessageItemRole2 `queryParam:"inline" union:"member"`
	OpenAIResponseInputMessageItemRole3 *OpenAIResponseInputMessageItemRole3 `queryParam:"inline" union:"member"`
	UnknownRaw                          json.RawMessage                      `json:"-" union:"unknown"`

	Type OpenAIResponseInputMessageItemRoleType
}

func CreateOpenAIResponseInputMessageItemRoleOpenAIResponseInputMessageItemRole1(openAIResponseInputMessageItemRole1 OpenAIResponseInputMessageItemRole1) OpenAIResponseInputMessageItemRole {
	typ := OpenAIResponseInputMessageItemRoleTypeOpenAIResponseInputMessageItemRole1

	return OpenAIResponseInputMessageItemRole{
		OpenAIResponseInputMessageItemRole1: &openAIResponseInputMessageItemRole1,
		Type:                                typ,
	}
}

func CreateOpenAIResponseInputMessageItemRoleOpenAIResponseInputMessageItemRole2(openAIResponseInputMessageItemRole2 OpenAIResponseInputMessageItemRole2) OpenAIResponseInputMessageItemRole {
	typ := OpenAIResponseInputMessageItemRoleTypeOpenAIResponseInputMessageItemRole2

	return OpenAIResponseInputMessageItemRole{
		OpenAIResponseInputMessageItemRole2: &openAIResponseInputMessageItemRole2,
		Type:                                typ,
	}
}

func CreateOpenAIResponseInputMessageItemRoleOpenAIResponseInputMessageItemRole3(openAIResponseInputMessageItemRole3 OpenAIResponseInputMessageItemRole3) OpenAIResponseInputMessageItemRole {
	typ := OpenAIResponseInputMessageItemRoleTypeOpenAIResponseInputMessageItemRole3

	return OpenAIResponseInputMessageItemRole{
		OpenAIResponseInputMessageItemRole3: &openAIResponseInputMessageItemRole3,
		Type:                                typ,
	}
}

func CreateOpenAIResponseInputMessageItemRoleUnknown(raw json.RawMessage) OpenAIResponseInputMessageItemRole {
	return OpenAIResponseInputMessageItemRole{
		UnknownRaw: raw,
		Type:       OpenAIResponseInputMessageItemRoleTypeUnknown,
	}
}

func (u OpenAIResponseInputMessageItemRole) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u OpenAIResponseInputMessageItemRole) IsUnknown() bool {
	return u.Type == OpenAIResponseInputMessageItemRoleTypeUnknown
}

func (u *OpenAIResponseInputMessageItemRole) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var openAIResponseInputMessageItemRole1 OpenAIResponseInputMessageItemRole1 = OpenAIResponseInputMessageItemRole1("")
	if err := utils.UnmarshalJSON(data, &openAIResponseInputMessageItemRole1, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  OpenAIResponseInputMessageItemRoleTypeOpenAIResponseInputMessageItemRole1,
			Value: &openAIResponseInputMessageItemRole1,
		})
	}

	var openAIResponseInputMessageItemRole2 OpenAIResponseInputMessageItemRole2 = OpenAIResponseInputMessageItemRole2("")
	if err := utils.UnmarshalJSON(data, &openAIResponseInputMessageItemRole2, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  OpenAIResponseInputMessageItemRoleTypeOpenAIResponseInputMessageItemRole2,
			Value: &openAIResponseInputMessageItemRole2,
		})
	}

	var openAIResponseInputMessageItemRole3 OpenAIResponseInputMessageItemRole3 = OpenAIResponseInputMessageItemRole3("")
	if err := utils.UnmarshalJSON(data, &openAIResponseInputMessageItemRole3, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  OpenAIResponseInputMessageItemRoleTypeOpenAIResponseInputMessageItemRole3,
			Value: &openAIResponseInputMessageItemRole3,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = OpenAIResponseInputMessageItemRoleTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = OpenAIResponseInputMessageItemRoleTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(OpenAIResponseInputMessageItemRoleType)
	switch best.Type {
	case OpenAIResponseInputMessageItemRoleTypeOpenAIResponseInputMessageItemRole1:
		u.OpenAIResponseInputMessageItemRole1 = best.Value.(*OpenAIResponseInputMessageItemRole1)
		return nil
	case OpenAIResponseInputMessageItemRoleTypeOpenAIResponseInputMessageItemRole2:
		u.OpenAIResponseInputMessageItemRole2 = best.Value.(*OpenAIResponseInputMessageItemRole2)
		return nil
	case OpenAIResponseInputMessageItemRoleTypeOpenAIResponseInputMessageItemRole3:
		u.OpenAIResponseInputMessageItemRole3 = best.Value.(*OpenAIResponseInputMessageItemRole3)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = OpenAIResponseInputMessageItemRoleTypeUnknown
	return nil
}

func (u OpenAIResponseInputMessageItemRole) MarshalJSON() ([]byte, error) {
	if u.OpenAIResponseInputMessageItemRole1 != nil {
		return utils.MarshalJSON(u.OpenAIResponseInputMessageItemRole1, "", true)
	}

	if u.OpenAIResponseInputMessageItemRole2 != nil {
		return utils.MarshalJSON(u.OpenAIResponseInputMessageItemRole2, "", true)
	}

	if u.OpenAIResponseInputMessageItemRole3 != nil {
		return utils.MarshalJSON(u.OpenAIResponseInputMessageItemRole3, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type OpenAIResponseInputMessageItemRole: all fields are null")
}

type OpenAIResponseInputMessageItemType string

const (
	OpenAIResponseInputMessageItemTypeMessage OpenAIResponseInputMessageItemType = "message"
)

func (e OpenAIResponseInputMessageItemType) ToPointer() *OpenAIResponseInputMessageItemType {
	return &e
}
func (e *OpenAIResponseInputMessageItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "message":
		*e = OpenAIResponseInputMessageItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OpenAIResponseInputMessageItemType: %v", v)
	}
}

type OpenAIResponseInputMessageItem struct {
	Content []OpenAIResponseInputMessageItemContent `json:"content"`
	ID      string                                  `json:"id"`
	Role    OpenAIResponseInputMessageItemRole      `json:"role"`
	Type    *OpenAIResponseInputMessageItemType     `json:"type,omitzero"`
}

func (o OpenAIResponseInputMessageItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OpenAIResponseInputMessageItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OpenAIResponseInputMessageItem) GetContent() []OpenAIResponseInputMessageItemContent {
	if o == nil {
		return []OpenAIResponseInputMessageItemContent{}
	}
	return o.Content
}

func (o *OpenAIResponseInputMessageItem) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OpenAIResponseInputMessageItem) GetRole() OpenAIResponseInputMessageItemRole {
	if o == nil {
		return OpenAIResponseInputMessageItemRole{}
	}
	return o.Role
}

func (o *OpenAIResponseInputMessageItem) GetType() *OpenAIResponseInputMessageItemType {
	if o == nil {
		return nil
	}
	return o.Type
}
