// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type OutputModality string

const (
	OutputModalityText          OutputModality = "text"
	OutputModalityImage         OutputModality = "image"
	OutputModalityEmbeddings    OutputModality = "embeddings"
	OutputModalityAudio         OutputModality = "audio"
	OutputModalityVideo         OutputModality = "video"
	OutputModalityRerank        OutputModality = "rerank"
	OutputModalitySpeech        OutputModality = "speech"
	OutputModalityTranscription OutputModality = "transcription"
)

func (e OutputModality) ToPointer() *OutputModality {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *OutputModality) IsExact() bool {
	if e != nil {
		switch *e {
		case "text", "image", "embeddings", "audio", "video", "rerank", "speech", "transcription":
			return true
		}
	}
	return false
}
