// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/optionalnullable"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type PendingSafetyChecks struct {
	Code    string `json:"code"`
	ID      string `json:"id"`
	Message string `json:"message"`
}

func (p PendingSafetyChecks) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PendingSafetyChecks) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PendingSafetyChecks) GetCode() string {
	if p == nil {
		return ""
	}
	return p.Code
}

func (p *PendingSafetyChecks) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PendingSafetyChecks) GetMessage() string {
	if p == nil {
		return ""
	}
	return p.Message
}

type OutputComputerCallItemStatus string

const (
	OutputComputerCallItemStatusCompleted  OutputComputerCallItemStatus = "completed"
	OutputComputerCallItemStatusIncomplete OutputComputerCallItemStatus = "incomplete"
	OutputComputerCallItemStatusInProgress OutputComputerCallItemStatus = "in_progress"
)

func (e OutputComputerCallItemStatus) ToPointer() *OutputComputerCallItemStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *OutputComputerCallItemStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "completed", "incomplete", "in_progress":
			return true
		}
	}
	return false
}

type OutputComputerCallItemType string

const (
	OutputComputerCallItemTypeComputerCall OutputComputerCallItemType = "computer_call"
)

func (e OutputComputerCallItemType) ToPointer() *OutputComputerCallItemType {
	return &e
}
func (e *OutputComputerCallItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "computer_call":
		*e = OutputComputerCallItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OutputComputerCallItemType: %v", v)
	}
}

type OutputComputerCallItem struct {
	Action              optionalnullable.OptionalNullable[any] `json:"action,omitzero"`
	CallID              string                                 `json:"call_id"`
	ID                  *string                                `json:"id,omitzero"`
	PendingSafetyChecks []PendingSafetyChecks                  `json:"pending_safety_checks"`
	Status              OutputComputerCallItemStatus           `json:"status"`
	Type                OutputComputerCallItemType             `json:"type"`
}

func (o OutputComputerCallItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutputComputerCallItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutputComputerCallItem) GetAction() optionalnullable.OptionalNullable[any] {
	if o == nil {
		return nil
	}
	return o.Action
}

func (o *OutputComputerCallItem) GetCallID() string {
	if o == nil {
		return ""
	}
	return o.CallID
}

func (o *OutputComputerCallItem) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *OutputComputerCallItem) GetPendingSafetyChecks() []PendingSafetyChecks {
	if o == nil {
		return []PendingSafetyChecks{}
	}
	return o.PendingSafetyChecks
}

func (o *OutputComputerCallItem) GetStatus() OutputComputerCallItemStatus {
	if o == nil {
		return OutputComputerCallItemStatus("")
	}
	return o.Status
}

func (o *OutputComputerCallItem) GetType() OutputComputerCallItemType {
	if o == nil {
		return OutputComputerCallItemType("")
	}
	return o.Type
}
