// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/optionalnullable"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type OutputWebSearchCallItemAction3Type string

const (
	OutputWebSearchCallItemAction3TypeFindInPage OutputWebSearchCallItemAction3Type = "find_in_page"
)

func (e OutputWebSearchCallItemAction3Type) ToPointer() *OutputWebSearchCallItemAction3Type {
	return &e
}
func (e *OutputWebSearchCallItemAction3Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "find_in_page":
		*e = OutputWebSearchCallItemAction3Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OutputWebSearchCallItemAction3Type: %v", v)
	}
}

type Action3 struct {
	Pattern string                             `json:"pattern"`
	Type    OutputWebSearchCallItemAction3Type `json:"type"`
	URL     string                             `json:"url"`
}

func (a Action3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *Action3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *Action3) GetPattern() string {
	if a == nil {
		return ""
	}
	return a.Pattern
}

func (a *Action3) GetType() OutputWebSearchCallItemAction3Type {
	if a == nil {
		return OutputWebSearchCallItemAction3Type("")
	}
	return a.Type
}

func (a *Action3) GetURL() string {
	if a == nil {
		return ""
	}
	return a.URL
}

// #region class-body-action3
// #endregion class-body-action3

type OutputWebSearchCallItemActionType string

const (
	OutputWebSearchCallItemActionTypeOpenPage OutputWebSearchCallItemActionType = "open_page"
)

func (e OutputWebSearchCallItemActionType) ToPointer() *OutputWebSearchCallItemActionType {
	return &e
}
func (e *OutputWebSearchCallItemActionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "open_page":
		*e = OutputWebSearchCallItemActionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OutputWebSearchCallItemActionType: %v", v)
	}
}

type Action2 struct {
	Type OutputWebSearchCallItemActionType         `json:"type"`
	URL  optionalnullable.OptionalNullable[string] `json:"url,omitzero"`
}

func (a Action2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *Action2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *Action2) GetType() OutputWebSearchCallItemActionType {
	if a == nil {
		return OutputWebSearchCallItemActionType("")
	}
	return a.Type
}

func (a *Action2) GetURL() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.URL
}

// #region class-body-action2
// #endregion class-body-action2

type ActionType string

const (
	ActionTypeSearch ActionType = "search"
)

func (e ActionType) ToPointer() *ActionType {
	return &e
}
func (e *ActionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "search":
		*e = ActionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ActionType: %v", v)
	}
}

type Action1 struct {
	Queries []string          `json:"queries,omitzero"`
	Query   string            `json:"query"`
	Sources []WebSearchSource `json:"sources,omitzero"`
	Type    ActionType        `json:"type"`
}

func (a Action1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *Action1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *Action1) GetQueries() []string {
	if a == nil {
		return nil
	}
	return a.Queries
}

func (a *Action1) GetQuery() string {
	if a == nil {
		return ""
	}
	return a.Query
}

func (a *Action1) GetSources() []WebSearchSource {
	if a == nil {
		return nil
	}
	return a.Sources
}

func (a *Action1) GetType() ActionType {
	if a == nil {
		return ActionType("")
	}
	return a.Type
}

// #region class-body-action1
// #endregion class-body-action1

type ActionUnionType string

const (
	ActionUnionTypeSearch     ActionUnionType = "search"
	ActionUnionTypeOpenPage   ActionUnionType = "open_page"
	ActionUnionTypeFindInPage ActionUnionType = "find_in_page"
	ActionUnionTypeUnknown    ActionUnionType = "UNKNOWN"
)

type Action struct {
	Action1    *Action1        `queryParam:"inline" union:"member"`
	Action2    *Action2        `queryParam:"inline" union:"member"`
	Action3    *Action3        `queryParam:"inline" union:"member"`
	UnknownRaw json.RawMessage `json:"-" union:"unknown"`

	Type ActionUnionType
}

func CreateActionSearch(search Action1) Action {
	typ := ActionUnionTypeSearch

	typStr := ActionType(typ)
	search.Type = typStr

	return Action{
		Action1: &search,
		Type:    typ,
	}
}

func CreateActionOpenPage(openPage Action2) Action {
	typ := ActionUnionTypeOpenPage

	typStr := OutputWebSearchCallItemActionType(typ)
	openPage.Type = typStr

	return Action{
		Action2: &openPage,
		Type:    typ,
	}
}

func CreateActionFindInPage(findInPage Action3) Action {
	typ := ActionUnionTypeFindInPage

	typStr := OutputWebSearchCallItemAction3Type(typ)
	findInPage.Type = typStr

	return Action{
		Action3: &findInPage,
		Type:    typ,
	}
}

func CreateActionUnknown(raw json.RawMessage) Action {
	return Action{
		UnknownRaw: raw,
		Type:       ActionUnionTypeUnknown,
	}
}

func (u Action) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u Action) IsUnknown() bool {
	return u.Type == ActionUnionTypeUnknown
}

func (u *Action) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ActionUnionTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ActionUnionTypeUnknown
		return nil
	}

	switch dis.Type {
	case "search":
		action1 := new(Action1)
		if err := utils.UnmarshalJSON(data, &action1, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == search) type Action1 within Action: %w", string(data), err)
		}

		u.Action1 = action1
		u.Type = ActionUnionTypeSearch
		return nil
	case "open_page":
		action2 := new(Action2)
		if err := utils.UnmarshalJSON(data, &action2, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == open_page) type Action2 within Action: %w", string(data), err)
		}

		u.Action2 = action2
		u.Type = ActionUnionTypeOpenPage
		return nil
	case "find_in_page":
		action3 := new(Action3)
		if err := utils.UnmarshalJSON(data, &action3, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == find_in_page) type Action3 within Action: %w", string(data), err)
		}

		u.Action3 = action3
		u.Type = ActionUnionTypeFindInPage
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ActionUnionTypeUnknown
		return nil
	}

}

func (u Action) MarshalJSON() ([]byte, error) {
	if u.Action1 != nil {
		return utils.MarshalJSON(u.Action1, "", true)
	}

	if u.Action2 != nil {
		return utils.MarshalJSON(u.Action2, "", true)
	}

	if u.Action3 != nil {
		return utils.MarshalJSON(u.Action3, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type Action: all fields are null")
}

type OutputWebSearchCallItemType string

const (
	OutputWebSearchCallItemTypeWebSearchCall OutputWebSearchCallItemType = "web_search_call"
)

func (e OutputWebSearchCallItemType) ToPointer() *OutputWebSearchCallItemType {
	return &e
}
func (e *OutputWebSearchCallItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "web_search_call":
		*e = OutputWebSearchCallItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OutputWebSearchCallItemType: %v", v)
	}
}

type OutputWebSearchCallItem struct {
	Action Action                      `json:"action"`
	ID     string                      `json:"id"`
	Status WebSearchStatus             `json:"status"`
	Type   OutputWebSearchCallItemType `json:"type"`
}

func (o OutputWebSearchCallItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutputWebSearchCallItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutputWebSearchCallItem) GetAction() Action {
	if o == nil {
		return Action{}
	}
	return o.Action
}

func (o *OutputWebSearchCallItem) GetActionSearch() *Action1 {
	return o.GetAction().Action1
}

func (o *OutputWebSearchCallItem) GetActionOpenPage() *Action2 {
	return o.GetAction().Action2
}

func (o *OutputWebSearchCallItem) GetActionFindInPage() *Action3 {
	return o.GetAction().Action3
}

func (o *OutputWebSearchCallItem) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OutputWebSearchCallItem) GetStatus() WebSearchStatus {
	if o == nil {
		return WebSearchStatus("")
	}
	return o.Status
}

func (o *OutputWebSearchCallItem) GetType() OutputWebSearchCallItemType {
	if o == nil {
		return OutputWebSearchCallItemType("")
	}
	return o.Type
}
