// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type OutputBrowserUseServerToolItemType string

const (
	OutputBrowserUseServerToolItemTypeOpenrouterBrowserUse OutputBrowserUseServerToolItemType = "openrouter:browser_use"
)

func (e OutputBrowserUseServerToolItemType) ToPointer() *OutputBrowserUseServerToolItemType {
	return &e
}
func (e *OutputBrowserUseServerToolItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "openrouter:browser_use":
		*e = OutputBrowserUseServerToolItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OutputBrowserUseServerToolItemType: %v", v)
	}
}

// OutputBrowserUseServerToolItem - An openrouter:browser_use server tool output item
type OutputBrowserUseServerToolItem struct {
	Action        *string                            `json:"action,omitzero"`
	ID            *string                            `json:"id,omitzero"`
	ScreenshotB64 *string                            `json:"screenshotB64,omitzero"`
	Status        ToolCallStatus                     `json:"status"`
	Type          OutputBrowserUseServerToolItemType `json:"type"`
}

func (o OutputBrowserUseServerToolItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutputBrowserUseServerToolItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutputBrowserUseServerToolItem) GetAction() *string {
	if o == nil {
		return nil
	}
	return o.Action
}

func (o *OutputBrowserUseServerToolItem) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *OutputBrowserUseServerToolItem) GetScreenshotB64() *string {
	if o == nil {
		return nil
	}
	return o.ScreenshotB64
}

func (o *OutputBrowserUseServerToolItem) GetStatus() ToolCallStatus {
	if o == nil {
		return ToolCallStatus("")
	}
	return o.Status
}

func (o *OutputBrowserUseServerToolItem) GetType() OutputBrowserUseServerToolItemType {
	if o == nil {
		return OutputBrowserUseServerToolItemType("")
	}
	return o.Type
}
