// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type OutputToolSearchServerToolItemType string

const (
	OutputToolSearchServerToolItemTypeOpenrouterToolSearch OutputToolSearchServerToolItemType = "openrouter:tool_search"
)

func (e OutputToolSearchServerToolItemType) ToPointer() *OutputToolSearchServerToolItemType {
	return &e
}
func (e *OutputToolSearchServerToolItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "openrouter:tool_search":
		*e = OutputToolSearchServerToolItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OutputToolSearchServerToolItemType: %v", v)
	}
}

// OutputToolSearchServerToolItem - An openrouter:tool_search server tool output item
type OutputToolSearchServerToolItem struct {
	ID     *string                            `json:"id,omitzero"`
	Query  *string                            `json:"query,omitzero"`
	Status ToolCallStatus                     `json:"status"`
	Type   OutputToolSearchServerToolItemType `json:"type"`
}

func (o OutputToolSearchServerToolItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutputToolSearchServerToolItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutputToolSearchServerToolItem) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *OutputToolSearchServerToolItem) GetQuery() *string {
	if o == nil {
		return nil
	}
	return o.Query
}

func (o *OutputToolSearchServerToolItem) GetStatus() ToolCallStatus {
	if o == nil {
		return ToolCallStatus("")
	}
	return o.Status
}

func (o *OutputToolSearchServerToolItem) GetType() OutputToolSearchServerToolItemType {
	if o == nil {
		return OutputToolSearchServerToolItemType("")
	}
	return o.Type
}
