// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type OutputCustomToolCallItemType string

const (
	OutputCustomToolCallItemTypeCustomToolCall OutputCustomToolCallItemType = "custom_tool_call"
)

func (e OutputCustomToolCallItemType) ToPointer() *OutputCustomToolCallItemType {
	return &e
}
func (e *OutputCustomToolCallItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "custom_tool_call":
		*e = OutputCustomToolCallItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OutputCustomToolCallItemType: %v", v)
	}
}

// OutputCustomToolCallItem - A call to a custom (freeform-grammar) tool created by the model — distinct from `function_call`. Used for tools like Codex CLI's `apply_patch` whose payload is opaque text rather than JSON arguments.
type OutputCustomToolCallItem struct {
	CallID string  `json:"call_id"`
	ID     *string `json:"id,omitzero"`
	Input  string  `json:"input"`
	Name   string  `json:"name"`
	// Namespace qualifier for tools registered as part of a namespace tool group (e.g. an MCP server)
	Namespace *string                      `json:"namespace,omitzero"`
	Type      OutputCustomToolCallItemType `json:"type"`
}

func (o OutputCustomToolCallItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutputCustomToolCallItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutputCustomToolCallItem) GetCallID() string {
	if o == nil {
		return ""
	}
	return o.CallID
}

func (o *OutputCustomToolCallItem) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *OutputCustomToolCallItem) GetInput() string {
	if o == nil {
		return ""
	}
	return o.Input
}

func (o *OutputCustomToolCallItem) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *OutputCustomToolCallItem) GetNamespace() *string {
	if o == nil {
		return nil
	}
	return o.Namespace
}

func (o *OutputCustomToolCallItem) GetType() OutputCustomToolCallItemType {
	if o == nil {
		return OutputCustomToolCallItemType("")
	}
	return o.Type
}
