// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type OutputApplyPatchServerToolItemType string

const (
	OutputApplyPatchServerToolItemTypeOpenrouterApplyPatch OutputApplyPatchServerToolItemType = "openrouter:apply_patch"
)

func (e OutputApplyPatchServerToolItemType) ToPointer() *OutputApplyPatchServerToolItemType {
	return &e
}
func (e *OutputApplyPatchServerToolItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "openrouter:apply_patch":
		*e = OutputApplyPatchServerToolItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OutputApplyPatchServerToolItemType: %v", v)
	}
}

// OutputApplyPatchServerToolItem - An openrouter:apply_patch server tool output item. The turn halts when validation succeeds so the client can apply the patch and echo an `apply_patch_call_output` on the next turn.
type OutputApplyPatchServerToolItem struct {
	CallID *string `json:"call_id,omitzero"`
	ID     *string `json:"id,omitzero"`
	// The patch operation requested by an `apply_patch_call`. `create_file` and `update_file` carry a V4A diff; `delete_file` omits it.
	Operation *ApplyPatchCallOperation           `json:"operation,omitzero"`
	Status    ToolCallStatus                     `json:"status"`
	Type      OutputApplyPatchServerToolItemType `json:"type"`
}

func (o OutputApplyPatchServerToolItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutputApplyPatchServerToolItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutputApplyPatchServerToolItem) GetCallID() *string {
	if o == nil {
		return nil
	}
	return o.CallID
}

func (o *OutputApplyPatchServerToolItem) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *OutputApplyPatchServerToolItem) GetOperation() *ApplyPatchCallOperation {
	if o == nil {
		return nil
	}
	return o.Operation
}

func (o *OutputApplyPatchServerToolItem) GetOperationCreateFile() *ApplyPatchCreateFileOperation {
	if v := o.GetOperation(); v != nil {
		return v.ApplyPatchCreateFileOperation
	}
	return nil
}

func (o *OutputApplyPatchServerToolItem) GetOperationDeleteFile() *ApplyPatchDeleteFileOperation {
	if v := o.GetOperation(); v != nil {
		return v.ApplyPatchDeleteFileOperation
	}
	return nil
}

func (o *OutputApplyPatchServerToolItem) GetOperationUpdateFile() *ApplyPatchUpdateFileOperation {
	if v := o.GetOperation(); v != nil {
		return v.ApplyPatchUpdateFileOperation
	}
	return nil
}

func (o *OutputApplyPatchServerToolItem) GetStatus() ToolCallStatus {
	if o == nil {
		return ToolCallStatus("")
	}
	return o.Status
}

func (o *OutputApplyPatchServerToolItem) GetType() OutputApplyPatchServerToolItemType {
	if o == nil {
		return OutputApplyPatchServerToolItemType("")
	}
	return o.Type
}
