// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type Command string

const (
	CommandView       Command = "view"
	CommandCreate     Command = "create"
	CommandStrReplace Command = "str_replace"
	CommandInsert     Command = "insert"
)

func (e Command) ToPointer() *Command {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Command) IsExact() bool {
	if e != nil {
		switch *e {
		case "view", "create", "str_replace", "insert":
			return true
		}
	}
	return false
}

type OutputTextEditorServerToolItemType string

const (
	OutputTextEditorServerToolItemTypeOpenrouterTextEditor OutputTextEditorServerToolItemType = "openrouter:text_editor"
)

func (e OutputTextEditorServerToolItemType) ToPointer() *OutputTextEditorServerToolItemType {
	return &e
}
func (e *OutputTextEditorServerToolItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "openrouter:text_editor":
		*e = OutputTextEditorServerToolItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OutputTextEditorServerToolItemType: %v", v)
	}
}

// OutputTextEditorServerToolItem - An openrouter:text_editor server tool output item
type OutputTextEditorServerToolItem struct {
	Command  *Command                           `json:"command,omitzero"`
	FilePath *string                            `json:"filePath,omitzero"`
	ID       *string                            `json:"id,omitzero"`
	Status   ToolCallStatus                     `json:"status"`
	Type     OutputTextEditorServerToolItemType `json:"type"`
}

func (o OutputTextEditorServerToolItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutputTextEditorServerToolItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutputTextEditorServerToolItem) GetCommand() *Command {
	if o == nil {
		return nil
	}
	return o.Command
}

func (o *OutputTextEditorServerToolItem) GetFilePath() *string {
	if o == nil {
		return nil
	}
	return o.FilePath
}

func (o *OutputTextEditorServerToolItem) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *OutputTextEditorServerToolItem) GetStatus() ToolCallStatus {
	if o == nil {
		return ToolCallStatus("")
	}
	return o.Status
}

func (o *OutputTextEditorServerToolItem) GetType() OutputTextEditorServerToolItemType {
	if o == nil {
		return OutputTextEditorServerToolItemType("")
	}
	return o.Type
}
