// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ProviderSort - The provider sorting strategy (price, throughput, latency)
type ProviderSort string

const (
	ProviderSortPrice      ProviderSort = "price"
	ProviderSortThroughput ProviderSort = "throughput"
	ProviderSortLatency    ProviderSort = "latency"
	ProviderSortExacto     ProviderSort = "exacto"
)

func (e ProviderSort) ToPointer() *ProviderSort {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ProviderSort) IsExact() bool {
	if e != nil {
		switch *e {
		case "price", "throughput", "latency", "exacto":
			return true
		}
	}
	return false
}
