// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ProviderName string

const (
	ProviderNameAkashMl         ProviderName = "AkashML"
	ProviderNameAi21            ProviderName = "AI21"
	ProviderNameAionLabs        ProviderName = "AionLabs"
	ProviderNameAlibaba         ProviderName = "Alibaba"
	ProviderNameAmbient         ProviderName = "Ambient"
	ProviderNameBaidu           ProviderName = "Baidu"
	ProviderNameAmazonBedrock   ProviderName = "Amazon Bedrock"
	ProviderNameAmazonNova      ProviderName = "Amazon Nova"
	ProviderNameAnthropic       ProviderName = "Anthropic"
	ProviderNameArceeAi         ProviderName = "Arcee AI"
	ProviderNameAtlasCloud      ProviderName = "AtlasCloud"
	ProviderNameAvian           ProviderName = "Avian"
	ProviderNameAzure           ProviderName = "Azure"
	ProviderNameBaseTen         ProviderName = "BaseTen"
	ProviderNameBytePlus        ProviderName = "BytePlus"
	ProviderNameBlackForestLabs ProviderName = "Black Forest Labs"
	ProviderNameCerebras        ProviderName = "Cerebras"
	ProviderNameChutes          ProviderName = "Chutes"
	ProviderNameCirrascale      ProviderName = "Cirrascale"
	ProviderNameClarifai        ProviderName = "Clarifai"
	ProviderNameCloudflare      ProviderName = "Cloudflare"
	ProviderNameCohere          ProviderName = "Cohere"
	ProviderNameCrucible        ProviderName = "Crucible"
	ProviderNameCrusoe          ProviderName = "Crusoe"
	ProviderNameDeepInfra       ProviderName = "DeepInfra"
	ProviderNameDeepSeek        ProviderName = "DeepSeek"
	ProviderNameDekaLlm         ProviderName = "DekaLLM"
	ProviderNameFeatherless     ProviderName = "Featherless"
	ProviderNameFireworks       ProviderName = "Fireworks"
	ProviderNameFriendli        ProviderName = "Friendli"
	ProviderNameGmiCloud        ProviderName = "GMICloud"
	ProviderNameGoogle          ProviderName = "Google"
	ProviderNameGoogleAiStudio  ProviderName = "Google AI Studio"
	ProviderNameGroq            ProviderName = "Groq"
	ProviderNameHyperbolic      ProviderName = "Hyperbolic"
	ProviderNameInception       ProviderName = "Inception"
	ProviderNameInceptron       ProviderName = "Inceptron"
	ProviderNameInferenceNet    ProviderName = "InferenceNet"
	ProviderNameIonstream       ProviderName = "Ionstream"
	ProviderNameInfermatic      ProviderName = "Infermatic"
	ProviderNameIoNet           ProviderName = "Io Net"
	ProviderNameInflection      ProviderName = "Inflection"
	ProviderNameLiquid          ProviderName = "Liquid"
	ProviderNameMara            ProviderName = "Mara"
	ProviderNameMancer2         ProviderName = "Mancer 2"
	ProviderNameMinimax         ProviderName = "Minimax"
	ProviderNameModelRun        ProviderName = "ModelRun"
	ProviderNameMistral         ProviderName = "Mistral"
	ProviderNameModular         ProviderName = "Modular"
	ProviderNameMoonshotAi      ProviderName = "Moonshot AI"
	ProviderNameMorph           ProviderName = "Morph"
	ProviderNameNCompass        ProviderName = "NCompass"
	ProviderNameNebius          ProviderName = "Nebius"
	ProviderNameNexAgi          ProviderName = "Nex AGI"
	ProviderNameNextBit         ProviderName = "NextBit"
	ProviderNameNovita          ProviderName = "Novita"
	ProviderNameNvidia          ProviderName = "Nvidia"
	ProviderNameOpenAi          ProviderName = "OpenAI"
	ProviderNameOpenInference   ProviderName = "OpenInference"
	ProviderNameParasail        ProviderName = "Parasail"
	ProviderNamePoolside        ProviderName = "Poolside"
	ProviderNamePerceptron      ProviderName = "Perceptron"
	ProviderNamePerplexity      ProviderName = "Perplexity"
	ProviderNamePhala           ProviderName = "Phala"
	ProviderNameRecraft         ProviderName = "Recraft"
	ProviderNameReka            ProviderName = "Reka"
	ProviderNameRelace          ProviderName = "Relace"
	ProviderNameSambaNova       ProviderName = "SambaNova"
	ProviderNameSeed            ProviderName = "Seed"
	ProviderNameSiliconFlow     ProviderName = "SiliconFlow"
	ProviderNameSourceful       ProviderName = "Sourceful"
	ProviderNameStepFun         ProviderName = "StepFun"
	ProviderNameStealth         ProviderName = "Stealth"
	ProviderNameStreamLake      ProviderName = "StreamLake"
	ProviderNameSwitchpoint     ProviderName = "Switchpoint"
	ProviderNameTogether        ProviderName = "Together"
	ProviderNameUpstage         ProviderName = "Upstage"
	ProviderNameVenice          ProviderName = "Venice"
	ProviderNameWandB           ProviderName = "WandB"
	ProviderNameXiaomi          ProviderName = "Xiaomi"
	ProviderNameXAi             ProviderName = "xAI"
	ProviderNameZAi             ProviderName = "Z.AI"
	ProviderNameFakeProvider    ProviderName = "FakeProvider"
)

func (e ProviderName) ToPointer() *ProviderName {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ProviderName) IsExact() bool {
	if e != nil {
		switch *e {
		case "AkashML", "AI21", "AionLabs", "Alibaba", "Ambient", "Baidu", "Amazon Bedrock", "Amazon Nova", "Anthropic", "Arcee AI", "AtlasCloud", "Avian", "Azure", "BaseTen", "BytePlus", "Black Forest Labs", "Cerebras", "Chutes", "Cirrascale", "Clarifai", "Cloudflare", "Cohere", "Crucible", "Crusoe", "DeepInfra", "DeepSeek", "DekaLLM", "Featherless", "Fireworks", "Friendli", "GMICloud", "Google", "Google AI Studio", "Groq", "Hyperbolic", "Inception", "Inceptron", "InferenceNet", "Ionstream", "Infermatic", "Io Net", "Inflection", "Liquid", "Mara", "Mancer 2", "Minimax", "ModelRun", "Mistral", "Modular", "Moonshot AI", "Morph", "NCompass", "Nebius", "Nex AGI", "NextBit", "Novita", "Nvidia", "OpenAI", "OpenInference", "Parasail", "Poolside", "Perceptron", "Perplexity", "Phala", "Recraft", "Reka", "Relace", "SambaNova", "Seed", "SiliconFlow", "Sourceful", "StepFun", "Stealth", "StreamLake", "Switchpoint", "Together", "Upstage", "Venice", "WandB", "Xiaomi", "xAI", "Z.AI", "FakeProvider":
			return true
		}
	}
	return false
}
