// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ProviderResponseProviderName - Name of the provider
type ProviderResponseProviderName string

const (
	ProviderResponseProviderNameAnyScale        ProviderResponseProviderName = "AnyScale"
	ProviderResponseProviderNameAtoma           ProviderResponseProviderName = "Atoma"
	ProviderResponseProviderNameCentMl          ProviderResponseProviderName = "Cent-ML"
	ProviderResponseProviderNameCrofAi          ProviderResponseProviderName = "CrofAI"
	ProviderResponseProviderNameEnfer           ProviderResponseProviderName = "Enfer"
	ProviderResponseProviderNameGoPomelo        ProviderResponseProviderName = "GoPomelo"
	ProviderResponseProviderNameHuggingFace     ProviderResponseProviderName = "HuggingFace"
	ProviderResponseProviderNameHyperbolic2     ProviderResponseProviderName = "Hyperbolic 2"
	ProviderResponseProviderNameInoCloud        ProviderResponseProviderName = "InoCloud"
	ProviderResponseProviderNameKluster         ProviderResponseProviderName = "Kluster"
	ProviderResponseProviderNameLambda          ProviderResponseProviderName = "Lambda"
	ProviderResponseProviderNameLepton          ProviderResponseProviderName = "Lepton"
	ProviderResponseProviderNameLynn2           ProviderResponseProviderName = "Lynn 2"
	ProviderResponseProviderNameLynn            ProviderResponseProviderName = "Lynn"
	ProviderResponseProviderNameMancer          ProviderResponseProviderName = "Mancer"
	ProviderResponseProviderNameMeta            ProviderResponseProviderName = "Meta"
	ProviderResponseProviderNameModal           ProviderResponseProviderName = "Modal"
	ProviderResponseProviderNameNineteen        ProviderResponseProviderName = "Nineteen"
	ProviderResponseProviderNameOctoAi          ProviderResponseProviderName = "OctoAI"
	ProviderResponseProviderNameRecursal        ProviderResponseProviderName = "Recursal"
	ProviderResponseProviderNameReflection      ProviderResponseProviderName = "Reflection"
	ProviderResponseProviderNameReplicate       ProviderResponseProviderName = "Replicate"
	ProviderResponseProviderNameSambaNova2      ProviderResponseProviderName = "SambaNova 2"
	ProviderResponseProviderNameSfCompute       ProviderResponseProviderName = "SF Compute"
	ProviderResponseProviderNameTargon          ProviderResponseProviderName = "Targon"
	ProviderResponseProviderNameTogether2       ProviderResponseProviderName = "Together 2"
	ProviderResponseProviderNameUbicloud        ProviderResponseProviderName = "Ubicloud"
	ProviderResponseProviderNameOneDotAi        ProviderResponseProviderName = "01.AI"
	ProviderResponseProviderNameAkashMl         ProviderResponseProviderName = "AkashML"
	ProviderResponseProviderNameAi21            ProviderResponseProviderName = "AI21"
	ProviderResponseProviderNameAionLabs        ProviderResponseProviderName = "AionLabs"
	ProviderResponseProviderNameAlibaba         ProviderResponseProviderName = "Alibaba"
	ProviderResponseProviderNameAmbient         ProviderResponseProviderName = "Ambient"
	ProviderResponseProviderNameBaidu           ProviderResponseProviderName = "Baidu"
	ProviderResponseProviderNameAmazonBedrock   ProviderResponseProviderName = "Amazon Bedrock"
	ProviderResponseProviderNameAmazonNova      ProviderResponseProviderName = "Amazon Nova"
	ProviderResponseProviderNameAnthropic       ProviderResponseProviderName = "Anthropic"
	ProviderResponseProviderNameArceeAi         ProviderResponseProviderName = "Arcee AI"
	ProviderResponseProviderNameAtlasCloud      ProviderResponseProviderName = "AtlasCloud"
	ProviderResponseProviderNameAvian           ProviderResponseProviderName = "Avian"
	ProviderResponseProviderNameAzure           ProviderResponseProviderName = "Azure"
	ProviderResponseProviderNameBaseTen         ProviderResponseProviderName = "BaseTen"
	ProviderResponseProviderNameBytePlus        ProviderResponseProviderName = "BytePlus"
	ProviderResponseProviderNameBlackForestLabs ProviderResponseProviderName = "Black Forest Labs"
	ProviderResponseProviderNameCerebras        ProviderResponseProviderName = "Cerebras"
	ProviderResponseProviderNameChutes          ProviderResponseProviderName = "Chutes"
	ProviderResponseProviderNameCirrascale      ProviderResponseProviderName = "Cirrascale"
	ProviderResponseProviderNameClarifai        ProviderResponseProviderName = "Clarifai"
	ProviderResponseProviderNameCloudflare      ProviderResponseProviderName = "Cloudflare"
	ProviderResponseProviderNameCohere          ProviderResponseProviderName = "Cohere"
	ProviderResponseProviderNameCrucible        ProviderResponseProviderName = "Crucible"
	ProviderResponseProviderNameCrusoe          ProviderResponseProviderName = "Crusoe"
	ProviderResponseProviderNameDeepInfra       ProviderResponseProviderName = "DeepInfra"
	ProviderResponseProviderNameDeepSeek        ProviderResponseProviderName = "DeepSeek"
	ProviderResponseProviderNameDekaLlm         ProviderResponseProviderName = "DekaLLM"
	ProviderResponseProviderNameFeatherless     ProviderResponseProviderName = "Featherless"
	ProviderResponseProviderNameFireworks       ProviderResponseProviderName = "Fireworks"
	ProviderResponseProviderNameFriendli        ProviderResponseProviderName = "Friendli"
	ProviderResponseProviderNameGmiCloud        ProviderResponseProviderName = "GMICloud"
	ProviderResponseProviderNameGoogle          ProviderResponseProviderName = "Google"
	ProviderResponseProviderNameGoogleAiStudio  ProviderResponseProviderName = "Google AI Studio"
	ProviderResponseProviderNameGroq            ProviderResponseProviderName = "Groq"
	ProviderResponseProviderNameHyperbolic      ProviderResponseProviderName = "Hyperbolic"
	ProviderResponseProviderNameInception       ProviderResponseProviderName = "Inception"
	ProviderResponseProviderNameInceptron       ProviderResponseProviderName = "Inceptron"
	ProviderResponseProviderNameInferenceNet    ProviderResponseProviderName = "InferenceNet"
	ProviderResponseProviderNameIonstream       ProviderResponseProviderName = "Ionstream"
	ProviderResponseProviderNameInfermatic      ProviderResponseProviderName = "Infermatic"
	ProviderResponseProviderNameIoNet           ProviderResponseProviderName = "Io Net"
	ProviderResponseProviderNameInflection      ProviderResponseProviderName = "Inflection"
	ProviderResponseProviderNameLiquid          ProviderResponseProviderName = "Liquid"
	ProviderResponseProviderNameMara            ProviderResponseProviderName = "Mara"
	ProviderResponseProviderNameMancer2         ProviderResponseProviderName = "Mancer 2"
	ProviderResponseProviderNameMinimax         ProviderResponseProviderName = "Minimax"
	ProviderResponseProviderNameModelRun        ProviderResponseProviderName = "ModelRun"
	ProviderResponseProviderNameMistral         ProviderResponseProviderName = "Mistral"
	ProviderResponseProviderNameModular         ProviderResponseProviderName = "Modular"
	ProviderResponseProviderNameMoonshotAi      ProviderResponseProviderName = "Moonshot AI"
	ProviderResponseProviderNameMorph           ProviderResponseProviderName = "Morph"
	ProviderResponseProviderNameNCompass        ProviderResponseProviderName = "NCompass"
	ProviderResponseProviderNameNebius          ProviderResponseProviderName = "Nebius"
	ProviderResponseProviderNameNexAgi          ProviderResponseProviderName = "Nex AGI"
	ProviderResponseProviderNameNextBit         ProviderResponseProviderName = "NextBit"
	ProviderResponseProviderNameNovita          ProviderResponseProviderName = "Novita"
	ProviderResponseProviderNameNvidia          ProviderResponseProviderName = "Nvidia"
	ProviderResponseProviderNameOpenAi          ProviderResponseProviderName = "OpenAI"
	ProviderResponseProviderNameOpenInference   ProviderResponseProviderName = "OpenInference"
	ProviderResponseProviderNameParasail        ProviderResponseProviderName = "Parasail"
	ProviderResponseProviderNamePoolside        ProviderResponseProviderName = "Poolside"
	ProviderResponseProviderNamePerceptron      ProviderResponseProviderName = "Perceptron"
	ProviderResponseProviderNamePerplexity      ProviderResponseProviderName = "Perplexity"
	ProviderResponseProviderNamePhala           ProviderResponseProviderName = "Phala"
	ProviderResponseProviderNameRecraft         ProviderResponseProviderName = "Recraft"
	ProviderResponseProviderNameReka            ProviderResponseProviderName = "Reka"
	ProviderResponseProviderNameRelace          ProviderResponseProviderName = "Relace"
	ProviderResponseProviderNameSambaNova       ProviderResponseProviderName = "SambaNova"
	ProviderResponseProviderNameSeed            ProviderResponseProviderName = "Seed"
	ProviderResponseProviderNameSiliconFlow     ProviderResponseProviderName = "SiliconFlow"
	ProviderResponseProviderNameSourceful       ProviderResponseProviderName = "Sourceful"
	ProviderResponseProviderNameStepFun         ProviderResponseProviderName = "StepFun"
	ProviderResponseProviderNameStealth         ProviderResponseProviderName = "Stealth"
	ProviderResponseProviderNameStreamLake      ProviderResponseProviderName = "StreamLake"
	ProviderResponseProviderNameSwitchpoint     ProviderResponseProviderName = "Switchpoint"
	ProviderResponseProviderNameTogether        ProviderResponseProviderName = "Together"
	ProviderResponseProviderNameUpstage         ProviderResponseProviderName = "Upstage"
	ProviderResponseProviderNameVenice          ProviderResponseProviderName = "Venice"
	ProviderResponseProviderNameWandB           ProviderResponseProviderName = "WandB"
	ProviderResponseProviderNameXiaomi          ProviderResponseProviderName = "Xiaomi"
	ProviderResponseProviderNameXAi             ProviderResponseProviderName = "xAI"
	ProviderResponseProviderNameZAi             ProviderResponseProviderName = "Z.AI"
	ProviderResponseProviderNameFakeProvider    ProviderResponseProviderName = "FakeProvider"
)

func (e ProviderResponseProviderName) ToPointer() *ProviderResponseProviderName {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ProviderResponseProviderName) IsExact() bool {
	if e != nil {
		switch *e {
		case "AnyScale", "Atoma", "Cent-ML", "CrofAI", "Enfer", "GoPomelo", "HuggingFace", "Hyperbolic 2", "InoCloud", "Kluster", "Lambda", "Lepton", "Lynn 2", "Lynn", "Mancer", "Meta", "Modal", "Nineteen", "OctoAI", "Recursal", "Reflection", "Replicate", "SambaNova 2", "SF Compute", "Targon", "Together 2", "Ubicloud", "01.AI", "AkashML", "AI21", "AionLabs", "Alibaba", "Ambient", "Baidu", "Amazon Bedrock", "Amazon Nova", "Anthropic", "Arcee AI", "AtlasCloud", "Avian", "Azure", "BaseTen", "BytePlus", "Black Forest Labs", "Cerebras", "Chutes", "Cirrascale", "Clarifai", "Cloudflare", "Cohere", "Crucible", "Crusoe", "DeepInfra", "DeepSeek", "DekaLLM", "Featherless", "Fireworks", "Friendli", "GMICloud", "Google", "Google AI Studio", "Groq", "Hyperbolic", "Inception", "Inceptron", "InferenceNet", "Ionstream", "Infermatic", "Io Net", "Inflection", "Liquid", "Mara", "Mancer 2", "Minimax", "ModelRun", "Mistral", "Modular", "Moonshot AI", "Morph", "NCompass", "Nebius", "Nex AGI", "NextBit", "Novita", "Nvidia", "OpenAI", "OpenInference", "Parasail", "Poolside", "Perceptron", "Perplexity", "Phala", "Recraft", "Reka", "Relace", "SambaNova", "Seed", "SiliconFlow", "Sourceful", "StepFun", "Stealth", "StreamLake", "Switchpoint", "Together", "Upstage", "Venice", "WandB", "Xiaomi", "xAI", "Z.AI", "FakeProvider":
			return true
		}
	}
	return false
}

// ProviderResponse - Details of a provider response for a generation attempt
type ProviderResponse struct {
	// Internal endpoint identifier
	EndpointID *string `json:"endpoint_id,omitzero"`
	// Upstream provider response identifier
	ID *string `json:"id,omitzero"`
	// Whether the request used a bring-your-own-key
	IsByok *bool `json:"is_byok,omitzero"`
	// Response latency in milliseconds
	Latency *float64 `json:"latency,omitzero"`
	// Canonical model slug
	ModelPermaslug *string `json:"model_permaslug,omitzero"`
	// Name of the provider
	ProviderName *ProviderResponseProviderName `json:"provider_name,omitzero"`
	// HTTP status code from the provider
	Status *float64 `json:"status"`
}

func (p *ProviderResponse) GetEndpointID() *string {
	if p == nil {
		return nil
	}
	return p.EndpointID
}

func (p *ProviderResponse) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *ProviderResponse) GetIsByok() *bool {
	if p == nil {
		return nil
	}
	return p.IsByok
}

func (p *ProviderResponse) GetLatency() *float64 {
	if p == nil {
		return nil
	}
	return p.Latency
}

func (p *ProviderResponse) GetModelPermaslug() *string {
	if p == nil {
		return nil
	}
	return p.ModelPermaslug
}

func (p *ProviderResponse) GetProviderName() *ProviderResponseProviderName {
	if p == nil {
		return nil
	}
	return p.ProviderName
}

func (p *ProviderResponse) GetStatus() *float64 {
	if p == nil {
		return nil
	}
	return p.Status
}
