// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type ReasoningDoneEventType string

const (
	ReasoningDoneEventTypeResponseReasoningTextDone ReasoningDoneEventType = "response.reasoning_text.done"
)

func (e ReasoningDoneEventType) ToPointer() *ReasoningDoneEventType {
	return &e
}
func (e *ReasoningDoneEventType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "response.reasoning_text.done":
		*e = ReasoningDoneEventType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ReasoningDoneEventType: %v", v)
	}
}

// ReasoningDoneEvent - Event emitted when reasoning text streaming is complete
type ReasoningDoneEvent struct {
	ContentIndex   int64                  `json:"content_index"`
	ItemID         string                 `json:"item_id"`
	OutputIndex    int64                  `json:"output_index"`
	SequenceNumber int64                  `json:"sequence_number"`
	Text           string                 `json:"text"`
	Type           ReasoningDoneEventType `json:"type"`
}

func (r ReasoningDoneEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReasoningDoneEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReasoningDoneEvent) GetContentIndex() int64 {
	if r == nil {
		return 0
	}
	return r.ContentIndex
}

func (r *ReasoningDoneEvent) GetItemID() string {
	if r == nil {
		return ""
	}
	return r.ItemID
}

func (r *ReasoningDoneEvent) GetOutputIndex() int64 {
	if r == nil {
		return 0
	}
	return r.OutputIndex
}

func (r *ReasoningDoneEvent) GetSequenceNumber() int64 {
	if r == nil {
		return 0
	}
	return r.SequenceNumber
}

func (r *ReasoningDoneEvent) GetText() string {
	if r == nil {
		return ""
	}
	return r.Text
}

func (r *ReasoningDoneEvent) GetType() ReasoningDoneEventType {
	if r == nil {
		return ReasoningDoneEventType("")
	}
	return r.Type
}
