// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type RefusalDeltaEventType string

const (
	RefusalDeltaEventTypeResponseRefusalDelta RefusalDeltaEventType = "response.refusal.delta"
)

func (e RefusalDeltaEventType) ToPointer() *RefusalDeltaEventType {
	return &e
}
func (e *RefusalDeltaEventType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "response.refusal.delta":
		*e = RefusalDeltaEventType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RefusalDeltaEventType: %v", v)
	}
}

// RefusalDeltaEvent - Event emitted when a refusal delta is streamed
type RefusalDeltaEvent struct {
	ContentIndex   int64                 `json:"content_index"`
	Delta          string                `json:"delta"`
	ItemID         string                `json:"item_id"`
	OutputIndex    int64                 `json:"output_index"`
	SequenceNumber int64                 `json:"sequence_number"`
	Type           RefusalDeltaEventType `json:"type"`
}

func (r RefusalDeltaEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RefusalDeltaEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RefusalDeltaEvent) GetContentIndex() int64 {
	if r == nil {
		return 0
	}
	return r.ContentIndex
}

func (r *RefusalDeltaEvent) GetDelta() string {
	if r == nil {
		return ""
	}
	return r.Delta
}

func (r *RefusalDeltaEvent) GetItemID() string {
	if r == nil {
		return ""
	}
	return r.ItemID
}

func (r *RefusalDeltaEvent) GetOutputIndex() int64 {
	if r == nil {
		return 0
	}
	return r.OutputIndex
}

func (r *RefusalDeltaEvent) GetSequenceNumber() int64 {
	if r == nil {
		return 0
	}
	return r.SequenceNumber
}

func (r *RefusalDeltaEvent) GetType() RefusalDeltaEventType {
	if r == nil {
		return RefusalDeltaEventType("")
	}
	return r.Type
}
