// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ResponsesStreamingResponse struct {
	// Union of all possible event types emitted during response streaming
	Data StreamEvents `json:"data"`
}

func (r *ResponsesStreamingResponse) GetData() StreamEvents {
	if r == nil {
		return StreamEvents{}
	}
	return r.Data
}

func (r *ResponsesStreamingResponse) GetDataError() *ErrorEvent {
	return r.GetData().ErrorEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseApplyPatchCallOperationDiffDelta() *ApplyPatchCallOperationDiffDeltaEvent {
	return r.GetData().ApplyPatchCallOperationDiffDeltaEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseApplyPatchCallOperationDiffDone() *ApplyPatchCallOperationDiffDoneEvent {
	return r.GetData().ApplyPatchCallOperationDiffDoneEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseCompleted() *StreamEventsResponseCompleted {
	return r.GetData().StreamEventsResponseCompleted
}

func (r *ResponsesStreamingResponse) GetDataResponseContentPartAdded() *ContentPartAddedEvent {
	return r.GetData().ContentPartAddedEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseContentPartDone() *ContentPartDoneEvent {
	return r.GetData().ContentPartDoneEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseCreated() *OpenResponsesCreatedEvent {
	return r.GetData().OpenResponsesCreatedEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseCustomToolCallInputDelta() *CustomToolCallInputDeltaEvent {
	return r.GetData().CustomToolCallInputDeltaEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseCustomToolCallInputDone() *CustomToolCallInputDoneEvent {
	return r.GetData().CustomToolCallInputDoneEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseFailed() *StreamEventsResponseFailed {
	return r.GetData().StreamEventsResponseFailed
}

func (r *ResponsesStreamingResponse) GetDataResponseFunctionCallArgumentsDelta() *FunctionCallArgsDeltaEvent {
	return r.GetData().FunctionCallArgsDeltaEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseFunctionCallArgumentsDone() *FunctionCallArgsDoneEvent {
	return r.GetData().FunctionCallArgsDoneEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseImageGenerationCallCompleted() *ImageGenCallCompletedEvent {
	return r.GetData().ImageGenCallCompletedEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseImageGenerationCallGenerating() *ImageGenCallGeneratingEvent {
	return r.GetData().ImageGenCallGeneratingEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseImageGenerationCallInProgress() *ImageGenCallInProgressEvent {
	return r.GetData().ImageGenCallInProgressEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseImageGenerationCallPartialImage() *ImageGenCallPartialImageEvent {
	return r.GetData().ImageGenCallPartialImageEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseInProgress() *OpenResponsesInProgressEvent {
	return r.GetData().OpenResponsesInProgressEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseIncomplete() *StreamEventsResponseIncomplete {
	return r.GetData().StreamEventsResponseIncomplete
}

func (r *ResponsesStreamingResponse) GetDataResponseOutputItemAdded() *StreamEventsResponseOutputItemAdded {
	return r.GetData().StreamEventsResponseOutputItemAdded
}

func (r *ResponsesStreamingResponse) GetDataResponseOutputItemDone() *StreamEventsResponseOutputItemDone {
	return r.GetData().StreamEventsResponseOutputItemDone
}

func (r *ResponsesStreamingResponse) GetDataResponseOutputTextAnnotationAdded() *AnnotationAddedEvent {
	return r.GetData().AnnotationAddedEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseOutputTextDelta() *TextDeltaEvent {
	return r.GetData().TextDeltaEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseOutputTextDone() *TextDoneEvent {
	return r.GetData().TextDoneEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseReasoningSummaryPartAdded() *ReasoningSummaryPartAddedEvent {
	return r.GetData().ReasoningSummaryPartAddedEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseReasoningSummaryPartDone() *ReasoningSummaryPartDoneEvent {
	return r.GetData().ReasoningSummaryPartDoneEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseReasoningSummaryTextDelta() *ReasoningSummaryTextDeltaEvent {
	return r.GetData().ReasoningSummaryTextDeltaEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseReasoningSummaryTextDone() *ReasoningSummaryTextDoneEvent {
	return r.GetData().ReasoningSummaryTextDoneEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseReasoningTextDelta() *ReasoningDeltaEvent {
	return r.GetData().ReasoningDeltaEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseReasoningTextDone() *ReasoningDoneEvent {
	return r.GetData().ReasoningDoneEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseRefusalDelta() *RefusalDeltaEvent {
	return r.GetData().RefusalDeltaEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseRefusalDone() *RefusalDoneEvent {
	return r.GetData().RefusalDoneEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseWebSearchCallCompleted() *WebSearchCallCompletedEvent {
	return r.GetData().WebSearchCallCompletedEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseWebSearchCallInProgress() *WebSearchCallInProgressEvent {
	return r.GetData().WebSearchCallInProgressEvent
}

func (r *ResponsesStreamingResponse) GetDataResponseWebSearchCallSearching() *WebSearchCallSearchingEvent {
	return r.GetData().WebSearchCallSearchingEvent
}

func (r ResponsesStreamingResponse) GetEventEncoding(event string) (string, error) {
	return "application/json", nil
}
