// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

// SearchModelsServerToolConfig - Configuration for the openrouter:experimental__search_models server tool
type SearchModelsServerToolConfig struct {
	// Maximum number of models to return. Defaults to 5, max 20.
	MaxResults *int64 `json:"max_results,omitzero"`
}

func (s SearchModelsServerToolConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SearchModelsServerToolConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SearchModelsServerToolConfig) GetMaxResults() *int64 {
	if s == nil {
		return nil
	}
	return s.MaxResults
}
