// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SearchQualityLevel - How much context to retrieve per result. Applies to Exa and Parallel engines; ignored with native provider search and Firecrawl. For Exa, pins a fixed per-result character cap (low=5,000, medium=15,000, high=30,000); when omitted, Exa picks an adaptive size per query and document (typically ~2,000–4,000 characters per result). For Parallel, controls the total characters across all results; when omitted, Parallel uses its own default size.
type SearchQualityLevel string

const (
	SearchQualityLevelLow    SearchQualityLevel = "low"
	SearchQualityLevelMedium SearchQualityLevel = "medium"
	SearchQualityLevelHigh   SearchQualityLevel = "high"
)

func (e SearchQualityLevel) ToPointer() *SearchQualityLevel {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SearchQualityLevel) IsExact() bool {
	if e != nil {
		switch *e {
		case "low", "medium", "high":
			return true
		}
	}
	return false
}
