// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type ShellServerToolType string

const (
	ShellServerToolTypeShell ShellServerToolType = "shell"
)

func (e ShellServerToolType) ToPointer() *ShellServerToolType {
	return &e
}
func (e *ShellServerToolType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "shell":
		*e = ShellServerToolType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ShellServerToolType: %v", v)
	}
}

// ShellServerTool - Shell tool configuration
type ShellServerTool struct {
	Type ShellServerToolType `json:"type"`
}

func (s ShellServerTool) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *ShellServerTool) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *ShellServerTool) GetType() ShellServerToolType {
	if s == nil {
		return ShellServerToolType("")
	}
	return s.Type
}
