// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

// Provider - Provider-specific passthrough configuration
type Provider struct {
	// Provider-specific options keyed by provider slug. The options for the matched provider are spread into the upstream request body.
	Options *ProviderOptions `json:"options,omitzero"`
}

func (p Provider) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Provider) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Provider) GetOptions() *ProviderOptions {
	if p == nil {
		return nil
	}
	return p.Options
}

// ResponseFormat - Audio output format
type ResponseFormat string

const (
	ResponseFormatMp3 ResponseFormat = "mp3"
	ResponseFormatPcm ResponseFormat = "pcm"
)

func (e ResponseFormat) ToPointer() *ResponseFormat {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ResponseFormat) IsExact() bool {
	if e != nil {
		switch *e {
		case "mp3", "pcm":
			return true
		}
	}
	return false
}

// SpeechRequest - Text-to-speech request input
type SpeechRequest struct {
	// Text to synthesize
	Input string `json:"input"`
	// TTS model identifier
	Model string `json:"model"`
	// Provider-specific passthrough configuration
	Provider *Provider `json:"provider,omitzero"`
	// Audio output format
	ResponseFormat *ResponseFormat `default:"pcm" json:"response_format"`
	// Playback speed multiplier. Only used by models that support it (e.g. OpenAI TTS). Ignored by other providers.
	Speed *float64 `json:"speed,omitzero"`
	// Voice identifier (provider-specific).
	Voice string `json:"voice"`
}

func (s SpeechRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SpeechRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SpeechRequest) GetInput() string {
	if s == nil {
		return ""
	}
	return s.Input
}

func (s *SpeechRequest) GetModel() string {
	if s == nil {
		return ""
	}
	return s.Model
}

func (s *SpeechRequest) GetProvider() *Provider {
	if s == nil {
		return nil
	}
	return s.Provider
}

func (s *SpeechRequest) GetResponseFormat() *ResponseFormat {
	if s == nil {
		return nil
	}
	return s.ResponseFormat
}

func (s *SpeechRequest) GetSpeed() *float64 {
	if s == nil {
		return nil
	}
	return s.Speed
}

func (s *SpeechRequest) GetVoice() string {
	if s == nil {
		return ""
	}
	return s.Voice
}
