// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type StreamEventsResponseIncompleteType string

const (
	StreamEventsResponseIncompleteTypeResponseIncomplete StreamEventsResponseIncompleteType = "response.incomplete"
)

func (e StreamEventsResponseIncompleteType) ToPointer() *StreamEventsResponseIncompleteType {
	return &e
}
func (e *StreamEventsResponseIncompleteType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "response.incomplete":
		*e = StreamEventsResponseIncompleteType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StreamEventsResponseIncompleteType: %v", v)
	}
}

// StreamEventsResponseIncomplete - Event emitted when a response is incomplete
type StreamEventsResponseIncomplete struct {
	// Complete non-streaming response from the Responses API
	Response       OpenResponsesResult                `json:"response"`
	SequenceNumber int64                              `json:"sequence_number"`
	Type           StreamEventsResponseIncompleteType `json:"type"`
}

func (s StreamEventsResponseIncomplete) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StreamEventsResponseIncomplete) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StreamEventsResponseIncomplete) GetResponse() OpenResponsesResult {
	if s == nil {
		return OpenResponsesResult{}
	}
	return s.Response
}

func (s *StreamEventsResponseIncomplete) GetSequenceNumber() int64 {
	if s == nil {
		return 0
	}
	return s.SequenceNumber
}

func (s *StreamEventsResponseIncomplete) GetType() StreamEventsResponseIncompleteType {
	if s == nil {
		return StreamEventsResponseIncompleteType("")
	}
	return s.Type
}
