// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/optionalnullable"
)

// TopProviderInfo - Information about the top provider for this model
type TopProviderInfo struct {
	// Context length from the top provider
	ContextLength optionalnullable.OptionalNullable[int64] `json:"context_length,omitzero"`
	// Whether the top provider moderates content
	IsModerated bool `json:"is_moderated"`
	// Maximum completion tokens from the top provider
	MaxCompletionTokens optionalnullable.OptionalNullable[int64] `json:"max_completion_tokens,omitzero"`
}

func (t *TopProviderInfo) GetContextLength() optionalnullable.OptionalNullable[int64] {
	if t == nil {
		return nil
	}
	return t.ContextLength
}

func (t *TopProviderInfo) GetIsModerated() bool {
	if t == nil {
		return false
	}
	return t.IsModerated
}

func (t *TopProviderInfo) GetMaxCompletionTokens() optionalnullable.OptionalNullable[int64] {
	if t == nil {
		return nil
	}
	return t.MaxCompletionTokens
}
