// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

// TraceConfig - Metadata for observability and tracing. Known keys (trace_id, trace_name, span_name, generation_name, parent_span_id) have special handling. Additional keys are passed through as custom metadata to configured broadcast destinations.
type TraceConfig struct {
	GenerationName       *string        `json:"generation_name,omitzero"`
	ParentSpanID         *string        `json:"parent_span_id,omitzero"`
	SpanName             *string        `json:"span_name,omitzero"`
	TraceID              *string        `json:"trace_id,omitzero"`
	TraceName            *string        `json:"trace_name,omitzero"`
	AdditionalProperties map[string]any `additionalProperties:"true" json:"-"`
}

func (t TraceConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TraceConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TraceConfig) GetGenerationName() *string {
	if t == nil {
		return nil
	}
	return t.GenerationName
}

func (t *TraceConfig) GetParentSpanID() *string {
	if t == nil {
		return nil
	}
	return t.ParentSpanID
}

func (t *TraceConfig) GetSpanName() *string {
	if t == nil {
		return nil
	}
	return t.SpanName
}

func (t *TraceConfig) GetTraceID() *string {
	if t == nil {
		return nil
	}
	return t.TraceID
}

func (t *TraceConfig) GetTraceName() *string {
	if t == nil {
		return nil
	}
	return t.TraceName
}

func (t *TraceConfig) GetAdditionalProperties() map[string]any {
	if t == nil {
		return nil
	}
	return t.AdditionalProperties
}
