// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Truncation string

const (
	TruncationAuto     Truncation = "auto"
	TruncationDisabled Truncation = "disabled"
)

func (e Truncation) ToPointer() *Truncation {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Truncation) IsExact() bool {
	if e != nil {
		switch *e {
		case "auto", "disabled":
			return true
		}
	}
	return false
}
