// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/optionalnullable"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type UpdateGuardrailRequest struct {
	// Array of model identifiers (slug or canonical_slug accepted)
	AllowedModels optionalnullable.OptionalNullable[[]string] `json:"allowed_models,omitzero"`
	// New list of allowed provider IDs
	AllowedProviders optionalnullable.OptionalNullable[[]string] `json:"allowed_providers,omitzero"`
	// Builtin content filters to apply. Set to null to remove. The "flag" action is only supported for "regex-prompt-injection"; PII slugs (email, phone, ssn, credit-card, ip-address, person-name, address) accept "block" or "redact" only.
	ContentFilterBuiltins optionalnullable.OptionalNullable[[]ContentFilterBuiltinEntry] `json:"content_filter_builtins,omitzero"`
	// Custom regex content filters to apply. Set to null to remove.
	ContentFilters optionalnullable.OptionalNullable[[]ContentFilterEntry] `json:"content_filters,omitzero"`
	// New description for the guardrail
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// Deprecated. Use enforce_zdr_anthropic, enforce_zdr_openai, enforce_zdr_google, and enforce_zdr_other instead. When provided, its value is copied into any of those per-provider fields that are not explicitly specified on the request.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	EnforceZdr optionalnullable.OptionalNullable[bool] `json:"enforce_zdr,omitzero"`
	// Whether to enforce zero data retention for Anthropic models. Falls back to enforce_zdr when not provided.
	EnforceZdrAnthropic optionalnullable.OptionalNullable[bool] `json:"enforce_zdr_anthropic,omitzero"`
	// Whether to enforce zero data retention for Google models. Falls back to enforce_zdr when not provided.
	EnforceZdrGoogle optionalnullable.OptionalNullable[bool] `json:"enforce_zdr_google,omitzero"`
	// Whether to enforce zero data retention for OpenAI models. Falls back to enforce_zdr when not provided.
	EnforceZdrOpenai optionalnullable.OptionalNullable[bool] `json:"enforce_zdr_openai,omitzero"`
	// Whether to enforce zero data retention for models that are not from Anthropic, OpenAI, or Google. Falls back to enforce_zdr when not provided.
	EnforceZdrOther optionalnullable.OptionalNullable[bool] `json:"enforce_zdr_other,omitzero"`
	// Array of model identifiers to exclude from routing (slug or canonical_slug accepted)
	IgnoredModels optionalnullable.OptionalNullable[[]string] `json:"ignored_models,omitzero"`
	// List of provider IDs to exclude from routing
	IgnoredProviders optionalnullable.OptionalNullable[[]string] `json:"ignored_providers,omitzero"`
	// New spending limit in USD
	LimitUsd optionalnullable.OptionalNullable[float64] `json:"limit_usd,omitzero"`
	// New name for the guardrail
	Name *string `json:"name,omitzero"`
	// Interval at which the limit resets (daily, weekly, monthly)
	ResetInterval optionalnullable.OptionalNullable[GuardrailInterval] `json:"reset_interval,omitzero"`
}

func (u UpdateGuardrailRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateGuardrailRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateGuardrailRequest) GetAllowedModels() optionalnullable.OptionalNullable[[]string] {
	if u == nil {
		return nil
	}
	return u.AllowedModels
}

func (u *UpdateGuardrailRequest) GetAllowedProviders() optionalnullable.OptionalNullable[[]string] {
	if u == nil {
		return nil
	}
	return u.AllowedProviders
}

func (u *UpdateGuardrailRequest) GetContentFilterBuiltins() optionalnullable.OptionalNullable[[]ContentFilterBuiltinEntry] {
	if u == nil {
		return nil
	}
	return u.ContentFilterBuiltins
}

func (u *UpdateGuardrailRequest) GetContentFilters() optionalnullable.OptionalNullable[[]ContentFilterEntry] {
	if u == nil {
		return nil
	}
	return u.ContentFilters
}

func (u *UpdateGuardrailRequest) GetDescription() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateGuardrailRequest) GetEnforceZdr() optionalnullable.OptionalNullable[bool] {
	if u == nil {
		return nil
	}
	return u.EnforceZdr
}

func (u *UpdateGuardrailRequest) GetEnforceZdrAnthropic() optionalnullable.OptionalNullable[bool] {
	if u == nil {
		return nil
	}
	return u.EnforceZdrAnthropic
}

func (u *UpdateGuardrailRequest) GetEnforceZdrGoogle() optionalnullable.OptionalNullable[bool] {
	if u == nil {
		return nil
	}
	return u.EnforceZdrGoogle
}

func (u *UpdateGuardrailRequest) GetEnforceZdrOpenai() optionalnullable.OptionalNullable[bool] {
	if u == nil {
		return nil
	}
	return u.EnforceZdrOpenai
}

func (u *UpdateGuardrailRequest) GetEnforceZdrOther() optionalnullable.OptionalNullable[bool] {
	if u == nil {
		return nil
	}
	return u.EnforceZdrOther
}

func (u *UpdateGuardrailRequest) GetIgnoredModels() optionalnullable.OptionalNullable[[]string] {
	if u == nil {
		return nil
	}
	return u.IgnoredModels
}

func (u *UpdateGuardrailRequest) GetIgnoredProviders() optionalnullable.OptionalNullable[[]string] {
	if u == nil {
		return nil
	}
	return u.IgnoredProviders
}

func (u *UpdateGuardrailRequest) GetLimitUsd() optionalnullable.OptionalNullable[float64] {
	if u == nil {
		return nil
	}
	return u.LimitUsd
}

func (u *UpdateGuardrailRequest) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateGuardrailRequest) GetResetInterval() optionalnullable.OptionalNullable[GuardrailInterval] {
	if u == nil {
		return nil
	}
	return u.ResetInterval
}
