// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/optionalnullable"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type UpdateObservabilityDestinationRequest struct {
	// Optional allowlist of OpenRouter API key hashes. `null` clears the filter (all keys). Omitting leaves the current value. Must contain at least one hash if provided.
	APIKeyHashes optionalnullable.OptionalNullable[[]string] `json:"api_key_hashes,omitzero"`
	// Provider-specific configuration fields to update. Masked values are ignored; unset fields keep their current value.
	Config map[string]any `json:"config,omitzero"`
	// Whether the destination is enabled.
	Enabled     *bool                                                             `json:"enabled,omitzero"`
	FilterRules optionalnullable.OptionalNullable[ObservabilityFilterRulesConfig] `json:"filter_rules,omitzero"`
	// Human-readable name for the destination.
	Name *string `json:"name,omitzero"`
	// When true, request/response bodies are not forwarded — only metadata.
	PrivacyMode *bool `json:"privacy_mode,omitzero"`
	// Sampling rate between 0 and 1 (1 = 100%).
	SamplingRate *float64 `json:"sampling_rate,omitzero"`
}

func (u UpdateObservabilityDestinationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateObservabilityDestinationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateObservabilityDestinationRequest) GetAPIKeyHashes() optionalnullable.OptionalNullable[[]string] {
	if u == nil {
		return nil
	}
	return u.APIKeyHashes
}

func (u *UpdateObservabilityDestinationRequest) GetConfig() map[string]any {
	if u == nil {
		return nil
	}
	return u.Config
}

func (u *UpdateObservabilityDestinationRequest) GetEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.Enabled
}

func (u *UpdateObservabilityDestinationRequest) GetFilterRules() optionalnullable.OptionalNullable[ObservabilityFilterRulesConfig] {
	if u == nil {
		return nil
	}
	return u.FilterRules
}

func (u *UpdateObservabilityDestinationRequest) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateObservabilityDestinationRequest) GetPrivacyMode() *bool {
	if u == nil {
		return nil
	}
	return u.PrivacyMode
}

func (u *UpdateObservabilityDestinationRequest) GetSamplingRate() *float64 {
	if u == nil {
		return nil
	}
	return u.SamplingRate
}
