// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateObservabilityDestinationResponse struct {
	Data ObservabilityDestination `json:"data"`
}

func (u *UpdateObservabilityDestinationResponse) GetData() ObservabilityDestination {
	if u == nil {
		return ObservabilityDestination{}
	}
	return u.Data
}

func (u *UpdateObservabilityDestinationResponse) GetDataArize() *ObservabilityArizeDestination {
	return u.GetData().ObservabilityArizeDestination
}

func (u *UpdateObservabilityDestinationResponse) GetDataBraintrust() *ObservabilityBraintrustDestination {
	return u.GetData().ObservabilityBraintrustDestination
}

func (u *UpdateObservabilityDestinationResponse) GetDataClickhouse() *ObservabilityClickhouseDestination {
	return u.GetData().ObservabilityClickhouseDestination
}

func (u *UpdateObservabilityDestinationResponse) GetDataDatadog() *ObservabilityDatadogDestination {
	return u.GetData().ObservabilityDatadogDestination
}

func (u *UpdateObservabilityDestinationResponse) GetDataGrafana() *ObservabilityGrafanaDestination {
	return u.GetData().ObservabilityGrafanaDestination
}

func (u *UpdateObservabilityDestinationResponse) GetDataLangfuse() *ObservabilityLangfuseDestination {
	return u.GetData().ObservabilityLangfuseDestination
}

func (u *UpdateObservabilityDestinationResponse) GetDataLangsmith() *ObservabilityLangsmithDestination {
	return u.GetData().ObservabilityLangsmithDestination
}

func (u *UpdateObservabilityDestinationResponse) GetDataNewrelic() *ObservabilityNewrelicDestination {
	return u.GetData().ObservabilityNewrelicDestination
}

func (u *UpdateObservabilityDestinationResponse) GetDataOpik() *ObservabilityOpikDestination {
	return u.GetData().ObservabilityOpikDestination
}

func (u *UpdateObservabilityDestinationResponse) GetDataOtelCollector() *ObservabilityOtelCollectorDestination {
	return u.GetData().ObservabilityOtelCollectorDestination
}

func (u *UpdateObservabilityDestinationResponse) GetDataPosthog() *ObservabilityPosthogDestination {
	return u.GetData().ObservabilityPosthogDestination
}

func (u *UpdateObservabilityDestinationResponse) GetDataRamp() *ObservabilityRampDestination {
	return u.GetData().ObservabilityRampDestination
}

func (u *UpdateObservabilityDestinationResponse) GetDataS3() *ObservabilityS3Destination {
	return u.GetData().ObservabilityS3Destination
}

func (u *UpdateObservabilityDestinationResponse) GetDataSentry() *ObservabilitySentryDestination {
	return u.GetData().ObservabilitySentryDestination
}

func (u *UpdateObservabilityDestinationResponse) GetDataSnowflake() *ObservabilitySnowflakeDestination {
	return u.GetData().ObservabilitySnowflakeDestination
}

func (u *UpdateObservabilityDestinationResponse) GetDataWeave() *ObservabilityWeaveDestination {
	return u.GetData().ObservabilityWeaveDestination
}

func (u *UpdateObservabilityDestinationResponse) GetDataWebhook() *ObservabilityWebhookDestination {
	return u.GetData().ObservabilityWebhookDestination
}
