// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type WebFetchPluginID string

const (
	WebFetchPluginIDWebFetch WebFetchPluginID = "web-fetch"
)

func (e WebFetchPluginID) ToPointer() *WebFetchPluginID {
	return &e
}
func (e *WebFetchPluginID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "web-fetch":
		*e = WebFetchPluginID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WebFetchPluginID: %v", v)
	}
}

type WebFetchPlugin struct {
	// Only fetch from these domains.
	AllowedDomains []string `json:"allowed_domains,omitzero"`
	// Never fetch from these domains.
	BlockedDomains []string         `json:"blocked_domains,omitzero"`
	ID             WebFetchPluginID `json:"id"`
	// Maximum content length in approximate tokens. Content exceeding this limit is truncated.
	MaxContentTokens *int64 `json:"max_content_tokens,omitzero"`
	// Maximum number of web fetches per request. Once exceeded, the tool returns an error.
	MaxUses *int64 `json:"max_uses,omitzero"`
}

func (w WebFetchPlugin) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebFetchPlugin) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebFetchPlugin) GetAllowedDomains() []string {
	if w == nil {
		return nil
	}
	return w.AllowedDomains
}

func (w *WebFetchPlugin) GetBlockedDomains() []string {
	if w == nil {
		return nil
	}
	return w.BlockedDomains
}

func (w *WebFetchPlugin) GetID() WebFetchPluginID {
	if w == nil {
		return WebFetchPluginID("")
	}
	return w.ID
}

func (w *WebFetchPlugin) GetMaxContentTokens() *int64 {
	if w == nil {
		return nil
	}
	return w.MaxContentTokens
}

func (w *WebFetchPlugin) GetMaxUses() *int64 {
	if w == nil {
		return nil
	}
	return w.MaxUses
}
