// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/kenrogers/openrouter-cli/internal/sdk/optionalnullable"
	"github.com/kenrogers/openrouter-cli/internal/sdk/sdkinternal/utils"
)

type WebSearchDomainFilter struct {
	AllowedDomains  optionalnullable.OptionalNullable[[]string] `json:"allowed_domains,omitzero"`
	ExcludedDomains optionalnullable.OptionalNullable[[]string] `json:"excluded_domains,omitzero"`
}

func (w WebSearchDomainFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebSearchDomainFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebSearchDomainFilter) GetAllowedDomains() optionalnullable.OptionalNullable[[]string] {
	if w == nil {
		return nil
	}
	return w.AllowedDomains
}

func (w *WebSearchDomainFilter) GetExcludedDomains() optionalnullable.OptionalNullable[[]string] {
	if w == nil {
		return nil
	}
	return w.ExcludedDomains
}
