// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// WebSearchEngineEnum - Which search engine to use. "auto" (default) uses native if the provider supports it, otherwise Exa. "native" forces the provider's built-in search. "exa" forces the Exa search API. "firecrawl" uses Firecrawl (requires BYOK). "parallel" uses the Parallel search API.
type WebSearchEngineEnum string

const (
	WebSearchEngineEnumAuto      WebSearchEngineEnum = "auto"
	WebSearchEngineEnumNative    WebSearchEngineEnum = "native"
	WebSearchEngineEnumExa       WebSearchEngineEnum = "exa"
	WebSearchEngineEnumFirecrawl WebSearchEngineEnum = "firecrawl"
	WebSearchEngineEnumParallel  WebSearchEngineEnum = "parallel"
)

func (e WebSearchEngineEnum) ToPointer() *WebSearchEngineEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *WebSearchEngineEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "auto", "native", "exa", "firecrawl", "parallel":
			return true
		}
	}
	return false
}
