// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Workspace struct {
	// ISO 8601 timestamp of when the workspace was created
	CreatedAt string `json:"created_at"`
	// User ID of the workspace creator
	CreatedBy *string `json:"created_by"`
	// Default image model for this workspace
	DefaultImageModel *string `json:"default_image_model"`
	// Default provider sort preference (price, throughput, latency, exacto)
	DefaultProviderSort *string `json:"default_provider_sort"`
	// Default text model for this workspace
	DefaultTextModel *string `json:"default_text_model"`
	// Description of the workspace
	Description *string `json:"description"`
	// Unique identifier for the workspace
	ID string `json:"id"`
	// Optional array of API key IDs to filter I/O logging. Null means all keys are logged.
	IoLoggingAPIKeyIds []int64 `json:"io_logging_api_key_ids"`
	// Sampling rate for I/O logging (0.0001-1). 1 means 100% of requests are logged.
	IoLoggingSamplingRate float64 `json:"io_logging_sampling_rate"`
	// Whether data discount logging is enabled for this workspace
	IsDataDiscountLoggingEnabled bool `json:"is_data_discount_logging_enabled"`
	// Whether broadcast is enabled for this workspace
	IsObservabilityBroadcastEnabled bool `json:"is_observability_broadcast_enabled"`
	// Whether private logging is enabled for this workspace
	IsObservabilityIoLoggingEnabled bool `json:"is_observability_io_logging_enabled"`
	// Name of the workspace
	Name string `json:"name"`
	// URL-friendly slug for the workspace
	Slug string `json:"slug"`
	// ISO 8601 timestamp of when the workspace was last updated
	UpdatedAt *string `json:"updated_at"`
}

func (w *Workspace) GetCreatedAt() string {
	if w == nil {
		return ""
	}
	return w.CreatedAt
}

func (w *Workspace) GetCreatedBy() *string {
	if w == nil {
		return nil
	}
	return w.CreatedBy
}

func (w *Workspace) GetDefaultImageModel() *string {
	if w == nil {
		return nil
	}
	return w.DefaultImageModel
}

func (w *Workspace) GetDefaultProviderSort() *string {
	if w == nil {
		return nil
	}
	return w.DefaultProviderSort
}

func (w *Workspace) GetDefaultTextModel() *string {
	if w == nil {
		return nil
	}
	return w.DefaultTextModel
}

func (w *Workspace) GetDescription() *string {
	if w == nil {
		return nil
	}
	return w.Description
}

func (w *Workspace) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

func (w *Workspace) GetIoLoggingAPIKeyIds() []int64 {
	if w == nil {
		return nil
	}
	return w.IoLoggingAPIKeyIds
}

func (w *Workspace) GetIoLoggingSamplingRate() float64 {
	if w == nil {
		return 0.0
	}
	return w.IoLoggingSamplingRate
}

func (w *Workspace) GetIsDataDiscountLoggingEnabled() bool {
	if w == nil {
		return false
	}
	return w.IsDataDiscountLoggingEnabled
}

func (w *Workspace) GetIsObservabilityBroadcastEnabled() bool {
	if w == nil {
		return false
	}
	return w.IsObservabilityBroadcastEnabled
}

func (w *Workspace) GetIsObservabilityIoLoggingEnabled() bool {
	if w == nil {
		return false
	}
	return w.IsObservabilityIoLoggingEnabled
}

func (w *Workspace) GetName() string {
	if w == nil {
		return ""
	}
	return w.Name
}

func (w *Workspace) GetSlug() string {
	if w == nil {
		return ""
	}
	return w.Slug
}

func (w *Workspace) GetUpdatedAt() *string {
	if w == nil {
		return nil
	}
	return w.UpdatedAt
}
